### ISSUE TITLE
Discussion: Drop (possibly useless) things from customizer

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/wd_s#100]
The customizer is pretty powerful and we can hook into it to do a lot of things that are done on every site - a logo, social links, footer copyright text, etc.

But when's the last time we actually had someone use colors or background image in the customizer?  We JUST used the background image field for a site and it's literally the only time I've ever used it.

I think maybe we could do with adding filters to remove those items that may be un-uitilized on a regular basis.  If they need to be added in for a specific project, we could easily remove the filter that removes the fields/sections from the customizer.

**Comment by gregrickaby** [comment]
Or just comment out the line in `functions.php` that powers the customizer?

https://github.com/WebDevStudios/wd_s/blob/master/functions.php#L163

**Comment by coreymcollins** [comment]
I would probably lean more toward leaving that file in and just making customizations to the /inc/customizer.php file myself once we figure out which essential customizer sections should exist.  I know we're talking about support for header/logo here: https://github.com/WebDevStudios/wd_s/issues/94

Maybe there's a use case for having social icons and copyright text by default as well?  Not sure.  But, I don't think the solution is to comment out the customizer include all together.

Personally, having pieces of code commented out looks sloppy or lazy to me.  If you don't want to use something, then remove it.  If it's something that needs instruction on how to use, then add those instructions to the readme.

**Comment by gregrickaby** [comment]
I'm talking about should this functionality be included by default. If the answer is no, then remove the include from `functions.php` - but leave the file inside `/inc`. If you want to use the customizer, just add the file include to `functions.php`. Same goes for Jetpack. 

I love the idea of adding Social Icons and copyright text to the customizer. This is definitely something the client should be curating after we're done with their project.

**Comment by coreymcollins** [comment]
I think you just answered the question yourself, unless we're just missing what the other is saying --

You love the idea of adding social icons and copyright text to the customizer.  So, by that point, then we should NOT be removing the include from functions.php because we'll need to add our own customizer sections (social links and copyright) in a default wd_s experience.  Right?

**Comment by gregrickaby** [comment]
Lol, we're on the same page :) 

Next up....customizing Page Builder parts with the Customizer!

**Comment by coreymcollins** [comment]
:thumbsup:

**Comment by briannaorg** [comment]
YES we need social icons and footer/copyright stuff in the Customizer. And I am actually really excited about handling PB customizations there too.

**Comment by gregrickaby** [comment]
The entire Page Builder UX can be very cumbersome. Especially when dealing with many parts with custom fields. I would love to get this over into the customizer. If anyone wants to take a stab at it...feel free!

**Comment by gregrickaby** [comment]
Custom header support has been rolled back into the theme. I also merged in your PR @coreymcollins. Can y'all test out the custom header and new footer/social icon features?

**Comment by coreymcollins** [comment]
Tested on my local and working a-ok.  Out of the box, there is no display for the header image, social icons, or copyright text anywhere in the theme but the customizer fields themselves work fine and can be pulled in wherever they're needed.

**Comment by gregrickaby** [comment]
Do you think we should swap out the hard-coded copyright text in the footer, for a function that pulls in the stuff from the customizer?

**Comment by coreymcollins** [comment]
Definitely.  I can work on adding a PR for that this morning.

**Comment by gregrickaby** [comment]
Fixed in https://github.com/WebDevStudios/wd_s/pull/104
