### ISSUE TITLE
This last-child style on the p tag in our basic setup no longer works.

### ISSUE THREAD

**Issue by schlotterer** [WebDevStudios/wd_s#1000]
We are adding a margin bottom 0 to the last of any group of p tags, this however now conflicts with how WP handles those p tags because it wraps them in a span, meaning all WP core paragraph p tags get this style and I don't think that's intention.
wds.preset.js
line 139

`'&:last-child': {
	marginBottom: '0',
},`

**Comment by schlotterer** [comment]
I propose this instead:

in src/scss/blocks/core/_general.scss

`//----------------------------------------
// General Spacing
//----------------------------------------

.site-wrapper {
	.wp-block-group {
		> * {
			@apply px-0;
		}
		> .wp-block-paragraph:last-child p{
			@apply mb-0
		}
	}
	.wp-block-cover {
		> div[class*='inner-container'] {
			@apply p-0;
		}
	}
}
`

**Comment by kingthrillgore** [comment]
I'll check this out locally and make the correction.
