### ISSUE TITLE
remove Google Font sub-setting for latin as it is not needed

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#102]
If I'm reading Google's recommendations it seems sub-settings for Latin is not needed, as it is default: https://developers.google.com/fonts/docs/getting_started#Subsets

I'm thinking we can remove this? https://github.com/WebDevStudios/wd_s/blob/master/inc/scripts.php#L31

**Comment by gregrickaby** [comment]
This was added because it's the standard set by the WordPress Theme Review Team. It's based on this post: http://themeshaper.com/2014/08/13/how-to-add-google-fonts-to-wordpress-themes/

**Comment by colorful-tones** [comment]
Yeah, that post is from Themeshaper, which advocates for WP.com stuff. I can see how that general coding practice in that post is important to be aware of, and general good practice, but sub-setting is not even explicitly discussed in it, and still believe it is unnecessary.

**Comment by gregrickaby** [comment]
:+1: Get me a PR.

**Comment by gregrickaby** [comment]
Fixed in #119
