### ISSUE TITLE
Automated search and replace operations for 'wd_s' in theme setup

### ISSUE THREAD

**Issue by RichKenyon** [WebDevStudios/wd_s#1039]
I've developed a script that simplifies the process of performing the 'wd_s' search and replace operatio during theme setup. The script `npm run theme-setup` prompts the user for details and then utilizes the "replace-in-file" module to update the 'wd_s' strings throughout the theme files. If there is interest, I will fork the repository and create a pull request to contribute this feature.

Features:
User Interaction: The script  prompts developers for input (Company Name and Project Name).
Detailed Output: The script provides clear feedback on the modified files, allowing developers to verify the changes.
Error Handling: The script handles errors gracefully, providing meaningful error messages to assist in troubleshooting.

**Comment by schlotterer** [comment]
I just went through this process of replacing all the things as well and found it overly time consuming and error prone. I think this would be super helpful will gladly look over your work with you as you make progress. Thanks!
