### ISSUE TITLE
Group block with background color needs padding

### ISSUE THREAD

**Issue by lepittenger** [WebDevStudios/wd_s#1087]
I feel like there should be some padding if the group block has a background color

<img width="1378" alt="Screenshot 2023-09-29 at 11 44 21 AM" src="https://github.com/WebDevStudios/wd_s/assets/2576376/4dd1763f-9fe3-4810-9189-dbe7d28e380e">

**Comment by khleomix** [comment]
This will have to be manually added on a per block basis as/where needed.
