### ISSUE TITLE
Too many <h1>s on a page

### ISSUE THREAD

**Issue by lepittenger** [WebDevStudios/wd_s#1090]
I think the footer should not use an `<h1>` as it is not best a11y practice to have multiple h1s on a single page

**Comment by khleomix** [comment]
Can you give more context on this? With block themes, it is up to you to make sure that you're using the correct headings since everything is editable.

**Comment by lepittenger** [comment]
Yeah, I believe the footer is a pattern inside wd_s that uses an h1 to display the site title

**Comment by lepittenger** [comment]
I think the wp:site-title defaults to an h1 here: https://github.com/WebDevStudios/wd_s/blob/035d0656b5c4210f23620acb1034bb3ed7199e18/patterns/footer.php#L12C90-L12C103

Changing it to 
`<!-- wp:site-title {"level":0} /-->` would output it as a paragraph.
