### ISSUE TITLE
Cover block text color

### ISSUE THREAD

**Issue by lepittenger** [WebDevStudios/wd_s#1095]
On this block with a repeated background, the text color disappears 

<img width="1335" alt="Screenshot 2023-09-29 at 1 45 14 PM" src="https://github.com/WebDevStudios/wd_s/assets/2576376/100c8b51-9659-4da1-b51c-143c9e044071">

**Comment by khleomix** [comment]
This too will have to be styled on a per project basis, with wd_s as a starter theme, we'll only give default styling for the default settings. Thanks!
