### ISSUE TITLE
Center aligned button is not center

### ISSUE THREAD

**Issue by lepittenger** [WebDevStudios/wd_s#1096]
<img width="1335" alt="Screenshot 2023-09-29 at 1 57 07 PM" src="https://github.com/WebDevStudios/wd_s/assets/2576376/f3896a7d-464a-4106-a891-3c9d866f2942">

**Comment by khleomix** [comment]
With block themes, all elements that you need to have an alignment are supposed to be added inside of a group block that way they'll get the global spacings and alignments. :)
