### ISSUE TITLE
Improve documentation in /svg/readme.md to cover SVG and icoMoon usage

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#120]
I've had a few pings from team on how to use the .json file in wd_s /svg/. I've briefly started to update the [Readme](https://github.com/WebDevStudios/wd_s/blob/master/images/svg/README.md), and will get it wrapped up soon.

**Comment by colorful-tones** [comment]
~~also, lumping renaming dir to /svg-icons/~~ [created separate issue to track against](https://github.com/WebDevStudios/wd_s/issues/128).

**Comment by gregrickaby** [comment]
Fixed in https://github.com/WebDevStudios/wd_s/pull/130
