### ISSUE TITLE
Make SVG's more accessible 

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#123]
Context https://basecamp.com/1756504/projects/7221032/todos/218217200 

Will use this: http://www.sitepoint.com/tips-accessible-svg/

![image of basecamp convo](https://cldup.com/Qlgc4LOiuw.jpg)

**Comment by jazzsequence** [comment]
Can we add some parameters that can be passed to do_svg? Then title and description can (optionally) be passed into the svg and used if they exist, e.g.:

``` php

$title = __( 'My awesome icon', 'wds' );
$description = __( 'A really amazing description about my awesome icon.', 'wds' );

do_svg( $title, $description );
```

**Comment by jazzsequence** [comment]
:boom:
