### ISSUE TITLE
Remove navigation.js

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#124]
Because of our requirement to make wd_s [Section 508](http://www.section508.gov/) compliant, we've removed the `aria` markup from the primary navigation menu. `navgiation.js` was based on the `aria` markup, and is now broken.

I'm for adding a different "navicon" solution into wd_s. I feel like we do a navicon on every client project...

**Comment by pstonier** [comment]
Do you mind sharing what issues were being caused? I thought the aria markup was supposed to aid in accessibility?

**Comment by jazzsequence** [comment]
@pstonier It's related to #111
