### ISSUE TITLE
Add "ready" support

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#126]
In an effort to prevent FOUT; I have a snippet that will add the body class "ready" after all the things have downloaded, and the DOM is indeed: "ready".

**Comment by bezierer** [comment]
So does this simply add visibility: hidden to the text until the body class= 'ready'?

**Comment by gregrickaby** [comment]
Correct. You could hide something and then fade it in:

``` sass
// Hide this thing until all the assets and DOM are ready.
.foo {
  opacity: 0;
  transition: all 0.5s ease;
  visibility: hidden;

    // When everything has loaded, fade in using window-ready.js.
    body.ready & {
        opacity: 1;
        visibility: visible;
    }
}
```

**Comment by bezierer** [comment]
Awesome! I'm doing something similar on my (unfinished) site: http://juxtapose.co/2015/10/alphabetizing-css/ but also making the transition a little slower so it's not “jarring” but that may be more of a personal preference.

Great commit!

**Comment by gregrickaby** [comment]
Just added this so there is code out of the box: https://github.com/WebDevStudios/wd_s/commit/0731bd583b16c5672d70450a1ee7853d5373fdcf

**Comment by coreymcollins** [comment]
Awesome! Just had to implement a solution like this on a site which had similar classes from Typekit being added to the body tag.  Really like the solution you're using above, Cameron - the easing in is real nice.
