### ISSUE TITLE
Media Query Splitting

### ISSUE THREAD

**Issue by pstonier** [WebDevStudios/wd_s#127]
Following the guidelines from Neat, adding non-overlapping media queries as variables works well when also using omega.
https://github.com/thoughtbot/neat#how-do-i-use-omega-in-a-mobile-first-workflow

This allows me to use mixins like this

```
@mixin one-quarter {
    margin-bottom:1em;

    @include media($small-screen) {
        @include span-columns(2);
        @include omega(1n);
    }
    @include media($medium-screen) {
        @include span-columns(2);
        @include omega(2n);
    }
    @include media($large-screen) {
        @include span-columns(2);
        @include omega(4n);
    }
    @include media($xl-screen) {
        @include span-columns(3);
        @include omega(4n);
    }
}
```

More examples: https://github.com/pstonier/rapid-springs/blob/master/sass/mixins/_mixins-master.scss

Also, note that these are written for a changing grid size (small screens are 2 columns, medium screens are 4 columns, large are 8, xl are 12).
https://github.com/pstonier/rapid-springs/blob/master/sass/base/_grid-settings.scss

For broader media queries, you can still use 
`@media screen and (min-width:$first-breakpoint-value)`

**Comment by colorful-tones** [comment]
Hey @pstonier would be neat to see a Pull Request and see how you would see this being incorporated into wd_s.

I like the concept of Media Query Splitting, however for somebody that has been using [Media Query Overwriting](http://simurai.com/blog/2012/08/29/media-query-splitting/) approach for awhile it becomes a little harder to shift mindset. Pull request might help visualize the benefits.

It seems to be that there could be more potential for planning and segregating ahead with MQ Splitting, and that to me is a benefit, but to others may seem like an initial barrier to overcome. 

Looking forward to fleshing out a bit more.

**Comment by colorful-tones** [comment]
I took a stab at what I envisioned with Media Query Splitting and would be interested to hear what you think @pstonier . I just did a branch off my fork of wd_s: https://github.com/WebDevStudios/wd_s/compare/master...colorful-tones:media-query-splitting

**Comment by pstonier** [comment]
@colorful-tones it looks about right. I made a PR myself that I think would be able to be merged without breaking existing functionality.

**Comment by gregrickaby** [comment]
This was merged in with PR https://github.com/WebDevStudios/wd_s/pull/141

@pstonier Would love a write up/example so we can add it to the docs here on Github (yes, we'd like to have docs here on Github haha)

https://github.com/WebDevStudios/wd_s/wiki
