### ISSUE TITLE
empty /svg-icons/ dir to start out

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#131]
I feel like it may be more error prone to start with dozens of svg icons on new project and then have to go back and clean out unused icons later on (especially in team environment), as opposed to starting with empty directory and add as you go? I wonder if some projects never get cleaned up, therefore lots of unused icons left causing bloat?

**Comment by aubreypwd** [comment]
I agree, add as you go....

**Comment by colorful-tones** [comment]
or even just start with very little, like Facebook and Twitter only? Although, empty is probably still better.

**Comment by gregrickaby** [comment]
I vote we clean it out, leaving only FB and Twitter. It will help newbs...  :smile:

**Comment by efuller** [comment]
+1 on the idea of removing bloat! I like Greg's thinking though of starting with FB and Twitter.

**Comment by colorful-tones** [comment]
Resolved with: https://github.com/WebDevStudios/wd_s/pull/135
