### ISSUE TITLE
Detecting Media Queries w/ Javascript

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#138]
http://zerosixthree.se/detecting-media-queries-with-javascript/
A lot of Javascript (and jQuery) is written to stay synchronized with a theme's media query breakpoints. Example, make off-screen nav work only 767px and above. Therefore, I feel like detecting the theme's Sass @mixin built media queries and keeping the Javascript in sync (single-source) is important. This would make a great reusable feature to have baked into wd_s. 

What do you think?

**Comment by colorful-tones** [comment]
I forgot we've removed reliance on breakpoint @mixin, which makes this feature mostly unusable. Will have to rethink.

**Comment by gregrickaby** [comment]
Just doing some housekeeping @colorful-tones; do you want me to keep this issue open?

**Comment by gregrickaby** [comment]
Last call @colorful-tones... thoughts on leaving this open?

**Comment by colorful-tones** [comment]
The only reason I left it open, because you told me to when I asked if I should. Closing.
