### ISSUE TITLE
Grunt githooks

### ISSUE THREAD

**Issue by CamdenSegal** [WebDevStudios/wd_s#14]
We've had some issues with using grunt githooks and currently they are being used to do compilation and minnification. The earliest hook possible is 'pre-commit' which is what we are currently using, but when this runs files have already been added to the commit so any changes and additions from grunt will not be included with the commit.

I think using grunt githooks makes sense for linting and testing code but not for compiling code.

Any thoughts?

**Comment by gregrickaby** [comment]
Just doing some house cleaning, what's the status of this? I leave it to you devs... :smile:

**Comment by jtsternberg** [comment]
I think i've come around to @CamdenSegal's side.. We're all used to running grunt now.. I think it's a non-issue, and not something we need to be doing on a githook.
