### ISSUE TITLE
remove those pesky IDs again

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#142]
`<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>`
In most cases will output
`<article id="post-x" class="post-x">`
~~This is invalid markup and~~ We should not be using IDs to begin with. Greg said Stacey originally removed the IDs, and when we brought wd_s up-to-date with _s they came back. 

Somebody should go through and remove again, and soon please.

**Comment by mindctrl** [comment]
@colorful-tones for the sake of education, what exactly makes that invalid markup?

**Comment by colorful-tones** [comment]
@mindctrl thanks for asking... I updated statement above, which I hope clarifies your question.

**Comment by colorful-tones** [comment]
We [removed id="site-navigation"](https://github.com/WebDevStudios/wd_s/commit/1d4bd6f79dfa3ca44f177d406995542fdd8a725c) which is targeted by navigation.js for mobile menu. This will need to be fixed.

**Comment by colorful-tones** [comment]
I added id back for main nav as navigation.js is tied to it.
