### ISSUE TITLE
Add 'animate.css'

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#144]
Based on our new browser support and the fact that more comps require it, let's go ahead get this library added. I think @colorful-tones mentioned he found a Sass version?

Ideally, this library would be added to `bower.json` - not `/assets/sass`

https://daneden.github.io/animate.css/

**Comment by colorful-tones** [comment]
I can't remember which one I used, and didn't use Bower to install, and either of these would work:
https://github.com/tgdev/animate-sass
https://github.com/geoffgraham/animate.scss

**Comment by colorful-tones** [comment]
We probably should not be enqueing bower_components, and probably not including the whole animate.css library, and only use what we need, when need for optimal speed performance.

**Comment by gregrickaby** [comment]
This is part of a larger discussion. I've added to the weekly call agenda! Closing since we're tracking in #148
