### ISSUE TITLE
Beef up wd_s documentation

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#145]
It is way past time we document how to use wd_s. I've enabled a public wiki which can be edited by _anyone_ (not just @WebDevStudios/team-members). 

Contributions are welcome at: https://github.com/WebDevStudios/wd_s/wiki

Thanks!

**Comment by carrieforde** [comment]
@gregrickaby Would you still be amenable to adding Sassdocs? I think that could be a handy way to create documentation, and if we put it in a `/doc` folder within the theme, we could even spin up a little github.io doc site. 😄 

I'd also be interested to see if we could use PHP Doc (maybe via a Gulp task) or something similar to create a PHP counterpart.

**Comment by gregrickaby** [comment]
This was my primary focus for #5ftf today. I added a new wiki page on using [the Grid](https://github.com/WebDevStudios/wd_s/wiki/Grid), as well has went a little nuts with the [Sass Docs](https://github.com/WebDevStudios/wd_s/commit/fa2ce9b185ca0ee0a32ab77184e784b3033ed9bb).

**Comment by zachary-russell** [comment]
@gregrickaby I'd love to assist in improving the documentation. I recently started using `wd_s` on a client project (used `_s` on dozens before but wanted more), there is a metric ton of things to go through for a new dev. Should I edit wiki directly or would you want to spin up a github.io site?

**Comment by gregrickaby** [comment]
@zachary-russell Wow! Thank you for the kind words. I'm OK if you want to update the wiki directly. When you are finished, would you mind pinging me here (with links) so I can review? Thank you so much for choosing to help! 👍  😄

**Comment by coreymcollins** [comment]
Our wiki has been beefed up pretty well at this point and continues to get beefier with new updates. The team has been good about updating docs when new features are merged in, and we've adopted the policy of adding an issue to create documentation when a PR is merged in (that way, we're not rewriting documentation if requirements or functionality change over the course of a PR).

I think we can safely close this out and continue to track our documentation on a PR-by-PR/case-by-case basis.
