### ISSUE TITLE
Remove /bower_components from version control

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#146]
I would recommend we .gitignore bower_components/

**Comment by gregrickaby** [comment]
Unless you have a build server, you're not supposed to ignore `bower_components/`. 

Unlike `node_modules/`, `bower_components/` was meant to house dependencies that will be served to the end user. http://stackoverflow.com/a/22328067

**Comment by colorful-tones** [comment]
All bower_components are available as NPM packages, and are up-to-date. Wonder if we should drop using Bower, and just streamline tooling to use NPM only?

It would look something like this: 
https://github.com/colorful-tones/wd_s/blob/media-query-splitting/package.json#L40
https://github.com/colorful-tones/wd_s/blob/media-query-splitting/Gruntfile.js#L90

**Comment by gregrickaby** [comment]
We discussed this on the Designers call last week. We voted to keep using Bower because the NPM versions of both Bourbon & Neat are out-of-date.

**Comment by colorful-tones** [comment]
They can't be out of date, and are not out of date, because they're served from the same repo. The only discrepancy may be the author forgot to update the package.json version number when bumping up their project version number. 

NPM - Publishing NPM Packages - [Updating the Package](https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package)

**Comment by gregrickaby** [comment]
Believe me, nobody wants to ditch Bower (and move to NPM) more than I. (Heck, I'm using NPM to enqueue Bourbon/Neat in the [Gulp feature branch](https://github.com/WebDevStudios/wd_s/blob/feature/gulp/package.json#L33)!)

Let's talk about it again on the next call. Please add it to the agenda, and feel better!
