### ISSUE TITLE
Integrate base Gravity Form styles

### ISSUE THREAD

**Issue by efuller** [WebDevStudios/wd_s#149]
Working on the feature/gravity-forms branch.

Initial Sass file can be found [here](https://github.com/WebDevStudios/wd_s/blob/feature/gravity-forms/assets/sass/plugins/_gravity-forms.scss).

Right now I'm using some local variables to make styling the forms easier, but after bouncing a few ideas around with @colorful-tones I think it might make sense to create global form variables.

Any thoughts, ideas or suggestions would be appreciated!

Here is an initial list of items for the next designers call:
- Create/use global form variables
- Use 'placeholder' selectors for all/most GF field types

**Comment by colorful-tones** [comment]
Yeah, I think having a `_forms.scss` partial inside the `assets/sass/utilities/variables/` would totally make sense. I would even argue that I would like to see use of both local and global variables in this instance. So the global form variables are things like this in the `_forms.scss` partial...`$form-background: $color-white;` and then local variables in `_gravity-forms.scss` partial, like `$gf-form-background: $form-background;`

**Comment by gregrickaby** [comment]
Be sure to check form styles after a successful Ajax submission. This has bitten me in the past...

**Comment by colorful-tones** [comment]
Barely worth noting, and probably overkill, but we might want to think about overriding [GF helper layout classes](https://www.gravityhelp.com/css-ready-classes-for-gravity-forms/) to use Flexbox if we're going to be ALL OVER the FLEXBOX!

**Comment by efuller** [comment]
**Current Todo List:**
Feel free to add items if there is anything specific that should be addressed.
- [x] Create `_forms.scss` inside `utilities/variables` to hold global form variables
- [x] Convert `modules/_forms.scss` to use new global variables
- [x] Setup `plugins/_gravity-forms.scss` with local varaibles
- [x] Mobile Responsive
- [x] Style form after successful/unsuccessful Ajax submission
- [x] Error styles
