### ISSUE TITLE
Bring current with _s

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#156]
Please go through the list of commits to [master](https://github.com/Automattic/_s/commits/master) and add them to our repo. 

There is no fancy auto-merge-fast-forward-upstream method to do this. While we're a fork, we have different opinions/direction for certain things. Generally, I'm focused on keeping the html markup/php/js similar. We've gone in a completely different direction with CSS/Sass.

If you have questions about what should/shouldn't be merged in, let me know.

**Comment by bradp** [comment]
Here's an example of an [upstream merge](https://github.com/WebDevStudios/wd_s/pull/77).

**Comment by gregrickaby** [comment]
I knew you were going to comment, so when you did that Upstream Merge back in September, it brought back all the IDs we had removed a few months earlier. #142 

Anyway to do an upstream, without doing that again?

**Comment by bradp** [comment]
The merge has to be a manual merge, so maybe the solution is to review any large changes or discrepancies from upstream before merging.

**Comment by gregrickaby** [comment]
FYI. I brought current on March 28, 2016.

**Comment by gregrickaby** [comment]
FYI: I brought current on July 29, 2016. Commit: https://github.com/WebDevStudios/wd_s/commit/c8656a056cf37f2deb31f6d84bdd7f6c3afb7f6e

**Comment by jomurgel** [comment]
I've made a few updates here inside `theme/#156-bring-current-with-underscores` which updates some of the stock `template-tag.php` functions as well as making some additions/updates to core functionality:
- https://github.com/WebDevStudios/wd_s/commit/2b29954db3fa27507bde1da5ab2f9e402684b165
- https://github.com/WebDevStudios/wd_s/commit/c0ca41d6c55745a51984daa1797e43bbe05848d2
- https://github.com/WebDevStudios/wd_s/commit/70182c013a4ebc14da04b2a780794e8dd75b2719
- https://github.com/WebDevStudios/wd_s/commit/1bc10a6814eba684bf93b0a018658cd53cec007a
- https://github.com/WebDevStudios/wd_s/commit/93b723d9ca8ecc4e6a0231975f83d9654e3d0ca9
- https://github.com/WebDevStudios/wd_s/commit/1241735c391854f541ddf7f2ec07f3c83c4e83c3
- https://github.com/WebDevStudios/wd_s/commit/ffe4dc55e4ef74a50c339b8aba273ee6ae6bd5c8
- https://github.com/WebDevStudios/wd_s/commit/6987fd5728a2103f1e675e36d8479d1eacb87bdf

I also added a new issue #438 to maybe take a look at how we're utilizing our grid. We have a grid and presentation classes, but it does not appear to be in use at the moment in favor of ad-hoc Neat use.
