### ISSUE TITLE
Implement semantic versioning on wd_s

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#161]
Would love to see semantic versioning rolled out in wd_s: http://semver.org/

**Comment by gregrickaby** [comment]
I feel like not having versioning is part of the allure of _s. Adding versioning will introduce more overhead for those responsible for maintaining wd_s (e.g., me). Instead of just iterating and pushing, everything has to be put on a timetable and put into releases. That feels too formal.

I welcome the discussion though...

**Comment by bradp** [comment]
I agree with @gregrickaby on this one.

One of the biggest benefits of _s, and also wd_s is that you don't need to back-port any features or changes into older projects. I like the fact that there is no version number, I'm just using wd_s from when I grabbed it.

We don't need to have a timetable if we do adopt a versioning scheme, but I don't think we need a versioning scheme at all for this.

**Comment by colorful-tones** [comment]
It is only as formal as we make it, and versioning does not necessarily add that much overhead. Ultimately, it is just a number at the top of files.

At some point we _may_ want to grow to allow for more people being responsible for maintaining this project, and encourage less ownership, and more transparency and collaboration. I imagine this would be better suited for internal discussion, and just wanted to offer some food for thought.

**Comment by gregrickaby** [comment]
If it's just a "number on top of a files", then we're not really versioning. @bradp is right, versioning requires careful testing to ensure when someone upgrades - a user's theme doesn't break. It's going to take what I consider a very agile project, and slow it to a crawl. 

That's not necessarily a bad thing and it works for most software. While public, wd_s is still at its core, internal dog food. 

I want to talk to your second point privately.
