### ISSUE TITLE
Buttons in IE

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#165]
This is a recurring QA task: "Fix button padding in IE".

Let's just fix it here and be done with it! :smile:

**Comment by gregrickaby** [comment]
@colorful-tones shared this... http://jxnblk.com/formula/

@coreymcollins suggested using flexbox

**Comment by jomurgel** [comment]
Possible bug with IE and line-height if height doesn't equal line-height.  Defining min-height of buttons and vertical alignment of bottom seems to fix vertical alignment.
