### ISSUE TITLE
Add @package _s to search/replace list

### ISSUE THREAD

**Issue by krogsgard** [WebDevStudios/wd_s#166]
I'd add `@package _s` to `@package project-name` to the list of stuff to search and replace for.

**Comment by krogsgard** [comment]
I should note that I mean on the home page readme, not anywhere code-wise :)

**Comment by gregrickaby** [comment]
Hey @krogsgard... I can certainly do this, but wanted to confirm that wasn't already being handled with:
- Search for (and include the leading space): <code>&nbsp;_s</code> and replace with: <code>&nbsp;Project Name</code> (with a space before it) to capture DocBlocks

**Comment by krogsgard** [comment]
Derp, @gregrickaby I think you're right. I missed the space note there so that should probably take care of it. I skipped that step before.

**Comment by gregrickaby** [comment]
@krogsgard We're working on a Gulp generator...that way, you wont have to do any of this by hand! :smile:
