### ISSUE TITLE
Adding aria-hidden="true" in SVG markup

### ISSUE THREAD

**Issue by samikeijonen** [WebDevStudios/wd_s#168]
How do you feel about adding `aria-hidden="true"` in SVG markup? In most cases icons are kind of decorative and for accessibility reason markup could be like this:

```
<button>
<span class="screen-reader-text">Menu</span>
<svg class="icon icon-menu" aria-hidden="true">
   <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-menu"></use>
</svg>
</button>
```

I'm using almost [the same function](https://github.com/samikeijonen/some/blob/master/inc/template-tags.php#L41) than `_s_get_svg()` but added ARIA rule as one of the arguments.

**Comment by gregrickaby** [comment]
I like it! 👍  Added here: https://github.com/WebDevStudios/wd_s/commit/d5a3f1eb91344d6d49e3478afd729020bde770a6
