### ISSUE TITLE
Javascript Gulp tasks not working

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#172]
I discovered this awhile ago, and been meaning to post ticket. However, since it was awhile ago I don't have detailed explanation.

Basically, if I recall correctly there is an issue between when items are clobbered especially in relation to any file created within the /js/ folder, and doesn't necessarily affect the project.js and /concat/ setup. I think we'll probably need to look in to using gulp merge or globbing. Something like: https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-task-steps-per-folder.md

I'll drop back next #5ftf and try to get specific details as to where JS Gulp config is breaking, and just wanted to get Issue reported for now before I forget, as it came up on scrum.

We'll need to discuss ways to optimize and enqueue scripts in projects. While having project.js is a nice start on larger projects it gets littered with unnecessary stuff sometimes, whereas it might be nicer to have a front-page.js, landing-page.js, format and enqueue on pertinent templates as needed. However, then it gets tricky if a small partial, like accordion.js needs to be on front-page and landing-page, but we only want to maintain one file/set of code. Browserify might be a good solution to overcome this, but would require further team training around what we're trying to accomplish, and best practices. I still have a Gulpfile.js saved from when I had Browserify working in wd_s during initial testing for pattern library work, which may come in handy: https://gist.github.com/colorful-tones/f0b253349ce0f97cb7e3

Also, found commit where I remove Browserify and all dependencies from wd_s Pattern Library, which may be helpful, and logging here too: https://github.com/WebDevStudios/wd_s/commit/1234f7eb13f420d795624068961b94ab943ea63e

**Comment by gregrickaby** [comment]
It would seem there are two parts to this ticket. 1) You're saying "it doesn't work" 2) Optimization

**1** 
Can you provide an specific example of it "not working"? We've been using Gulp "scripts" for months, and on at least 4-5 projects, so if this is broken - we need to do triage ASAP.

**2** 
I like the idea of each page having it's own file, which would get minified and enqueued on demand.

However, multiple JS files getting concatenated together is not really any different than, say, fifty Sass partials being compiled into a single  `style.css`. There could be an argument that each page should have it's own stylesheet.

Take PuffPastry, it has 17 files being concatenated into `project.js` - which is less than 1,000 lines long unminfied and only 13kB when minified. Compared to jQuery (86kb - minified), our concatenated scripts are tiny.

Still, I'm all about optimization and would like to know more about best practices. Sounds like a good FED call topic...maybe with @CamdenSegal

**Comment by coreymcollins** [comment]
To chime here on #1 - this is what I get when I save a JS file while `gulp watch` is running:

`events.js:141`
`throw er; // Unhandled 'error' event`
`^`

`Error: ENOENT: no such file or directory, open '/Applications/MAMP/htdocs/PROJECT_NAME/wp-content/themes/THEME_NAME/assets/js/project.js'`
`at Error (native)`

Once this happens, there are no more minified JS files in the root JS directory.  It kind of looks like, from watching my root JS directory and terminal at the same time, that the project.js and project.min.js files are deleted when `gulp watch` hears an update, but then since project.js/min.js are no longer there, Gulp doesn't know where to save anything to.

Running `gulp scripts` alone works as expected.

**Comment by gregrickaby** [comment]
I'm seeing this too! I know this used to work - maybe it's a Node thing. 

**Will look into this.**

BTW: It's supposed to "clean" the compiled scripts by deleting them, and then re-compiling. That's a standard Gulp/Grunt thing.

**Comment by coreymcollins** [comment]
Yup, figured that was what it was attempting to do but missing a step somewhere between "clean" and "recompile".  That damn Gulp is Gulping too quickly and our files can't keep up!

**Comment by colorful-tones** [comment]
I didn't have #5ftf time today, therefore didn't have time to follow up on this with both more details and a full fix. Will try next chance I get.

I would say we owe it to all our client's and their users to take any necessary steps to optimize as much a possible, both Jacascript and CSS.

**Comment by aubreypwd** [comment]
It seems https://github.com/WebDevStudios/wd_s/blob/master/Gulpfile.js#L63 is the culprit of the _no such file or directory_ issue. Removing this has stopped the error. I think another function is trying to process further the `.min` files and they had not been generated yet.

**Comment by gregrickaby** [comment]
Removed "clean" for now. This was only happening in the latest version of Node. Will circle back around for a better fix.
