### ISSUE TITLE
Remove support for Page Builder if we're no longer using?

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#174]
Please verify whether we're still using Page Builder and want to have out-of-box support for it in wd_s.

https://github.com/WebDevStudios/wd_s/blob/master/inc/scripts.php#L83

Make sure there a no other references within theme if we remove.

**Comment by gregrickaby** [comment]
Sounds good to me. Make it so.

**Comment by ImBigWill** [comment]
Removed support from scripts.php and did not find any reference to it in the theme currently. 

Branch:
**feature/remove-page-builder-support**

https://www.dropbox.com/s/1db3e33cilkflr7/Screenshot%202016-07-29%2011.40.32.png?dl=0
