### ISSUE TITLE
remove animate.css enqueue

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#176]
We're [enqueue'ing animate.css](https://github.com/WebDevStudios/wd_s/blob/master/inc/scripts.php#L70) via Bower even though it is [not declared as a Bower dependency in bower.json](https://github.com/WebDevStudios/wd_s/blob/master/bower.json). I think this was our first attempt at originally integrating animate stuff in wd_s before we decided to use the animate.scss methodology: https://github.com/WebDevStudios/wd_s/tree/master/assets/sass/utilities/animate

We should remove the enqueue statement, and also add back the link to the animate.scss Readme for documentation purposes? It used to be all on the wd_s Readme, but seems to have disappeared.

**Comment by ImBigWill** [comment]
Removed animate.css enqueue from scripts.php, gulpfile.js, and the folder within assets/sass/utilities as well as the call for it in assets/sass/style.scss 

In Branch:
**feature/remove-animate-css**

**Comment by colorful-tones** [comment]
Why did we remove Animate.scss? This ticket was originally created to remove just the enqueue for animate.css as we no longer were including it via Bower, and for some reason it got left. However, the Animate.scss library is quite useful, and I wrote a whole Readme doc on how to use. Was nobody using it, therefore the team agreed to remove? Just curious. I know we agreed to add Animate.scss as a team: https://github.com/WebDevStudios/wd_s/pull/148

**Comment by bezierer** [comment]
I must have missed that one, too. I don't think I've been on a project in the last few months where we _didn't_ use animate.css in some capacity.

**Comment by gregrickaby** [comment]
I vote we add this back in via NPM or Bower. I really want to keep us away from "maintaining" third party code.

https://www.npmjs.com/package/animate.css

Then, if we need it, just use `@import animate.css`

**Comment by gregrickaby** [comment]
I've re-included `animate.css` via Bower and enqueued via `@import animate.css` If we don't use it, simply remove the @import from `style.scss`. 

Commit:
https://github.com/WebDevStudios/wd_s/commit/1042a111b5b77c3bdff67058ee4d10c639070130
