### ISSUE TITLE
Research possible SEO impact of title tags in SVG output

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/wd_s#178]
Our SVG sprite generator outputs the SVG images after the opening body tag.  This includes `<title>` tags.  We should look into the possible SEO impact, if any, of having several `<title>` tags in place at the very start of a page.

**Comment by coreymcollins** [comment]
I don't think there is any cause for concern here.  Including the `<title>` tag makes the SVG accessible the same way `alt` tags work on standard images.

[This blog post](http://thenewcode.com/1026/Making-SVG-Accessible) offers a nice and quick read on SVG accessibility

Additionally, running that site through the W3 Validator does not come back with any issues related to multiple title tags.  You can [view those results here](https://validator.w3.org/nu/?doc=http%3A%2F%2Fthenewcode.com%2F1026%2FMaking-SVG-Accessible).

So, it looks like this is a non-issue but we should:
- Make sure to include title tags with SVG output. Maybe provide fallback text using the provided icon name if no explicit title text is specified? (maybe create a new issue for this?)
- Be sure to include `role="image"` if using an SVG in a normal `img` tag

**Comment by gregrickaby** [comment]
💥
