### ISSUE TITLE
Search box clearing on click

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#179]
When you click in it clears, when you click out it replaces with placeholder text

**Comment by benjaminmueller** [comment]
When the search field is focused on (clicked on or tabbed into...) the placeholder text is removed and is assigned to the `.data()` method to be used for later.

When the search field looses focus then the placeholder text is added back in by grabbing the text from the data attribute that we assigned the value to beforehand. This has been tested with multiple search fields on the page to ensure there are no scoping issues.

Not Focused:
![screen shot 2016-07-29 at 11 16 55 am](https://cloud.githubusercontent.com/assets/2722581/17259462/73d05fe4-5580-11e6-8f11-f7f75e9038ff.png)

Focused:
![screen shot 2016-07-29 at 11 17 02 am](https://cloud.githubusercontent.com/assets/2722581/17259463/73d25c4a-5580-11e6-9764-447710f97496.png)
