### ISSUE TITLE
Replace "..." with "Read More"

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#180]
On the excerpt replace the dots with Read More

**Comment by allisonplus** [comment]
**Branch:** [feature/read-more](https://github.com/WebDevStudios/wd_s/tree/feature/read-more)

Added:
`_s_modify_read_more_link()` which affects manual insertion of "Continue Reading"

![screen shot 2016-07-29-inline-read-more-after](https://cloud.githubusercontent.com/assets/10225971/17258056/678cc2e8-5582-11e6-9981-75b35915d30c.png)

`_s_excerpt_more( $more )`which can be used to alter the text &/or add a link to the post in question for `_s_get_the_excerpt`

![screen shot 2016-07-29-excerpt-link-option](https://cloud.githubusercontent.com/assets/10225971/17258055/6789e58c-5582-11e6-815f-9ff1e71e6b76.png)
