### ISSUE TITLE
Adjust comment boxes for logged out users

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#181]

**Comment by ImBigWill** [comment]
Adjusted comment boxes slightly for logged out users to look a little less clunky out of the box for mobile and desktop.

Branch:
**feature/comment-box-fields-logged-out**

Some Before Screenshots:

https://www.dropbox.com/s/6d4ddp69eibdjl8/Screenshot%202016-07-29%2012.32.04.png?dl=0

https://www.dropbox.com/s/3sibx2bmb1mg642/Screenshot%202016-07-29%2012.32.19.png?dl=0
