### ISSUE TITLE
Better nested comments for mobile

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#182]
When you get past 5 levels deep, comment nesting is pretty rough on mobile.

This is for default WP comments.

**Comment by allisonplus** [comment]
**Branch:** [feature/nested-comments](https://github.com/WebDevStudios/wd_s/tree/feature/nested-comments)

Added base styling for default WP nested comments, specifically to make them a little less cumbersome on mobile.

_Previously appeared as:_

![screen shot 2016-07-29-mobile-previously](https://cloud.githubusercontent.com/assets/10225971/17260551/524ad3aa-558e-11e6-825d-7bee31880ed1.png)

_With changes:_

![screen shot 2016-07-29-with-changes1](https://cloud.githubusercontent.com/assets/10225971/17260955/912e57de-5590-11e6-8464-7c7b20f5389f.png)
![screen shot 2016-07-29-with-changes2](https://cloud.githubusercontent.com/assets/10225971/17260956/918bf056-5590-11e6-964c-213670c31f66.png)
