### ISSUE TITLE
Remove hand icon from buttons

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#183]

**Comment by coreymcollins** [comment]
This has been updated in the [feature/button-hover-cursor branch](https://github.com/WebDevStudios/wd_s/tree/feature/button-hover-cursor)

Buttons should use the default cursor and not the pointer/hand cursor when hovered.

Previous:
![wd_s-button-hover-old](https://cloud.githubusercontent.com/assets/954724/17255132/de7b5394-5585-11e6-8901-26c5cf291478.gif)

Updated:
![wd_s-button-hover-new](https://cloud.githubusercontent.com/assets/954724/17255139/e68f0030-5585-11e6-804c-9f5b5cbfbe1f.gif)
