### ISSUE TITLE
Basic table styles

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#184]
Try to make them more responsive too.

**Comment by jomurgel** [comment]
I think we're all set.  Basic table styles with a responsive treatment on > 640 rems screens.

![screenshot 2016-07-29 10 16 15](https://cloud.githubusercontent.com/assets/5230729/17257143/8a9862ea-5575-11e6-806d-dac6ee3b7f5a.png)

![screenshot 2016-07-29 10 17 26](https://cloud.githubusercontent.com/assets/5230729/17257166/ab94905e-5575-11e6-8b0f-0543ba83a502.png)
