### ISSUE TITLE
Misc. clean ups 

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#186]
There are a few areas where items are misspelled and missing a space. Also need to update the JS in /concat from "that" to "app". Could also update comments to our new comment standardization.

**Comment by ImBigWill** [comment]
Added comments for a number of the partials with some help at the end from Allison. May have missed one or two things because it's a lot, but this is in a pretty good spot.

feature/comment-partials-update

**Comment by allisonplus** [comment]
**Branch:** [feature/comments-partial-remaining](https://github.com/WebDevStudios/wd_s/tree/feature/comment-partials-remaining)

Updated remaining partials (`_jetpack`, `_layout`, `_widget`) and fixed a few typos.
