### ISSUE TITLE
Add manual control

### ISSUE THREAD

**Issue by pmgarman** [WebDevStudios/wd_s#19]
If we include jetpack we should maybe include manual control for it as well.

**Comment by gregrickaby** [comment]
Agreed, but don't see a Github repo for it...

**Comment by pmgarman** [comment]
Yeah I poked @markjaquith on Twitter about it before, and that got a blank repo made but no code to it yet.

https://github.com/markjaquith/manual-control

**Comment by gregrickaby** [comment]
Poke @markjaquith some more!! :smile:

**Comment by jtsternberg** [comment]
Poke 'em. :point_right:

**Comment by pmgarman** [comment]
Maybe we just add the one line of code by ourselves without the plugin :)

`add_filter( 'jetpack_get_default_modules', '__return_empty_array', 99 );`

**Comment by jtsternberg** [comment]
deal.

**Comment by pmgarman** [comment]
@jtsternberg doesn't make sense to do that as a whole "plugin" ... Is it "clean enough" of a solution to store one liners like that in the mu-plugin file that does the auto loading?

**Comment by jtsternberg** [comment]
I wouldn't put it in here: https://github.com/WebDevStudios/wd_s/blob/master/mu-plugins/wds-mu-plugins-include.php
if that's what you mean.

Let's put it in the (now-missing) mu-plugin folder, `wds-mu-plugins` as it's own file, `jetpack-manual-control.php`. 

https://github.com/WebDevStudios/wd_s/tree/master/mu-plugins

**Comment by pmgarman** [comment]
Is the wds-mu-plugins folder going to be a submodule as well, or straight part of the repo?

**Comment by jtsternberg** [comment]
No, not a submodule.

**Comment by pmgarman** [comment]
`wds-mu-plugins` ... not sure that name "fits" as well, all the plugins there are "WDS MU Plugins"

Is the folder just going to be for little "quick patch" type fixes like this? Maybe `wds-mu-patches` or something. Open to ideas but just seems like we could find a more suited name?

**Comment by gregrickaby** [comment]
Hi. There is a jetpack file for our theme...we can put it there.

https://github.com/WebDevStudios/_s/blob/master/inc/jetpack.php

**Comment by jtsternberg** [comment]
That's a good spot for it @gregrickaby. @pmgarman wds-mu-plugins is meant to be for anything that should always load on the site, and may have translatable strings. I'm not sure it's worth arguing the semantics, so if you feel the name needs to change, you have my blessing.

**Comment by pmgarman** [comment]
I just wanted to get your opinion about the name, don't think its worth arguing and barely worth a discussion a discussion :D Was just going to put everything together and submit a PR for that too and wanted to do it once the way you wanted it :)

**Comment by jtsternberg** [comment]
Gotcha. my one and only thought is that wds-mu-plugins is intended to replace the use of mu-plugins, hence the name-mirroring. Patches are plugins, plugins are patches, so semantically, having it mirror the name has a bit more value in that it conveys it's purpose a bit better... maybe. ha!

**Comment by gregrickaby** [comment]
It's in! Thanks for the discussion.

https://github.com/WebDevStudios/_s/blob/master/inc/jetpack.php#L25
