### ISSUE TITLE
Rethink "editor-style.css"

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#195]
Now that WP has dropped support for Open Sans, we need to also drop it from `editor-styles.css`. 

This file could probably go away all together, since it makes assumptions on how the user's content should appear in the editor. Definitely worth a conversation...

https://github.com/WebDevStudios/wd_s/blob/master/editor-style.css

**Comment by xBLADEx** [comment]
Removed the style and enqueue.
