### ISSUE TITLE
Add Babel to gulp scripts build process

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#205]
We'd like to start writing/using ES6 stuff... will need to add Babel to transform.

**Comment by colorful-tones** [comment]
I'm still trying to solidify my ES5 training. Therefore, I'm genuinely intrigued to hear more on how we see ES6 and Babel will advance our WordPress-specific infrastructure and tooling? 

I would be curious to hear more of the team's thoughts and how comfortable they are with ES5 vs ES6. I'm all about learning the shiny and new stuff, but want to make sure I'm solid on the current standard.
