### ISSUE TITLE
Bring back over Aria/a11y tweaks used in TwentySeventeen's SVG workflow

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#207]
As some of you know, _TwentySeventeen_ (the new default theme shipping with WordPress 4.7) is using our SVG workflow. @samikeijonen is an a11y expert in his own right, and improved on the workflow. I'd like to bring these improvements back into wd_s.

See it here:
https://github.com/WordPress/twentyseventeen/pull/253

**Comment by samikeijonen** [comment]
I have additional thoughts in here:
https://github.com/WordPress/twentyseventeen/issues/394

The last example is what `a11y` team thinks is the best approach for title/desc. But it's not needed in Twenty17 because all icons are decorative and always have `aria-hidden="true"`.

**Comment by samikeijonen** [comment]
And we probably don't even need [argument for setting aria-hidden="true"](https://github.com/WordPress/twentyseventeen/blob/master/inc/icon-functions.php#L52).

It could be default and set it to null when title and desc are set. Something like this.

```
    // Set aria hidden.
    $aria_hidden =  ' aria-hidden="true"';

    // Set ARIA.
    $aria_labelledby = '';
    if ( $args['title'] && $args['desc'] ) {
        $aria_labelledby = ' aria-labelledby="title-ID desc-ID"';
        $aria_hidden =  '';
    }
```

**Comment by samikeijonen** [comment]
References:

https://www.paciellogroup.com/blog/2013/12/using-aria-enhance-svg-accessibility/

https://css-tricks.com/accessible-svgs/
