### ISSUE TITLE
Run through PHPCS and fix 

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#214]
PHPCS (WordPress) has found quite a few issues with our PHP in `template-tags.php`. Let's fix it up!

**Comment by JayWood** [comment]
Might want to look over `wd_s/inc/customizer.php` as well, looks like we're using spaces instead of tabs in some locations. @ImBigWill

**Comment by jomurgel** [comment]
#218 Addressed several lint issues within the template-tags.php file.

**Comment by coreymcollins** [comment]
#219 PHPCS Cleanup of Theme (minus template-tags.php)

**Comment by gregrickaby** [comment]
Merged.
