### ISSUE TITLE
Add pattern library

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#215]
Currently discussing internally adding a simple pattern library to help during builds. 

So far, we have been creating a regular ol page in WordPress, and then assigning it the `template-patterns.php` page template.

`template-patterns.php` houses a lot of hard-coded markup. We're looking to optimize and standardize this process.

**Comment by gregrickaby** [comment]
Update: I've created repo for extending our CodePen components and patterns: 
https://github.com/WebDevStudios/WDS-Components-Library

@carrieforde Is heading up that project. The idea is to create a place where we can store ready-to-use components and patterns that will work with wd_s.

**Comment by carrieforde** [comment]
I believe we should still be using a pattern library within wd_s regardless of the existence of the WDS Components Library. A pattern library and component library serve different purposes, and ideally, they work in tandem.

The Component Library is (will be) simply a collection of ready-to-use UI components that will have basic styling and functionality that serves as a jumping off point.

The Pattern Library, on the other hand, allows us to take components and theme them specifically to the project on which we are working. Not only that, but a Pattern Library serves as visual documentation for designers, developers, and even clients and PMs. If a dev needs to reuse a component that exists on a project, they can simply refer to the pattern library for usage information. This becomes really helpful when a project ends up having several card variations, for example.

So to clarify, the point of the wd_s pattern library is not to house a collection of ready-to-use components, but to serve as a spring board for front-end development. It helps ensure that we have styled the smallest details (atoms such as typography, radio buttons, etc.), and serves as visual, theme-specific documentation for our components. (PatternLab)[http://demo.patternlab.io/] has some really basic, but great examples of this.
