### ISSUE TITLE
Run through Sass Linter and fix

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#216]
@colorful-tones was able to tone down the Sass linter and really dial it in to meet WDS standards. Please run the Sass through the linter and fix any issues.

**Comment by xBLADEx** [comment]
**Branch**
https://github.com/WebDevStudios/wd_s/tree/qa/scss-linting
**Files**
https://github.com/WebDevStudios/wd_s/compare/qa/scss-linting
