### ISSUE TITLE
Stop targeting elements out-of-box, and target via module classes instead

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/wd_s#220]
`sass/base/_elements.scss`Partial as it exists in wd_s: https://github.com/WebDevStudios/wd_s/blob/master/assets/sass/base/_elements.scss

I believe it best to not target things like `<ul>`, `<ol>` out of the box as the specificity is too low, and should be compartmentalized to something like: 
```
// Using WP's TwentySomething standard core classes for naming as an example
.entry-content {
    ul {}

    ol {}

    p {}

    img {}
} // .entry-content
```

I believe this whole partial is something residual from _s, and not all that great to inherit, and might be worth the time to revisit.

Some further reasoning...

- Here is an article that explains some simple rules for specificity and keeping class targeting to be module specific: https://github.com/jareware/css-architecture/blob/master/README.md#1-always-prefer-classes
- Also, I think we've all encountered having to override stuff in this partial on past project, and it is usually tricky.

The easiest solution would be to actually nest all of that partial inside of `.entry-content`. Thoughts?

**Comment by colorful-tones** [comment]
This actually relates heavily to the [`sass/base/_media.scss`](https://github.com/WebDevStudios/wd_s/blob/master/assets/sass/base/_media.scss) partial as well.

**Comment by colorful-tones** [comment]
AND [`sass/base/_typography.scss`](https://github.com/WebDevStudios/wd_s/blob/master/assets/sass/base/_typography.scss) too! haha. Actually, probably more so in this partial than other three.

**Comment by colorful-tones** [comment]
With this change I would imagine and suggest we streamline most of the stuff in to a new `sass/modules/_entry-content.scss` probably.

**Comment by colorful-tones** [comment]
Also, part of the reasoning this issue was created and kept coming up for me was I've found myself writing the following same CSS on last 6 projects:

```
.entry-content {

    > *:last-child {
        margin: 0;
    }

}
```

While I can't say with 100% certainty that I would not have to write that CSS anymore I would have a nice partial to put it in along with all the other stuff :-D

**Comment by gregrickaby** [comment]
AFAIK, all of this came from Automattic's _s. I see no reason to continue to target HTML elements, so if the group is OK, we can probably tackle this next #5ftf

**Comment by coreymcollins** [comment]
Going to close this as it's 2 years old and hasn't really come up as a problem in that time.
