### ISSUE TITLE
Reorganize template-tags.php

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#222]
There are three helper functions that could be moved to `extras.php`, such as:

`_s_categorized_blog()`
`_s_category_transient_flusher()`
`_s_get_attachment_id_from_url()`

**Comment by allisonplus** [comment]
_Branch:_ https://github.com/WebDevStudios/wd_s/tree/theme/template-to-extras

Moved the following from `template-tags.php` to `extras.php`:
- `_s_categorized_blog()`
- `_s_category_transient_flusher()`
- `_s_get_attachment_id_from_url()`
