### ISSUE TITLE
The Customizer preview does not reload changes asynchronously

### ISSUE THREAD

**Issue by KostasNi** [WebDevStudios/wd_s#224]
In customizer.php, customizer.js is enqueued to enable asynchronous reloads of the customizer when things such as the Title and site description change. 

However customizer.js doesn't load because the url in the enqueue is incorrect. It should be /assets/**scripts**/customizer.js instead of /assets/**js**/customizer.js 

See commit 590bbed, where the scripts folder was renamed.

**Comment by gregrickaby** [comment]
Merged PR here: https://github.com/WebDevStudios/wd_s/commit/8186aa6ca1433b189531a8b97a73ca4c0afc5c4e
