### ISSUE TITLE
Responsive Breakpoints

### ISSUE THREAD

**Issue by xBLADEx** [WebDevStudios/wd_s#229]
Lets revisit breakpoints and see if there are better widths to use.
This article has some good points, but doesn't mean we should use those exactly.
https://medium.freecodecamp.com/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862#.ikxje0vkl

I will continue to research latest breakpoints and update here.

**Comment by gregrickaby** [comment]
Agreed that we might want to refresh. Our Project Plan doesn't get specific, and just says we will center/stack for Mobile and Tablet.

Let's start with finding out what those resolutions are.

**Comment by gregrickaby** [comment]
@xBLADEx Can you provide an updated list of breakpoints?

**Comment by gregrickaby** [comment]
@BLADEx 🏓

**Comment by gregrickaby** [comment]
@xBLADEx 🏓  ... last call

**Comment by xBLADEx** [comment]
@gregrickaby Sorry for the delay. I have been using these breakpoints in other projects and found them to work nicely:
```
@mixin tablet-up {
	@media (min-width: rem(600)) { @content; }
}

@mixin tablet-only {
	@media (min-width: rem(600)) and (max-width: rem(899)) { @content; }
}

@mixin laptop-up {
	@media (min-width: rem(900)) { @content; }
}

@mixin laptop-only {
	@media (min-width: rem(900)) and (max-width: rem(1199)) { @content; }
}

@mixin desktop-up {
	@media (min-width: rem(1200)) { @content; }
}

@mixin desktop-only {
	@media (min-width: rem(1200)) and (max-width: rem(1799)) { @content; }
}

@mixin desktop-large-up {
	@media (min-width: rem(1800)) { @content; }
}
```

**Comment by carrieforde** [comment]
To chime in, since Rich proposed these ages ago, I've been using them in personal projects, and have been finding them to work for 95 percent of my use cases. I'd definitely feel comfortable considering the switch to these breakpoints, especially since I believe they better align with the _add a breakpoint when things look like garbage_ approach. 😄

**Comment by gregrickaby** [comment]
Great. I'm rolling this into our Utilities Clean Up milestone.

**Comment by jomurgel** [comment]
Implemented the above-suggested breakpoints.  Utilized the Neat 2.0 structure (min-width only) and changed the naming convention to `$tablet-up` or `$desktop-up` to imply a `min-width` media query.

New suggested conventions: `$desktop-large-up`, `$desktop-up`, `$tablet-landscape-up`, `$wp-admin-bar`, `$tablet-portrait-up`, `$phone-up`

PR: #307
