### ISSUE TITLE
.eslintrc doesn't fully match WP Code standards

### ISSUE THREAD

**Issue by Cheffheid** [WebDevStudios/wd_s#230]
The WordPress config that's extended will, eventually, add missing rulesets as per their roadmap (See here: https://github.com/ntwb/eslint-config-wordpress/issues/8).

In the mean time, it'll be worth while to add the rules slated for V2.0.0 manually, since those will also look at coding style errors like spaces inside of parenthesis, mixed spaces/tabs, etc.

**Comment by gregrickaby** [comment]
While we're at it, `.eslintrc` has been deprecated. Let's rename to either `.eslintrc.js` or `.eslintrc.yml`.

http://eslint.org/docs/user-guide/configuring#configuration-file-formats
