### ISSUE TITLE
Build production task

### ISSUE THREAD

**Issue by devctor** [WebDevStudios/wd_s#235]
Hola amigos! great work!

There is a build task for production? i know some of the tasks generates minified assets for example, sorry if i missing something.

Thank You.

**Comment by gregrickaby** [comment]
@Acrata Just type `gulp`... this will re-compile (and minify) everything.

There isn't a specific `gulp build` command. See the full list of `gulp` tasks here: https://github.com/WebDevStudios/wd_s#gulp-tasks
