### ISSUE TITLE
Add acf-json directory

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#237]
Now that we're using ACF Pro on more and more projects, let's get the JSON sync folder added.

Add `acf-json` tothe theme's root directory

https://www.advancedcustomfields.com/resources/synchronized-json/

**Comment by allisonplus** [comment]
Branch: [theme/acf-json](https://github.com/WebDevStudios/wd_s/tree/theme/acf-json)

Added acf-json folder (with index.php within it as per Security instructions [here](https://www.advancedcustomfields.com/resources/local-json/))
