### ISSUE TITLE
Neat v2.0 is here...

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#244]
... and with it comes breaking changes with brand new mixins and a different way of dealing with grids. Let's discuss which direction we want to take (keep using Neat? Something else perhaps?)

http://neat.bourbon.io/

**Comment by gregrickaby** [comment]
@carrieforde @jomurgel I'm on #5ftf today, and would love to start getting your mixins and updates around Neat 2.0 into wd_s...

**Comment by jomurgel** [comment]
@gregrickaby feel free to modify or update these however you see fit 👍  https://gist.github.com/jomurgel/25a9f993c342491a269da60612ef2018
