### ISSUE TITLE
Update units and measurements

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#248]
Based on internal discussions and these related tickets: https://github.com/WebDevStudios/wd_s/issues/243,  https://github.com/WebDevStudios/wd_s/issues/244 respectively... 

Our plan is to bring in some new mixins, courtesy of @jomurgel, for legacy purposes https://github.com/WebDevStudios/wd_s/issues/244#issuecomment-285680547, and adopt a new standard for units: 

- px - border, shadow
- em - font-size, media query, letter spacing
- rem - sizing, spacing
- % - columns, layout, grid

With this change, we will also need to update the ruleset [.sass-lint.yml](https://github.com/WebDevStudios/wd_s/blob/master/.sass-lint.yml) to match the new standard.

Go through all sass partials and update units and measurements based on the list above.

**Comment by allisonplus** [comment]
Branch: [qa/lint-file](https://github.com/WebDevStudios/wd_s/tree/qa/lint-file)

Mixins from Jo are included currently.
[.sass-lint.yml](https://github.com/WebDevStudios/wd_s/blob/master/.sass-lint.yml) file has been updated (Issue #258)

The one part I wasn't sure how we wanted to transition through was if anything should be adjusted in re: the last bullet point above (% - columns, layout, grid). For instance: if [_grid-settings.scss](https://github.com/WebDevStudios/wd_s/blob/master/assets/sass/utilities/variables/_grid-settings.scss)) requires adjusting or if those should remain in `em`s.

**Comment by gregrickaby** [comment]
@allisonplus Can you merge in master, (there will be conflicts), and re-submit as a PR, please? Thank you!

**Comment by gregrickaby** [comment]
Merged in #265
