### ISSUE TITLE
Convert grid system from Neat v1 to Neat v2

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#249]
We've decided internally (https://github.com/WebDevStudios/wd_s/issues/244) to stick with Neat and convert our grid system to the new v2.0 architecture.

Please go through and update sass partials.

**Comment by carrieforde** [comment]
_If_ my upcoming Pattern Library PR gets merged, this will be address in that PR.

**Comment by gregrickaby** [comment]
Neat v2.0 was merged in #255
