### ISSUE TITLE
Bring Back The Hamburger Nav

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#250]
Yes. I said it. 

Since we merged in https://github.com/WebDevStudios/wd_s/pull/150 last February, only _two_ of the thirteen (2-13) projects (I've been on) have used the Tap Bar. One of them was _WDS8_, and the other? Well, the client just asked us to swap it out for the Hamburger nav. :( 

It's ultimately the client's choice - and _clients are choosing two buns with some meat_.

I propose we bring it back, but make it better than it was. I really like the animation on this one: http://codepen.io/taniarascia/details/dYvvYv

Thoughts?

**Comment by bezierer** [comment]
Dropping a note that @jomurgel did a similar animation for https://www.thesportsgeek.com/ which turned out really nice. I'm in favor of this change and we can always add the tap bar in on a project-basis if it's warranted, too.

**Comment by carrieforde** [comment]
Maybe we can drop the ol' tapbar navigation into [WDS Components](https://github.com/WebDevStudios/WDS-Components-Library) so we have it to hand when we need it?

**Comment by gregrickaby** [comment]
This morning our fireteam discussed doing a push drawer similar to this: https://tympanus.net/Development/SidebarTransitions/  (click "Push")

We'd keep the registered mobile menu, hook it into the footer, and just show the drawer on mobile when a user taps the 'ol hamburger nav.

This seems to be what clients want these days. Thoughts?

**Comment by gregrickaby** [comment]
I'm officially calling the ol tapbar dead 💀 . It was included in WDS8, and then it was squashed by Brad in favor of the off canvas drawer + 🍔 . So that brings the tally down to 0-13.

I'm going to work on getting an off canvas drawer with hamburger style nav brought back.
