### ISSUE TITLE
Clean up Output Buffers and use the new `display` nomenclature

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#251]
Calling @kellenmace! Would love your assistance (well, anyone's assistance would be great) in going through our template tags and such, and getting this up to spec with this: 
 http://make.wdslab.com/2017/03/09/output-buffers-make-doc-updated/

**Comment by kellenmace** [comment]
Yo @gregrickaby - I had a chance to make these changes in this pull request, plus a few lil' changes to the template tags functions that display/get the URL of the featured/attached/placeholder image for the current post. Can you please take a look when you have a chance? Thanks. https://github.com/WebDevStudios/wd_s/pull/262
