### ISSUE TITLE
Review & update utilities

### ISSUE THREAD

**Issue by carrieforde** [WebDevStudios/wd_s#268]
With the transition to Bourbon 5.0 and Neat 2.0.0, I think it may be a good idea to revisit our variables and mixins to ensure we have the mixins we need to keep development efficient.

I'd also like to propose a few new mixins:
- One I'd love to see is a mixin that we can use to efficiently create grid classes (as we've been discussing)
- Maybe another for quickly creating color classes
- Helpers for using other _types_ of media queries (not just min-width)
- More?

I also want to make sure all the variables we need are in place for Neat setup to go as smoothly as possible.

**Comment by carrieforde** [comment]
I spent about an hour and a half working through the above on https://github.com/WebDevStudios/wd_s/tree/feature/utilities-updates.

I've moved the units of measure to a newly created functions folder, and imported the index file within the directory before importing our variables and mixins. This allows us to use these new units correctly with the media queries.

I've also added a few new mixins, including a few of the above.

**Comment by gregrickaby** [comment]
Because this sparked a larger discussion, which started a [Milestone](https://github.com/WebDevStudios/wd_s/milestone/1), which contains a bunch of new tasks related to this discussion, I'm inclined to close this ticket.

Thoughts @carrieforde ?

**Comment by carrieforde** [comment]
Yup, I'm cool with that. Thanks for adding a milestone for this. 👍
