### ISSUE TITLE
Create mixin to create grid classes

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#269]
So we can use _simple_ presentational markup like,` .col-1`, `.col-2`, etc...

See this example for a look at the `.col-1` in use: https://codepen.io/webdevstudios/full/zwywyV

**Comment by allisonplus** [comment]
I created a CodePen that might be able to be used as a jumping off point conceptually or with some add-ons: https://codepen.io/allisonplus/pen/bRdgqK

Still getting the hang of Neat 2.0 so I'm sure some tidying + fine-tuning can still occur.

**Comment by carrieforde** [comment]
I'm just catching-up / reacquainting myself with all the things in the bourbon/neat milestone, and it looks like we may already have a working solution for this on the feature/utilities-updates branch, which is pretty consistent with the exploration @allisonplus did. 😄 

We now have:

```sass

@mixin grid-classes($context: $neat-grid) {

	$columns: map-get($context, columns);

	@for $i from 1 through $columns {

		&-#{$i} {
			@include grid-column($i, $context);
		}
	}
}
```

which we're calling in `structure/_grids.scss` to create a basic 12-column grid (the default $neat-rid is set up within `utilities/_grid-settings.scss`:

```sass
//-----------------------------------------
// Basic 12-column grid using $neat-grid()
//-----------------------------------------
@include grid-media($tablet-portrait) {

	.col {
		@include grid-classes;
	}
}
```

I'd still love to fix up the Sassdoc comments (and get Sassdoc setup & working) before closing this completely.

**Comment by carrieforde** [comment]
This should be all set with Sassdocs:

![Grid classes Sassdoc](https://www.dropbox.com/s/l6j6fkpjsls1k76/Screenshot%202017-06-30%2012.00.59.png?dl=1)
