### ISSUE TITLE
Create media query helper mixin

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#271]
Neat 2.0 requires that type out the entire CSS3 media query string. Create a mixin which will allow us to do things via shorthand.

**Comment by carrieforde** [comment]
Again, catching up on issues for each milestone to recenter myself and figure out where we left off. :)

I think the original problem I was trying to solve is that Neat 2.0.0's update now _only_ works with `min-width` media queries. Which for 98% of our needs at WDS is fine. But for that other 2%, we may want to either create a `max-width` query (which we used to be able to do with the `mediamax` variable in previous Neat versions), or a between-type query (`min-width: 600px and max-width: 900px`, for example).

So the ideal, in my mind, is to create a new media mixin that gives us the flexibility to pass a min, max, or both, and it looks like a working solution may already be in place on the [`feature/utilities-updates`](https://github.com/WebDevStudios/wd_s/tree/feature/utilities-updates) branch:

```sass
@mixin media($min, $max) {

	// If the user passes a grid Sass map, set the variable to the media's value.
	@if type-of($min) == 'map' {
		$min: map-get($min, media);
	}
	@if type-of($max) == 'map' {
		$max: map-get($max, media);
	}

	// Create the media query.
	@if $min == null {
		@media only screen and (max-width: $max) {
			@content;
		}
	} @else if $max == null {
		@media only screen and (min-width: $min) {
			@content;
		}
	} @else {
		@media only screen and (min-width: $min) and (max-width: $max) {
			@content;
		}
	}
}
```

This still needs better Sassdoc documentation, and any other thoughts on this are welcome. 😄

**Comment by carrieforde** [comment]
This should be all set with Sassdocs:

![Media mixin Sassdoc](https://www.dropbox.com/s/0xhlq3bp0jvfkvt/Screenshot%202017-06-30%2011.55.11.png?dl=1)
