### ISSUE TITLE
Level up our modals

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#274]
Calling @efuller! Making this an official task for you 😄 !

Please bring your awesome modal work into wd_s

**Comment by efuller** [comment]
Let's breath some life into this issue!

I think as a first step, I can refactor our current code into a constructor function or a class. I'm hesitant to use a class, but there really is no reason not to!

A good point of reference could be here: https://codepen.io/efuller/pen/YNaWzV

**Comment by efuller** [comment]
Performed more discovery on this today and I also got a simple local dev environment setup which should allow for faster development.

On FED scrum, I asked for some modal requirements and here's what we got so far:

### Requirements
- [x] Multiple on the same page.
- [x] Play video again once stopped
- [x] Videos stop when you close the modal
- [ ] Accessibility
    - [x] Escape to close
    - [ ] Tab index on forms
    - [x] Trap focus inside modal
- [x] Click outside of modal to close
- [x] Responsive
- [x] Make sure our fluid embed wrapper is in place!
- [ ] Create modals from an existing post/page?
- [ ] Pass in a post/page ID and pull in the title and content automatically in the modal?

**Comment by Cheffheid** [comment]
I had put this in the doc already, but let me drop this here too:

Preferably “trap” focus inside of the modal (ie. only allow the modal content and close button to get focus while the modal is open) and shift focus back to the trigger when it is closed.

Here's a video to illustrate:
https://www.youtube.com/watch?v=9FH08KhZNF8

**Comment by efuller** [comment]
Quick update here. Today I worked on researching and thinking of a good approach for trapping focus inside the modal.

I think I have a way forward and can make this work!

**Comment by efuller** [comment]
Today I committed code that gets an initial setup of modal keyboard trapping in place. This will need to be testing and tweak as needed.

I also started getting getting dynamic modals put into place.

The idea behind this is that you can specify any element as a trigger and any element as the modal content and things will just work. There would be no need to have markup around the content element... just use CSS to hide it.

Then when you click the trigger, everything is dynamically created.

Here is an example. I've randomly selected the `<h3>` as the trigger and set the comments form as the modal content.

![](https://d.pr/free/i/pMwiEN+)

I'm at the stage of having something in place, but refactoring will surely need to take place as well as thought around the overall API.

**Comment by coreymcollins** [comment]
This has been hanging out for about a year at this point. @efuller is this something you're still interested in tackling?

If so, perhaps we can get a PR going with the work you had previously completed? There may be things to revisit and improve on at this point since this is an older issue.

**Comment by efuller** [comment]
@coreymcollins I've been meaning to pop in here. I spoke with Greg recently and we closed out the branch, so I think we can table this issue for now. I think there are higher priority things to work on atm.
