### ISSUE TITLE
Switch to Foundation

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#279]
I'm thrilled to announce that WDS is going drop Bourbon/Neat and marry wd_s with [Foundation](http://foundation.zurb.com/sites) by Zurb. 😮 

# Why
It's simple: _let the Foundation community worry about maintaining components and its documentation, so WDS can focus on building premium websites for our clients_. 

**To be clear**: we are not abandoning our CodePens, our commitment (and quite frankly passion) for accessibility, or internal standards. We can use our time more wisely though, by building better client websites instead of maintaining an internal framework of components, modals, documentation, accessibility best practices standards, etc... this is why we all use WordPress right? DRY.

# How does that look?

First, our designers @bezierer and @jomurgel are both familiar with Foundation; and can use their knowledge and experience - as well as the [documentation](http://foundation.zurb.com/sites/docs/kitchen-sink.html#button) and [playground](http://zurb.com/playground) as a baseline, for how they place components into comps. This will (hopefully) make starting a new design a little easier.

Secondly, the Foundation docs contain the markup for these components. If Jo places a carousel into a page? A front-end dev can just  grab the markup, and be 75% finished. No more guess work on how to structure the markup, or write the Sass. It's already been done! Also, this eliminates the need for us to maintain our own set of components and (current lack of) documentation.

Obliviously, the client dictate the design, so I'm confident WDS isn't going to be cranking out the [same looking](http://adventurega.me/bootstrap/) site month after month.

Finally, WDS is going to adopt a more "BEM" approach to how we write our Sass. We haven't landed on one single methodology yet. We're going to do some more research into BEM, RSCSS, SMACSS, and OOCSS, and figure out which one works best for us.

# A few exciting features:

- Foundation has both thriving and mature [community](https://github.com/zurb/foundation-sites) with nearly 1,000 contributors and over 25,000 stargazers
- Accessibility focused (fully Section 508 compliant, just like wd_s)
- The entire framework is only 60kb of CSS and 80kb of JS (you can even turn off components)
- Outstanding [documentation](http://foundation.zurb.com/sites/docs/) 
- [Committed](http://zurb.com/article/1468/foundation-css-grid-think-beyond-the-page) to  CSS Grid
- Is not Bootstrap :smirk:
- [and more](http://foundation.zurb.com/sites).

# The Plan
I've started [a document](https://docs.google.com/document/d/13HRlZ6jB5eFwwph7K3yOxUfxtQsKcNXUNUataqzhPtY/edit#) outlining our initial thoughts. Today is my #5ftf, so I'm going to get a new branch setup and dump all the Sass. I also created [a milestone](https://github.com/WebDevStudios/wd_s/milestone/2) and will get some initial issues in later.

**Clearly, this is a huge breaking change** - and for those of you out there who use wd_s too, we want to make sure that we take this slow - and do things right. To help with the transition, we will make sure that the Bourbon/Neat iteration of wd_s remains in its own branch.

Code standards may need to be revisited. We use WordPress CS as our baseline, however, Foundation has [their own](https://github.com/zurb/foundation-code-standards).

As far as the[ existing wd_s issues](https://github.com/WebDevStudios/wd_s/issues), I don't know what do. If we're switching to Foundation - then we should abandon building a custom grid etc...I suppose I could close them out?

# Giving Back
Foundation is open source, and we love open source software at WDS! Which means during your #5ftf time, [you can contribute](https://github.com/zurb/foundation-sites/blob/develop/CONTRIBUTING.md) not only to a tool that WE use, but a tool used by thousands!

If you're reading this, and are familiar with Foundation - we want your help. I'll be adding a milestone/issues on Github later today.

# Wrap Up
In closing, I was moved by everyone's enthusiasm on yesterday's scrum. The fact that y'all stayed late to discuss this crazy idea was invigorating! 😄 

I care deeply about wd_s, and believe it's a big reason WDS is successful. I believe that offloading the cruft of maintaining a framework (and all that goes with that) onto a larger community is the right choice. Thank you for helping making it the best WordPress starter theme on the planet! 💪 

It's time to start [reading up](http://foundation.zurb.com/sites/docs/index.html) on Foundation, and feel free to follow along with [our progress](https://github.com/WebDevStudios/wd_s/tree/feature/foundation)!

👋

**Comment by carrieforde** [comment]
I'm totally excited to see where we go with this, but I'm also interested in seeing more of a transition plan. Anything I can help with on that front @gregrickaby ?

**Comment by gregrickaby** [comment]
@carrieforde More than anything, I feel like we need: documentation and education. 

Our devs need to know how to work with Foundation + wd_s. The [wiki](https://github.com/WebDevStudios/wd_s/wiki) would be great place to start!

**Comment by gregrickaby** [comment]
Hi  👋 ,

Based on internal discussions, [WebDevStudios](https://webdevstudios.com) is moving forward with merging [Foundation](https://github.com/zurb/foundation-sites/) for our next version of `wd_s`...which will be named: `wd_f`. Because this will a _huge change_, development of this new starter theme will happen in a separate repository, which will remain private (for now).

For those who prefer [Bourbon](https://github.com/thoughtbot/bourbon)/[Neat](https://github.com/thoughtbot/neat), we have good news: WDS has no plans to stop supporting `wd_s`. This is a mature, stable starter theme with 3 years of development and over 1,400 commits. It would a shame to shut it down.

In the meantime, I'll be closing all issues and milestones labeled with Foundation. 

Thank you for your support and the discussion! 👏
