### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#288]
Need to make sure our Readme has updated information about how to use wd_s. Off the top of my head...

- [ ] Remove Bourbon/Neat mentions
- [ ] Link to Foundation and docs
- [ ] Explain setup
- [ ] Show file structure
- [ ] Explain cherry picking Foundation components in both Sass/JS
- [ ] Discuss setting the Grid width
- [ ] Discuss a11y

Branch: https://github.com/WebDevStudios/wd_s/tree/foundation

**Comment by xBLADEx** [comment]
The [README.md](https://github.com/WebDevStudios/wd_s/blob/master/README.md#advanced) mentions updating and replacing __s.com_ with the _project-name.dev_
This is found in the Gulpfile.js and it is a comment.
My suggestion is to change http://_s.com:3000 to http://testing.dev:3000 and update the README.md to clarify changing the proxy testing.dev.
