### ISSUE TITLE
Remove Gravity Forms From WD_s?

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/wd_s#311]
Including gravity forms out of the box seems a little presumptuous as a base theme, but is more importantly problematic because of how it's forcing `!important` overrides which aren't ideal.

Propose removing `_graivty-forms.scss` styles by default, but if it's used turning "Output CSS" OFF and "Output HTML5" ON within the plugin and then taking advantage of a more simple and clean style sheet based on that.

This is the first pass here:
https://gist.github.com/jomurgel/514247b69149b271d53c182fb2b8506e

This gist adds basic styles that should address 90% of form elements from Gravity Forms as well adding helpers for all Standard Fields, Pricing Fields, and Advanced Fields.

**Comment by gregrickaby** [comment]
Thanks @jomurgel for thinking about this and your first pass at a refactor. I'm going to have to respectfully disagree with removing them from the theme entirely. 

I can't remember the last project our team did which _didn't_ use Gravity Forms. IMHO: It's easier to remove the GF partial and move on with the build, then to have to write styles from scratch - or even go find a Gist somewhere.

Now, this isn't to say that our form styles aren't dated. @efuller spent a couple weeks writing these styles a few years ago, so it's probably time to update them - and your first pass looks great, can't wait for a PR. 

Thanks! 👍

**Comment by jomurgel** [comment]
@gregrickaby totally fair. I think I've only used GFs on maybe one project, so if it's more often than not, totally down with keeping it.

👍

**Comment by jomurgel** [comment]
Given the notes above and the need for Gravity Forms on client projects, I'm closing this task.
