### ISSUE TITLE
Running babel on uglify

### ISSUE THREAD

**Issue by samikeijonen** [WebDevStudios/wd_s#322]
Thanks for hard and great work on `wd_s`! In my own projects I usually use combination of `_s` and `wd_s`. From `wd_s` I like the Gulp tasks for example.

But I usually don't load single `project.js` JS file, I just load all `*.min.js` files.

But when I now started using ES6+ in my project I noticed that `uglify` task gave me errors. The reason for this is that `gulp-uglify` is not ready for ES6+.

So could you consider adding babel to `uglify` task also? And why not `errorHandler` at the same time. 

`uglify` task could look like this after that:

```js
/**
  * Minify compiled JavaScript.
  *
  * https://www.npmjs.com/package/gulp-uglify
  */
gulp.task( 'uglify', [ 'concat' ], () =>
	gulp.src( paths.scripts )
		.pipe( plumber({'errorHandler': handleErrors}) )
		.pipe( rename({'suffix': '.min'}) )
		// Convert ES6+ to ES2015.
		.pipe( babel({
			presets: [ 'latest' ]
		}) )
		.pipe( uglify({
			'mangle': false
		}) )
		.pipe( gulp.dest( 'assets/scripts' ) )
);

```

**Comment by gregrickaby** [comment]
Thanks @samikeijonen. I merged this in!
