### ISSUE TITLE
Remove title from original svg-icons.svg file

### ISSUE THREAD

**Issue by samikeijonen** [WebDevStudios/wd_s#323]
In `_s_display_svg ` we can provide `i18n` ready titles and desc if needed. Therefore I think we could remove `<title>`s in the original `svg-icons.svg` file. This could be done inside cheerio with `$( 'title' ).remove();`. Something like:

```js
// Clean up the <symbol> by removing the following cruft...
.pipe( cheerio({
	'run': function( $, file ) {
		$( 'svg' ).attr( 'style', 'display:none' );
		$( '[fill]' ).removeAttr( 'fill' );
		$( 'path' ).removeAttr( 'class' );
		$( 'title' ).remove();
	},
	'parserOptions': {'xmlMode': true}
}) )
```

**Comment by gregrickaby** [comment]
Thanks @samikeijonen. I merged this in too!
