### ISSUE TITLE
Refactor `mobile-menu.js` to target submenus independently.

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/wd_s#333]
Currently the `mobile-menu.js` script targets the menu items at a more global level and adds the `is-visible` class which can cause some unnecessary nesting of styles.

Would like to look into potentially adding additional submenu classes or add is-visible as submenus are opened vs when the parent is opened.

**Comment by gregrickaby** [comment]
Closing since #273 was merged in.
