### ISSUE TITLE
Great stuff. How do I use it?

### ISSUE THREAD

**Issue by DevonVille** [WebDevStudios/wd_s#338]
Hello, I came across this extension of _s and it seems great.
There are, however, a lot of things I can't quite understand -
bits and pieces not fully comprehensible.

For example:
I see ACF is a necessary plugin. Are there others?
What is the scaffolding template part used for?

Is there any extensive documentation somewhere,
or rather a forum/chat/whatnot for elaboration?

Thanks

**Comment by thatryan** [comment]
I myself just got this up and running locally, attempting to learn it for use in a new project ha.
ACF is not "necessary" it appears only needed if you are using the content blocks template part.

<img width="330" alt="cloudapp annotation 2017-11-27 at 9 25 22 am png" src="https://user-images.githubusercontent.com/26583/33279851-ef9c5a4e-d354-11e7-87cf-0c42e5632273.png">

Scaffolding appears to output various examples of styling, so set a page to the scaffold template, save, then view it. You will see colors and sizes etc.

I found a docs file in the directory you download or create, `/docs` and that shows functions and variables available. There is also a wiki, though not much there.

**Comment by DevonVille** [comment]
Thanks, I'll do just that

**Comment by gregrickaby** [comment]
Hello @iwfmp!

@thatryan is correct. ACF v5 is _not_ required to use wd_s. We use it as a page builder on projects, but it's 100% optional.

We do have some (albeit limited) documentation on the [Wiki](https://github.com/WebDevStudios/wd_s/wiki) and we also blog about wd_s at [webdevstudios.com](https://webdevstudios.com/tags/wd_s/). 

Unfortunately, there isn't anywhere to chat...but I think that's a interesting idea. Let me take this in house and discuss with the team. We do provide our clients with extensive documentation, maybe we can move that over here as a baseline.

Thanks for giving wd_s a go. Cheers! 😄
