### ISSUE TITLE
Add password protected support to ACF block workflow

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wd_s#343]
We should consider utilizing functionality like post_password_required(), and similar core functions, with our usage of ACF blocks. Wrapping the block output would enable support right away, for WDS clients and the clients of others who may also do blocks.

By default, this only works for the_excerpt() and the_content(), so it's a missing component in these specific cases.

**Comment by gregrickaby** [comment]
Great find @tw2113 ... we'll make sure this gets merged in!
