### ISSUE TITLE
Subfields invisible in Other Options field group

### ISSUE THREAD

**Issue by tiborp** [WebDevStudios/wd_s#344]
I wanted to add an extra field to the Other Options field group (to be able to add a CSS-id field for a section), but noticed that the sub fields of this group are not visible in the field edit screen.

They are visible in the page edit screen (and in the json file) though. I tried adding a field, but when that is saved all other (invisible) fields get removed from the json file. Am I missing something obvious?

Thanks in advance.

![schermafdruk 23-01-18 10 04](https://user-images.githubusercontent.com/1078764/35266874-d56fc9b0-0024-11e8-8df7-1b9ddf89a284.png)

**Comment by bluestormmax** [comment]
Hey @tiborp thanks for bringing this to our attention. Looks like there is an issue with the JSON sync feature that isn't respecting those subfields. We're looking into a solution and will update asap.

**Comment by tiborp** [comment]
Glad this is fixed! Thanks!
