### ISSUE TITLE
Update composer.json so WDS Coding Standards is a dev requirement

### ISSUE THREAD

**Issue by jmichaelward** [WebDevStudios/wd_s#361]
composer.json lists WDS Coding Standards as a dependency requirement for wd_s. This means that a distributable version of wd_s would include PHP Code Sniffer, WordPress Coding Standards, and WebDevStudios Coding Standards.

We should update the composer.json file so that this is a dev dependency only. wd_s as a theme does not have a dependency on these external libraries in order to function.

**Comment by gregrickaby** [comment]
@jmichaelward Sounds good. If you could, please submit a PR and I'll go ahead and merge it in. Thanks!

**Comment by jmichaelward** [comment]
@gregrickaby I just submitted a PR with an update composer.json and composer.lock file.
