### ISSUE TITLE
ESlint rules

### ISSUE THREAD

**Issue by samikeijonen** [WebDevStudios/wd_s#366]
I was wondering are all the ESlint rules needed since many seems to be the same as [WordPress lint rules](https://github.com/WordPress-Coding-Standards/eslint-config-wordpress/blob/master/index.js)?

**Comment by gregrickaby** [comment]
Hey @samikeijonen thanks for the ticket.

@aubreypwd Could you maybe answer this? I know you worked extensively on our `.eslintrc.js` over at https://github.com/WebDevStudios/WDS-Coding-Standards

**Comment by gregrickaby** [comment]
@aubreypwd Just a friendly reminder ping... 🏓

**Comment by aubreypwd** [comment]
@samikeijonen We do (or will have) have some custom rules and _some_ that are a bit different than what WP does exactly.

**Comment by coreymcollins** [comment]
Going to close this with Aubrey's response, and the conversation having come to a halt in the thread.

Feel free to open an issue again here or in the [WDS Coding Standards](https://github.com/WebDevStudios/WDS-Coding-Standards) repo if you want to continue the discussion – thanks!
