### ISSUE TITLE
Full width Gutenberg blocks break when a sidebar is present

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#367]
When testing out https://github.com/WebDevStudios/WDS-Blocks/pull/47, I found out that any WDS Block which is full-width, breaks when a sidebar is present. 

![kapture 2018-05-01 at 12 27 46](https://user-images.githubusercontent.com/200280/39484324-1568f510-4d3b-11e8-832a-13e44c62e2e8.gif)

**Comment by coreymcollins** [comment]
Turns out this one is coming from the plugin itself rather than wd_s.  I opened a PR in the WDS Blocks repo here: https://github.com/WebDevStudios/WDS-Blocks/pull/48

**Comment by coreymcollins** [comment]
I wonder if this issue exists on its own in wd_s, though, with our current ACF Blocks?  Could still be something to dig into.
