### ISSUE TITLE
Would you accept a PR for GitLab CI? 

### ISSUE THREAD

**Issue by zachary-russell** [WebDevStudios/wd_s#371]
I am an avid user of GitLab and have been working to get automated tests into my theme dev workflow. I'm in the process of getting my version of `wd_s` working with GitLab's CI - my current progress [here](https://gitlab.com/protechig/atlas-theme/blob/master/.gitlab-ci.yml). 

In the open source spirit - would you accept a PR for a `.gitlab-ci.yml`?

**Comment by gregrickaby** [comment]
@zachary-russell Yes!

**Comment by zachary-russell** [comment]
@gregrickaby Awesome! Once I get this fully functioning i'll submit a PR (dealing with an obscene number of errors on a vanilla theme - not sure the root cause yet).
