### ISSUE TITLE
Can't get Gulp working with WD_S theme

### ISSUE THREAD

**Issue by snake2401** [WebDevStudios/wd_s#373]
Hi there,

I am a but of a newbie concerning gulp workflows. But i followed some install tuts and i think i have it all installer and up n running. But when i want to start the gulp watch cmd in the terminal in my working directory, i get ll kinds of errors. like:

MacBook-Pro-van-Herco:skjeugd hercoterweij$ gulp gulp-watch
gulp gulp-watch[55236]: ../src/node_contextify.cc:629:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x2aabc0e0427d
 8: 0x2aabc0e0f755
 9: 0x2aabc0e8bc20
10: 0x2aabc0e144f7
11: 0x2aabc0e144f7
12: 0x2aabc0e144f7
Abort trap: 6

Now i also installed xcode on my MBP. I think it might have to do something with that... Anyone got an idea

**Comment by gregrickaby** [comment]
@snake2401 

Which version of Node/NPM are you running? You can check by running this command: `node -v && npm -v`

I'm on v8.11.1 and 6.1.0 respectively, and everything seems to be working fine.

**Comment by snake2401** [comment]
Figured it out. Node 10.4 was the problem. Downgraded to 9.11.1 and it worked like a charm.

**Comment by gregrickaby** [comment]
I purposely stay on whatever the LTS version (in this case, v8) is for that very reason. Glad you got it working!
