### ISSUE TITLE
Context Based Color Variables

### ISSUE THREAD

**Issue by mharis** [WebDevStudios/wd_s#376]
I have been very familiar with context based color variables which makes it easier to read and understand code. Right now, the color variables are defined with a color name. What are your thoughts on changing it to a context-based naming scheme e.g. $primary-color, $secondary-color, $button-color, $link-color?

I have seen the context-based scheme used within the other areas of SCSS but defining them in one place, in my opinion will make it very easy to follow.

**Comment by jomurgel** [comment]
I agree with @mharis. I would argue that the industry standard would follow the more bootstrap/context-based naming conventions for colors over naming colors to match their HEX values.

It would certainly make things a tad clearer when a build has a large number of colors.

**Comment by Cheffheid** [comment]
I have no issue with this in principle. I can only come up with extreme instances where this may get a little weird and more specifically projects like Isle of MTV that has probably a dozen different background gradients.

But yeah, Isle is a bit of an extreme example, and the current colour naming scheme doesn't necessarily work in that instance either. "gradient-background-1" doesn't really describe it very well, nor are some of these colours really used elsewhere either. For reference fun times:

```$color-alizarin-crimson-gradient: linear-gradient(180deg, $color-alizarin-crimson-alt 0%, $color-zest 100%);
$color-turbo-gradient: linear-gradient(180deg, $color-turbo 0%, $color-zest-alt 100%);
$color-azure-radiance-gradient: linear-gradient(180deg, $color-azure-radiance 0%, $color-cyan 100%);
$color-green-haze-gradient: linear-gradient(180deg, $color-green-haze 0%, $color-cerulean 100%);
$color-green-haze-gradient-alt: linear-gradient(90deg, $color-green-haze 0%, $color-cerulean 100%);
$color-cerulean-gradient: linear-gradient(180deg, $color-cerulean-alt 0%, $color-red-violet-alt 100%);
$color-alizarin-crimson-alt-gradient: linear-gradient(180deg, $color-alizarin-crimson-alt-2 0%, $color-red-violet 100%);
$color-red-violet-gradient: linear-gradient(180deg, $color-red-violet-alt-2 0%, $color-zest-alt-2 100%);
$color-cerulean-alt-gradient: linear-gradient(180deg, $color-cerulean-alt-2 0%, $color-broom 100%);
$color-razmatazz-gradient: linear-gradient(180deg, $color-robins-blue-egg 0%, $color-razzmatazz 100%);
$color-black-gradient: linear-gradient(180deg, rgba($color-black, 0.7) 80%, rgba($color-black, 0.05) 100%);```

**Comment by coreymcollins** [comment]
Decisions have been made!

For now, the plan is to:
- Retain the current way we set color variables, like `$color-blood-orange: #ff0000`
- Then, where we need a contextual variable name we'll reference the color variable, like `$button-color: $color-blood-orange`
- Finally, we'll clean up the partials and move all of our contextual color settings into `/variables/_colors.scss` and out of any other partials so everything is in one easy-to-find location

Thanks for the suggestion @mharis and the feedback, everybody!

**Comment by coreymcollins** [comment]
Also, I'm sorry Isle of MTV hurt you like that @Cheffheid 😢

**Comment by Cheffheid** [comment]
I got to use "razzmatazz", it's cool.

**Comment by jomurgel** [comment]
Added a branch `feature/#376-color-variable-naming-structure` for handling some updates here. Will make notes as I go.
