### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#389]
Because of the time suck that was #341, I'd like to try and make the switch to Webpack. 
I'm throwing this out as an example, since I've already put a ton of time into this Webpack config (modeling it after wd_s Gulp workflow): https://github.com/gregrickaby/MoaningMyrtle. 

**Couple things**

- Our current Gulp workflow to be the model we work towards! Meaning, I'd like our Webpack workflow to be as close to a 1:1 match as possible.

- I'd also like to keep Gulp in a feature branch for several months, to give folks time to transition. We did the same thing when we moved from Grunt --> Gulp.

**Other considerations**

- Drop sass-lint for [stylelint](https://stylelint.io/)
- Update to Babel 7
- Drop Sass Docs
- I want linting to happen with each compile (see my example Webpack config, it does this)
- BrowserSync stays!
- NPM scripts all they way
- Move browerlist to `package.json` 
- Update our linting configs to match WDS Code Standards

**Comment by mharis** [comment]
Progress over here: https://github.com/WebDevStudios/wd_s/tree/feature/389-webpack

**Comment by mharis** [comment]
@gregrickaby 

Can you give a quick look at the repo and give me an idea if I'm on the right path? https://github.com/WebDevStudios/wd_s/tree/feature/389-webpack

Basically, it's still rough and not up-to-date with our gulp structure yet but that is something that I'll able to finish tomorrow but I am looking for your feedback.

**Comment by gregrickaby** [comment]
@mharis Could you open a PR? Easier to review code... 

I'll take a look this morning on my local. Thank you!

**Comment by mharis** [comment]
Removed sass lint and moved all rules to stylelint.

https://github.com/WebDevStudios/wd_s/blob/feature/389-webpack/.stylelintrc

**Comment by mharis** [comment]
Add ability to write all Saas code in pixels and convert to rem/em or leave as pixels based on our rules defined here: 
![image](https://user-images.githubusercontent.com/601054/47749477-ff460800-dcae-11e8-8e50-04e218d18f96.png)

**Comment by jomurgel** [comment]
I went through and tested this but ended up getting errors on bundle. I ended up adding inline-ignores for empty blocks inside the `_modal.scss`,`_typography.scss`, and the `_wds-cta.scss` partials.

I also updated the `.stylelintrc` setting for `sh-waqar/declaration-use-variable` which adds `inherit` to the list of ignores, which is used in a couple places.

**Comment by jomurgel** [comment]
Kind of wondering if something like this would serve our purpose for unit conversion. https://github.com/putneydm/pixelstorem

Might have to write our own PostCSS plugin to do what we need.

**Comment by jomurgel** [comment]
I fixed a couple of issue with BrowserSync, including adding the `reloadDebounce: 2000` setting to prevent BrowserSync from reloading every second. This solved a few issues, but I'm still getting this issue after some time has elapsed.

![screenshot_2018-11-14_12_31_51](https://user-images.githubusercontent.com/5230729/48507602-9bbcee00-e809-11e8-9226-60a4e8d66e50.jpg)

I can't seem to track down a specific issue causing this just yet.

@mharis has talked about potentially stripping BrowserSync entirely in favor of Hot Module Reloading or `webpack-dev-server`, but I'm uncertain if we can really take full advantage of either without BrowserSync to proxy for PHP, etc. More research required there.

**Comment by jomurgel** [comment]
This is what I'm working on currently to convert `px` to `em` or `rem` based on some defaults.
``` js
var options = {
    base: 16,
    precision: 3,
    toEM: [
        'letter-spacing',
        'text-shadow'
    ],
    toREM: [
        'box-shadow',
        'font-size',
        'margin',
        'padding'
    ],
    ignoreList: [
        'border',
        'border-radius'
    ]
};
```
https://github.com/jomurgel/postcss-unit-conversion

I need to do more testing but a basic test seems to be working as expected converting `text-shadow: 2px 2px #f00;`, for example, to `text-shadow: 0.125em 0.125em #f00;`

As of this moment I'm only really taking those defaults and converting `em`s and `rem`s respectively and everything else that is set to `px` is ignored. So the ignore list doesn't actually serve a purpose just yet. I'm not 100% convinced that we even need an ignore list, to be honest.

**Comment by mharis** [comment]
In my latest commit, I did research on how to set it up and it took a lot of time. We'll need to use webpack-dev-server with proxy which is now ready and will be triggered with `npm start` but it will not load styles and scripts.

We might need to use https://www.npmjs.com/package/extract-css-chunks-webpack-plugin to load the css.

**Comment by mharis** [comment]
Alright, `webpack-dev-server` is now setup with hot reloading. All you have to do is run `npm start` and it will handle it.

:+1:

**Comment by efuller** [comment]
Just wanted to provide an update here. I've had some time throughout the week to work with this a bit.

I was originally looking into the relative path issue when including images via CSS. I have at least one working fix for this.

As I've been working with Webpack and wd_s, I have not been happy with its performance. Scss changes are not being injected quick enough and the initial build can take 30 seconds to load. Some of this also seems to be related to Local as well.

I have a few ideas that I'd like to research and try. What I will probably do is branch off of the Webpack feature branch to do my testing because I want to scale everything way back.

Most times when I setup Webpack for WordPress, it's in the context of a plugin and everything seems to perform very well, so I want to try and pinpoint where the slowdowns are.

**Comment by efuller** [comment]
Spent a bit more time on this today and I'm becoming more and more convinced that a Gulp + Webpack config might be the way to go. From the research I've done, Gulp appears better at managing static files and faster at compiling CSS/SCSS. 

Being able to inject a Webpack config would then give us the best of both worlds.

I'm going to work on a basic implementation. It shouldn't take too much effort!

**Comment by efuller** [comment]
@gregrickaby @jomurgel @mharis 

I've been doing some more testing/researching this evening and I think I might be onto something. 

I've got an initial setup using Gulp + Webpack, and it seems to be performing really well. I think `gulp watch` is faster than what we currently have in place.

Gulp continues to handle everything except the JavaScript.

I have created a branch here: https://github.com/WebDevStudios/wd_s/tree/feature/gulp-plus-webpack.

Both Gulp and Webpack are tied into Browser sync and it seems to be really fast when in watch mode!

I need to work on a production build, linting, and a few other things.

Here is a gif. Note that the gaps between changes are from me having to actually change the JS and Scss.

![](https://d.pr/i/yBsA3N+)

**Comment by efuller** [comment]
Update:

More good progress on the Gulp + Webpack implementation today!

- Setup some initial start scripts
- Tested the config to see if I could transpile down to IE11 if needed. This worked. 16ffcdb9562acb4a4bc10fd11f7b44c20c7bd524
- Setup a basic production build for JS.

Next, I think I'll get linting in place.

**Comment by efuller** [comment]
Quick Update:

Progress is going pretty good. Been hitting and fixing some issues along the way.

Hot module reloading is in place and working well with both CSS and JS. There was an issue with having to manually reload the page when HMR would fail, which it can do at times. However, I was able to get this corrected today so that it will just reload the page when HMR fails.

https://d.pr/v/yD6Bec

At this point, I am working to figure out some things around configuration. I have a few ideas and I'm just going to run with them!
