### ISSUE TITLE
Include Normalize and Animate.css instead of importing from bower_components

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/wd_s#401]
Google Pagespeed Insights dings the theme for `animate.css` and `normalize.css` being render-blocking as they are loaded externally from our `bower_components` folder.

To get around this on some projects to help improve render times, we've moved those files into a new `vendor` directory in the Sass directory:
![](https://dl.dropbox.com/s/ewhp57pilq3g2rb/Screenshot%202018-09-27%2013.43.21.jpg?dl=0)

Then, in `style.scss` we change this:
```
@import 'assets/bower_components/normalize-css/normalize.css';
@import 'assets/bower_components/animate.css/animate.css';
```

To this:
```
@import 'vendor/normalize/normalize';
@import 'vendor/animate/animate';
```

Despite those individual files not being enqueued, Google still sees them as external calls when compiling them into the main stylesheet. This gets around that problem.

I would suggest we make this change, but still keep Normalize and Animate in our `bower_components` folder – this way, we can always be sure to have an updated version of them readily available to copy and paste into our Sass directory rather than having to hunt down the latest versions online.

Thoughts?

**Comment by gregrickaby** [comment]
I don't believe this will be an issue when #389 is finished, with that said, I don't mind this change in the interim.
