### ISSUE TITLE
Add support for accordion (reusable element)

### ISSUE THREAD

**Issue by mharis** [WebDevStudios/wd_s#413]
Accordion and toggles are a part of almost every project.

We should add built-in support for it in wd_s.

**Comment by coreymcollins** [comment]
I have some good examples of this on recent projects that I can work in here. I'll try and work on this today, but if I don't get to it I'll un-assign myself and let someone else grab it!

**Comment by coreymcollins** [comment]
I think it probably makes sense to roll this as an ACF Block as well. The markup and classes can be kept global enough to add to a template as static content, but why not go the next step and add a reusable block as well?

We've used that a number of times recently as well.
