### ISSUE TITLE
Documentation: Add notes around updated menu functions

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/wd_s#423]
Refer to #410

**Comment by jomurgel** [comment]
I added documentation to the tail end of the template tags wiki here https://github.com/WebDevStudios/wd_s/wiki/Template-Tags

I also went back and added languages to the code blocks to enable syntax highlighting where applicable 👍 

I went back and did that for all of the wiki pages where applicable or not already done.

**Comment by coreymcollins** [comment]
Nice work, and thanks for the bonus of adding the language to the blocks!
