### ISSUE TITLE
Documentation: ACF Block Settings

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/wd_s#426]
Update screenshots and details around settings to reflect latest updates.

Refer to #396

This is also somewhat related to #424, so if you're going to grab one please grab the other to update all of the ACF documentation at once. Thanks!

**Comment by jomurgel** [comment]
I've added documentation for the new background classes and block custom/default IDs. 

It did not appear, as of now, that there are any new additions that aren't already documented in the [wiki](https://github.com/WebDevStudios/wd_s/wiki/ACF-Content-Blocks).

**Comment by coreymcollins** [comment]
Looks good!
