### ISSUE TITLE
Documentation: Update docs around /inc/ files

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/wd_s#431]
Let's beef up the documentation around our `/inc/` directory. This has started already with the addition of a [Extras](https://github.com/WebDevStudios/wd_s/wiki/Extras) and [Hooks](https://github.com/WebDevStudios/wd_s/wiki/Hooks) pages to the wiki, but let's go through the files and add documentation for the functions and functionality within those files.

Refer to #430 for some good starting points.

**Comment by jomurgel** [comment]
1. Added a new page with the functions for the acf.php file at https://github.com/WebDevStudios/wd_s/wiki/ACF-Functions
2. Added a few new or missing functions to https://github.com/WebDevStudios/wd_s/wiki/Hooks/
3. Pointed https://github.com/WebDevStudios/wd_s/wiki/Customizer to the hooks dock with those functions.
4. Added missing functions to https://github.com/WebDevStudios/wd_s/wiki/Template-Tags.
5. Added some additional documentation and screenshots to https://github.com/WebDevStudios/wd_s/wiki/Customizer.

**Comment by coreymcollins** [comment]
These look great – thanks, Jo!
