### ISSUE TITLE
Social Media Widget

### ISSUE THREAD

**Issue by mharis** [WebDevStudios/wd_s#434]
We should add a social media wordpress widget or support to add social media/icons to WP menu links.

**Comment by coreymcollins** [comment]
We have added some support for social networks in a couple of themes in the past when social links are needed in a menu-type situation. I haven't had to do it consistently, so it was never added to `wd_s` core but if we think it'd be useful we could add it in.

Basically, we loop through our social networks set in a `$social-sites` Sass list targeting the `href` of the link and adding the icon that way. With this, the user/client doesn't need to worry about adding any extra classes to their menu items.

```
$social-sites: facebook twitter googleplus linkedin instagram youtube;

// Set the background image for each social network.
@each $network in $social-sites {
    &[href*='#{$network}'] {
        background-image: url('assets/images/svg-icons/#{$network}.svg');
        background-size: rem(30);

        @include media($tablet-portrait) {
            background-size: rem(19);
        }
    }
}
```

Would something like that suffice? Or do you think we still need an actual sidebar widget?

**Comment by coreymcollins** [comment]
(this is obviously a bit of an older example with that pesky `googleplus` in there :laughing: )

**Comment by mharis** [comment]
@coreymcollins We should keep our theme clean from widgets and shortcodes (even the yearly shortcode) and create a helper plugin or plugins for this functionality. This will keep code base leaner and easier to maintain.

**Comment by coreymcollins** [comment]
@mharis this example doesn't create a widget at all – just basic styles to style links with social network URLs in a menu. This functionality would/does work based on the core WP nav menu without any additional functionality in the theme. Since it's all CSS-based and affects visuals without added widgets/functions, I think this could be pretty easily added to the theme.

For me, it seems like overkill to create a plugin for 11 lines of Sass.

Thoughts?

**Comment by mharis** [comment]
Ohh okay, yes, that makes sense. My original proposal was to create a WP widget.

**Comment by mharis** [comment]
With fields, and all the fun stuff which is overkill for a theme, esp a starter theme.

**Comment by jomurgel** [comment]
@mharis still something you think is needed or worth building?
