### ISSUE TITLE
Outline on Firefox

### ISSUE THREAD

**Issue by mharis** [WebDevStudios/wd_s#435]
More research required:

The outline on Firefox apparently takes the link color and it is thinner than other browers (e.g. chrome). We may want to research into it and decide if we should implement a more accessible option.

![image](https://user-images.githubusercontent.com/601054/47750077-5ef0e300-dcb0-11e8-900d-600df7b8575b.png)

**Comment by coreymcollins** [comment]
@Cheffheid put together a CodePen showing some of this off: https://codepen.io/Cheffheid/full/ePwYZa/

It looks like actual `<button>` elements get a black outline, but you can see the text links getting the special outline color.

I forked his Pen and created one here with the common use-case of a link styled as a button: https://codepen.io/coreymcollins/pen/wYLYRd

It looks like here, the outline is adopting the text color as the outline color. This *could* be okay in most cases unless the text color matches the background color at which point there would be no visible outline.
![](https://dl.dropbox.com/s/tpa654gnjn9ajjd/firefox-outlines.gif?dl=0)

**Comment by mharis** [comment]
@coreymcollins I think this ticket can be closed since this is the default behaviour of Firefox and we shouldn't customize it. Customizing it means being on top of Firefox all the time and testing all the possible elements and its interactions. It's definitely weird but we should leave it up to Mozilla team.

**Comment by jomurgel** [comment]
@coreymcollins I agree with @mharis on this one here.

**Comment by ImBigWill** [comment]
Talked to Corey about this one, we can close it out.
