### ISSUE TITLE
Add default HTML elements to scaffolding page

### ISSUE THREAD

**Issue by mharis** [WebDevStudios/wd_s#440]
Example Elements:

1. Table
2. Lists
3. All form elements
4. Tables
5. abbr, pre, code, sub, sup
6. Blockquotes
7. Image left, right, center, none.

https://wp-themes.com/?p=36

**Comment by bezierer** [comment]
I could see the benefit of having this all with the scaffolding items instead of a separate page. Would we want to go all in and just include _all the things_ that are included in theme unit test data while we're at it or would that be too much? i.e. http://wptest.io/demo/

**Comment by mharis** [comment]
It would be a good idea to include some of these from the unit test data.

1. An image gallery is a good option.
2. Images with a caption.
3. Text alignments.

**Comment by coreymcollins** [comment]
I think this all makes sense and are solid additions to the scaffolding page. It would also help stop the need for creating a separate test page/post with dummy content, as we can load up the scaffolding template with this type of stuff.

Some other things that would be good to add (which exist in the sitewide elements test post) would be YouTube and Vimeo embeds to ensure videos flow responsively.

We recently rolled numeric pagination into `wd_s` as well (`_s_display_numeric_pagination`), so it'd probably be good to add that to the list.

Everything else in the standard global design elements test post are already noted above and are solid additions to the template, IMO.
