### ISSUE TITLE
Replace Normalize with Sanitize

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/wd_s#442]
I'd suggest replacing normalize with https://github.com/csstools/sanitize.css.

Normalize seems to cause some conflicts cross-browser and does a lot of things that we already tend to include in our stylesheets by default like `pre` or `code` formatting and box-sizing settings, etc.

**Comment by mharis** [comment]
1. Built by the same developer.
2. Built upon `normalize.css` and both are maintained in sync.
3. Opinionated compared to `normalize.css` but covers a wide range of issues and developers expectation.
4. Supports IE9+ 🤣 

My vote is 👍 and it should be simple to replace without requiring major changes.

**Comment by jomurgel** [comment]
I started working on this but realized that I think I have a couple of questions/thoughts. 

I think this should be implemented into our #389 conversion so we can include via npm. I can setup via bower, but given that bower is deprecated, I don't really feel like we should go down that road.

I did start a branch and test using a static stylesheet added to the `/utilities` directory. `feature/#442-replace-normalize-with-sanitize` which replaces normalize, but I think there are a few "issues" to resolve as a result. Sanitize does more and less to "reset" all the things, so we'll need to address that.

**Comment by jomurgel** [comment]
I'm also noticing that we import normalize (and now sanitize) 7th in our style.scss partial. After our bourbon and neat import and a few other elements and mixins. We should really be importing this above everything else and reset.

I'm inclined to potentially completely replace bourbon with mixins/functions as well. Opened a new issue to do that up for discussion. #443.

**Comment by jomurgel** [comment]
🤦‍♀️ Looks like we have a vendor directory for normalize, so will utilize this for sanatize. Same thoughts above still apply, however.

**Comment by mharis** [comment]
In case this gets merged before webpack. We can always make adjustments to that PR to make sure that it is up-to-date.

**Comment by jomurgel** [comment]
I've made some updates, including cleanup and formatting of a scss version of sanitize: https://gist.github.com/jomurgel/88084c6f3c10de5e47a9238087508e63

PR issued here: #444
