### ISSUE TITLE
Replace Bourbon with Mixins/Functions

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/wd_s#443]
Given that Bourbon is deprecating more and more and we probably only use a handful of Bourbon mixins I think we should remove Bourbon as a dependency and move any mixins or functions directly into the theme. 

Would like to get an idea of what everything might use with any regularity. I personally use:

- `em()` and `rem()` — potentially replaced with #389 and PostCSS Unit Conversion package.
- `position()`
- `size()`
- `margin()`
- `padding()`

**Comment by jomurgel** [comment]
The `media` mixin is actually part of Neat, so with #438 we can port that over for use. I also have media query mixin that could be used after review also: https://gist.github.com/jomurgel/c2eb29c6203ce6478015b39138a8e2af

I only bring that one up because the mixin for neat seems like, although we know it works, contains stuff we don't really need.

Neat Mixin: https://github.com/thoughtbot/neat/blob/v1.9.1/app/assets/stylesheets/grid/_media.scss

There are many out there we could take a look at and roll our own also.

**Comment by jomurgel** [comment]
Additional notes here.

### General
- #438 would replace the Neat grid and full-width mixin.
- I think that we should enable the `@include font;` mixin by default.
- Many mixins like `hyphens` for example includes the `-moz`, `-ms`, and `-webkit` variants, but this should be done with Autoprefixer. Same with many of the mixins.

### Remove
- Hyphens
- Font Legibility — Could just be added to our `_typography.scss` partial.
- Margin Auto — Seems unnecessary as a mixin.
- Margin Padding Reset
- Vertical Align
- Word Break
- Z-Index — Feels like this would be far quicker just to assign the index vs using a mixin.

### Keep
- Color Classes
- List Reset

### Add
- Em/Rem — Though We could take advantage of the PostCSS Unit Conversions to outright remove these.
- Clearfix — used by List Reset — though having removed the floats in #438 it may not be necessary or required.
- Position
- Size
- Margin
- Media Query — Added in #438.
- Padding

**Comment by jomurgel** [comment]
Took care of the above in a branch which I merged into #438. Realized that these updates along with some additional handling/tweaks were needed around the grid as a result, so I opted to take care of this and roll that into grid updates. In the interest in analyzing what's in use currently and taking liberties, I thought, what the hell.

Updates merged into #438 were as follows:

### Updates
- Replace normalize with Sanitize — seen in #442 
- Inlines Instances of Triangle Mixin with inline styles.

### Removes
- Bourbon as a dependency
- Bourbon from Gulpfile.js
- Hyphens Mixin
- Font Legibility Mixin
- Margin Auto Mixin
- Margin Padding Reset Mixin
- Vertical Align Mixin
- Word Break Mixin
- Z-Index Mixin

### Adds
- Directional Property Mixin — helper.
- Margin Mixin
- Padding Mixin
- Position Mixin
- Shorthand Function

**Comment by coreymcollins** [comment]
Closed via #438.
