### ISSUE TITLE
Audit Default ACF Block Markup

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/wd_s#445]
In reference to notes in #438 it occurs to me that our use of `<article>`, `<section>`, and `<div>` in our default ACF blocks may not be adhering to proper HTML standards or intention.

Specifically because whether or not a `<section>` or `<div>` is required may be a result of what a block is used for and where it's used.

I'd like to perform an audit and/or add additional settings or functionality to these blocks if necessary to fix these issues.

**Comment by jomurgel** [comment]
#438 Did make some updates to the CTA module to be more semantic and follow HTML5 guidelines for this type of block.

I did also, in the issue, create a new Display Options tabs which houses a container width feature. But I wonder if another display option might be to define the type of container: `div`, `aside`, `section`, etc.

**Comment by coreymcollins** [comment]
I think we don't need to give a million options, to be honest. The average user (who we're building the page builder-y stuff for) isn't going to know when or why they would want to use a `section` or a `div`, so I think we could leave that to code in the theme to be adjusted by devs.

I know we had some conversations _somewhere_ about `section` vs `div` usage and seemed to lean toward `div`, but now I'm not sure where those talks happened. Maybe just on scrum? But, we should revisit with the team on Thursday.

**Comment by coreymcollins** [comment]
I think we can close this with #438 and #474 having been merged in. We can always discuss changing the markup later on, but I think the changes we've made at this point are 👍
