### ISSUE TITLE
Consider removing sidebar.php

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/wd_s#450]
A sidebar on any client site or blog seems to be an element of the past. This part is almost always removed in my experience. I'd like to get some feedback on this idea.

WordPress' 2019 Theme has removed this template, which sets precedence.

**Comment by bezierer** [comment]
I definitely feel like we do less and less with the sidebar but there are the few clients who may want one/have asked for it. Wonder if we'd want to just remove the call to `get_sidebar()` from templates but keep the actual file around? Probably not a huge deal either way but just a thought!

**Comment by jomurgel** [comment]
We do have a `template-sidebar-right/left.php` file that utilizes it. It could be that we just relegate it to that template, and remove it from our blog single perhaps.

**Comment by coreymcollins** [comment]
I like the second idea here – using it for a specific page template and removing it from the default single post. We don't tend to use it very often in general, but it's good to offer the option to use one out of the box IMO.

**Comment by coreymcollins** [comment]
Going to table this until #447 is merged in so there aren't too many wild conflicts between branches once it gets merged in. I think it's pretty close, so we should be able to make the adjustments talked about here once that branch is merged in pretty easily.

Thanks y'all!
