### ISSUE TITLE
Put config files outside document root? 

### ISSUE THREAD

**Issue by gaambo** [WebDevStudios/wd_s#457]
Hi there, 
thanks for this awesome starte theme. I wanted to integrate this into our workflow together with roots/bedrock. Until now I've put package.json, yml configs (travis, gitlab ci,...) and other config files outside of the document root. So these were more of application (= the whole website project) dependencies and configuration instead of only for the theme. This has the advantage of source and configuration files not beeing publicly accessable. 
My question is: How do you work around this with your theme? I see on the project website one can simply call the url for the [travis.yml](https://wdunderscores.com/wp-content/themes/wdunderscores/.travis.yml) and [package.json](https://wdunderscores.com/wp-content/themes/wdunderscores/package.json). I don't know if this really has some security side-effects but i just think it's not ideal. 

I was thinking about forking this repository or building a script which clones the template and moves tasks, configuration and dependencies out of the theme directory. 

Alternatives would be not deploying those files or restricting access via .htaccess on Apache.

What do you think of that? Also this issue is ment as a place for discussion about the directory structure because I couldn't find anything about it. If it's not the right place for this kind of discussion please close this issue.

**Comment by coreymcollins** [comment]
For us, everything is tied to the theme. While we do create and manage plugins and ship the whole package, the main focus of wd_s itself is to function as a standalone theme that can be dropped in and be ready to go. With that in mind, we all of our config files, Gulp files, etc. into the theme to keep it all self-contained.

We _used to_ keep all of the config and Gulp files in `/wp-content/`, but it wound up being less than ideal when it came to packaging up an entire theme with those pieces in place. Plus, we didn't want to have to manage the entire `/wp-content/` directory as part of the theme – rather, we manage that as part of our overall project and include the theme.

We do have some wheels in motion to move away from some of our longstanding processes toward Webpack (#452), so some of what we have in place now will be going away once we have all of the kinks worked out there.

This theme is an ever-changing and ever-evolving thing, so we definitely welcome any discussion points here! Thanks so much for checking out the theme, and if you do wind up forking it and building something else with it let us know – we'd love to check it out!
