### ISSUE TITLE
Do not track generated files

### ISSUE THREAD

**Issue by aaroneaton** [WebDevStudios/wd_s#459]
Keeping generated files in source control can sometimes create a mess and causes unnecessary merge conflicts that must be manually resolved.

It's been mentioned in the past that simply adding the generated files to `.gitignore` wouldn't be adequate as loading the theme for the first time would deactivate the theme and/or throw errors.

Here's what I'm proposing:
1. `style.css` should only contain the required masthead/metadata.
1. `assets/` should contain two directories: `src/` that contains all of the source JS/CSS/images/fonts and `dist/` that contains the generated assets.
1. Gulp should place generated files under `dist/`
1. The theme should load assets from `src/` when `WP_DEBUG` is set to `true`, load from `dist/` if not.
1. `assets/dist` should be added to `.gitignore`.

## Simplified directory structure
```
── assets
│   ├── dist
│   │   ├── css
│   │   ├── images
│   │   └── js
│   └── src
│       ├── images
│       ├── js
│       └── sass
└── style.css
```

**Comment by coreymcollins** [comment]
I like it! We chatted in Slack about branching off of @efuller's #452 branch as we'll be moving in that direction soon enough. I think getting something in place that we can stress test will be helpful as I like the overall concept and can see it leading to fewer merge conflicts and fewer unnecessarily committed files.

**Comment by zachary-russell** [comment]
I'm curious about how this will affect deployments? Generally, I use git for deployments on all of my sites (either through a service like WP Pusher or something like WP Engine's git functionality). Obviously, a change like this would break my workflow (and likely a lot of the users of this theme). How do you handle deployments? Do you have some sort of CI/CD that does it for you?

**Comment by aaroneaton** [comment]
You make a great point @zachary-russell . WebDevStudios does make use of CI/CD pipelines that would handle this change. If CI/CD isn't a viable option for your project you could remove the lines in `.gitignore` that prevent `assets/dist` from being saved in the git history.

We'll be sure to add some documentation explaining the changes.
