### ISSUE TITLE
What is the correct way to "version" static asses? 

### ISSUE THREAD

**Issue by zachary-russell** [WebDevStudios/wd_s#462]
The specific issue here is that when using this theme with a CDN it very often occurs that visitors will get served static assets. The obvious solution is to add a `?ver=xxx` parameter to the asset URLs. I know you have a `$version = '1.0.0'` to your `inc/scripts.php` file that then gets passed into the register/enqueue functions.

I'm more just wondering how you handle this in a professional workflow? Having to manually bump the version number is likely to slip through the cracks. Is there a way this could be handled from within the theme itself? I've personally used the `filemtime()` function to automatically add the last modified timestamp to static assets.

**Comment by coreymcollins** [comment]
You could certainly update the version numbering to your liking when using/forking the theme. For us, we keep it manual and just bump the version number when we have a need to. We've seen issues where auto-generated times may differ from server to server which makes things harder to track if we're troubleshooting an issue. If the version number is manually set, then we can easily see if a file is v1.1.5, for example, on multiple servers.
