### ISSUE TITLE
Update Hero Title Tag if First Object

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/wd_s#464]
I realized that, in the way that we have the header constructed, the logo/branding/site title acts as an H1 ONLY on the homepage. Everywhere else it's a paragraph tag, assuming that the page title will be supplied by the page, post, archive, etc.

I realized that on ACF content block pages, the first block might be a hero, but the first tag on the page is an H2.

A couple of options here might be to either replace the hero title markup, assuming the hero would be first typically, to something like this:

``` php
$title        = get_sub_field( 'title' );
$heading = 1 === $index && ! ( is_front_page() && is_home() ) ? 'h1' : 'h2';

echo sprintf( '<%1$s class="hero-title">%2$s</%1$s>', esc_attr( $heading ), esc_html( $title ) );
```

Or, writing a function that does a similar thing for all blocks.

One consideration otherwise might be the carousel. We can have 1+ slides with H1s, but would need to adjust some markup to make this possible (though not ideal) — and for the record, IMO, we should just not offer a carousel out of the box.

**Comment by coreymcollins** [comment]
This is taken care of as of #470. Thanks!
