### ISSUE TITLE
Improvement for background-color class

### ISSUE THREAD

**Issue by tiborp** [WebDevStudios/wd_s#467]
I might be wrong, but I noticed the background color class used in the `_s_display_block_options()` function is different from what Gutenberg is using for its blocks. I guess it would make sense to use the same format as Gutenberg is using for this?

wd_s does: `background-' . esc_attr( $background_color );` 
See:
https://github.com/WebDevStudios/wd_s/blob/9dce9f0528bbf25a3ccadc31acfe6a13d1272c18/inc/acf.php#L79

For Gutenberg this would be: `has-' . esc_attr($background_color) . '-background-color`

I think the same goes for the font color class.

**Comment by coreymcollins** [comment]
We have a separate blocks repo here: https://github.com/WebDevStudios/wds-blocks

The blocks in the theme, at this point, are separate from Gutenberg so don't necessarily use the same class name structure as they predate Gutenberg by quite a bit.

There is a PR here which adds support for the Gutenberg classes on Gutenberg blocks: https://github.com/WebDevStudios/wd_s/pull/458

I don't necessarily see a need to update our non-Gutenberg blocks to use the same classes as Gutenberg blocks.
