### ISSUE TITLE
Remove Animate.css

### ISSUE THREAD

**Issue by jomurgel** [WebDevStudios/wd_s#472]
I think we've discussed this before, but I think we should remove `animate.css` and the associated "animation" field from WD_s for a couple of reasons.
- We load all of animate.css all the time into the stylesheet.
- Animate.css only loads on initial load so blocks that utilize the animation "below the fold" will never animate.
- I don't think this feature is utilized with any great amount.

If we decide to keep it I think we should:
- Work in some javascript to trigger the animation on block display into view.
- Only enqueue what we need to when we need to (somehow) instead of the entire animate.css stylesheet.

What say we?

**Comment by coreymcollins** [comment]
I'm all for removing it. I really don't see clients clamoring for animations on blocks all that often, and if we are going to use animations I imagine it would be something like your second scenario – animations that happen as you scroll, not all at once when the page loads.

This is a vote for removing `animate.css` and the animation options from our ACF blocks.

**Comment by ImBigWill** [comment]
I would also vote to remove this feature for all the reasons outlined above.

**Comment by michealengland** [comment]
I vote to remove the extra animation CSS as well for the same reasons as listed above. Also, I would really like the idea of an intersection observer feature for scrolling based animations when elements enter or leave the viewport. This would allow for some great animation possibilities while also making animation more practical in the user experience.

I'd be open to volunteering on this issue.

[Intersection Observer v2](https://developers.google.com/web/updates/2019/02/intersectionobserver-v2)

**Comment by coreymcollins** [comment]
Removed via #480. Byeeeeeeeeee
