### ISSUE TITLE
Get Other Options To Break WP-Rocket Cache

### ISSUE THREAD

**Issue by KrashKartMedia** [WebDevStudios/wd_s#477]
Being able to hide and show a field based on the date/time is great. Can you adjust this to break the cache if the date expires?

**Comment by coreymcollins** [comment]
I think this would need to be customized at your theme level within your codebase. We aren't caching anything in the theme ourselves, and the theme isn't dependent on WP-Rocket Cache to run so we aren't integrated with it.
