### ISSUE TITLE
Ability to set list list of colors once, instead of twice

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/wd_s#479]
**Background**
As I'm setting up a new project, I want to set the clients primary, secondary, and tertiary brand colors for the site. I'm doing this inside the `_color-vars.scss` file as:
<pre>
$color-primary: #4f31a8;
$color-secondary: #8a31a8;
$color-tertiary: #316ca8;
</pre>

I am now able to use those 3 variables throughout my style sheets, and that's fantastic. However, I also want to make the Primary, Secondary, and Tertiary colors available to the user inside the dashboard, right alongside the Alto, Cod Gray, Mineshaft, etc. And, I can do this by editing the function in `acf.php` like so:
<pre>
function projectname_get_theme_colors() {
	return array(
		esc_html__( 'Primary', 'projectname' )        => '#4f31a8',
		esc_html__( 'Secondary', 'projectname' )      => '#8a31a8',
		esc_html__( 'Tertiary', 'projectname' )      => '#316ca8',
		esc_html__( 'Alto', 'projectname' )           => '#ddd',
		esc_html__( 'Black', 'projectname' )          => '#000',
		esc_html__( 'Blue', 'projectname' )           => '#21759b',
		esc_html__( 'Cod Gray', 'projectname' )       => '#111',
		esc_html__( 'Dove Gray', 'projectname' )      => '#666',
		esc_html__( 'Gallery', 'projectname' )        => '#eee',
		esc_html__( 'Gray', 'projectname' )           => '#808080',
		esc_html__( 'Gray Alt', 'projectname' )       => '#929292',
		esc_html__( 'Light Yellow', 'projectname' )   => '#fff9c0',
		esc_html__( 'Mineshaft', 'projectname' )      => '#333',
		esc_html__( 'Silver', 'projectname' )         => '#ccc',
		esc_html__( 'Silver Chalice', 'projectname' ) => '#aaa',
		esc_html__( 'White', 'projectname' )          => '#fff',
		esc_html__( 'Whitesmoke', 'projectname' )     => '#f1f1f1',
	);
}
</pre>

## The Issue
While this technically works just fine, I think it makes sense that you would set the list of color names and their accompanying values in one spot (`_color-vars.scss`) rather than having to go and set them a second time. For example, here's how I would LIKE to set my colors in the acf.php file:

<pre>
function projectname_get_theme_colors() {
	return array(
		esc_html__( 'Primary', 'projectname' )        => $color-primary,
		esc_html__( 'Secondary', 'projectname' )      => $color-secondary,
		esc_html__( 'Tertiary', 'projectname' )      => $color-tertiary,
		esc_html__( 'Alto', 'projectname' )           => '#ddd',
		esc_html__( 'Black', 'projectname' )          => '#000',
		esc_html__( 'Blue', 'projectname' )           => '#21759b',
		esc_html__( 'Cod Gray', 'projectname' )       => '#111',
		esc_html__( 'Dove Gray', 'projectname' )      => '#666',
		esc_html__( 'Gallery', 'projectname' )        => '#eee',
		esc_html__( 'Gray', 'projectname' )           => '#808080',
		esc_html__( 'Gray Alt', 'projectname' )       => '#929292',
		esc_html__( 'Light Yellow', 'projectname' )   => '#fff9c0',
		esc_html__( 'Mineshaft', 'projectname' )      => '#333',
		esc_html__( 'Silver', 'projectname' )         => '#ccc',
		esc_html__( 'Silver Chalice', 'projectname' ) => '#aaa',
		esc_html__( 'White', 'projectname' )          => '#fff',
		esc_html__( 'Whitesmoke', 'projectname' )     => '#f1f1f1',
	);
}
</pre>

One possible solution I was thinking of had to do with making the acf color function filterable and then being able to pass in the colors from the main color file. I have no idea how feasable that is or if that makes it any easier. Happy to chat about it if you'd like.

**Comment by coreymcollins** [comment]
This is an interesting idea and one I can take a look at. The real pickle is sharing variables across PHP and Sass files, which I've truthfully never looked into before.

**Comment by tiborp** [comment]
I just bumped into [10up's Theme Scaffold](https://github.com/10up/theme-scaffold) and found a function that exactly does that:
```
/**
 * Extract colors from a CSS or Sass file
 *
 * @param string $path the path to your CSS variables file
 */
function get_colors( $path ) {
	$dir = get_stylesheet_directory();
	if ( file_exists( $dir . $path ) ) {
		$css_vars = file_get_contents( $dir . $path ); // phpcs:ignore WordPress.WP.AlternativeFunctions
		preg_match_all( ' /#([a-f]|[A-F]|[0-9]){3}(([a-f]|[A-F]|[0-9]){3})?\b/', $css_vars, $matches );
		return $matches[0];
	}
}
```

**Comment by coreymcollins** [comment]
I spent some time last week playing around with a similar idea – getting the contents of a Sass partial and piecing it out in PHP, but it doesn't quite the different scenarios we use the colors throughout our theme (i.e., setting colors for Gutenberg/ACF blocks, setting up our scaffolding page) so there's still a bit more legwork that would need to be done.

It would be nice to have a one-and-done solution, though, so it's something I'll keep poking around at when I have the time.

**Comment by tiborp** [comment]
Yes you are right; I looked into it a bit more and this function is just being used to show the theme colors in a scaffolding page (which still is nifty :-)).

Would indeed be nice to have  a one-and-done solution!

**Comment by coreymcollins** [comment]
Going to close this for now. Might be something we revisit down the road, but there doesn't seem to be a smooth implementation of it at the moment.
