### ISSUE TITLE
Start/End date description typo

### ISSUE THREAD

**Issue by Cheffheid** [WebDevStudios/wd_s#482]
Just leaving this here so that I don't forget about it.

The descriptions for the Start/End date under the "Other Options" tab seem to have a typo in it. They say "Chose", which should be "Choose".

See also these two lines:
https://github.com/WebDevStudios/wd_s/blob/master/acf-json/group_594168e970d85.json#L79
https://github.com/WebDevStudios/wd_s/blob/master/acf-json/group_594168e970d85.json#L96

**Comment by coreymcollins** [comment]
Fixed!

https://github.com/WebDevStudios/wd_s/commit/3cf7da09a63bc0d8e52cdd0ed85050bd1f185bfb
