### ISSUE TITLE
Display Block Options get_field() Fallback

### ISSUE THREAD

**Issue by michealengland** [WebDevStudios/wd_s#484]
### Issue
While working on a recent project, I had a standalone ACF field group that used a cloned field of the background options. This way I could utilize `_s_display_content_blocks()` in combination with the background options clone. At first glance everything looked and function as expected until another field was added that used `_s_display_content_blocks()` and didn't have a background options clone.

### What Caused the Issue
I did some investigating after I noticed some unexpected behavior in other modules. Background colors or images being displayed on blocks that either didn't have backgrounds set or didn't have background options at all. The issue wasn't noticeable because the following conditions have to be met for the incident to occur.

1. A block with `get_field( 'background_options'  );` must be in the content area.
2. The block must have a background option set such as color or an image. This will setup field data for `get_field( 'background_options'  );`.
3. Next, a block without a background option that uses `_s_display_content_blocks()` should be added to the same page. Since this block does not have `get_sub_field( 'background_options' )` it will default to `get_field( 'background_options'  );`. 
4. The block without a background should now display the characteristics of the nearest block with `get_field( 'background_options'  );`.

### Possible Solutions
A possible improvement to this issue could be to add a new parameter that could override `$background_options` when the parameter is passed in. This way on a standalone block, `get_field( 'background_options' )['background_options']` could be replaced with `get_field( 'my_custom_background_options' )['background_options']`.

**Comment by coreymcollins** [comment]
Hey @michealengland – I'm wondering if you can try to replicate your issues here with the new setup using ACF + Gutenberg? I'm curious if the problem still exists or if it worked itself out somehow in changing up how we're using the blocks.

**Comment by michealengland** [comment]
That is a solid idea, I'll check this out and see if I can reproduce the same issues.

**Comment by michealengland** [comment]
# Updates
After doing some testing, I was unable to replicate the original issue and am going to close this out.

**Testing Methods:**
I created a new block that was identical to the hero block. I added both to one page and set the background of the first block (test block) and set did not set any background of the second block (hero block).

Since both blocks use `get_field()` display the background image data I was checking to see if the hero block would inherit the background properties from the test block. It does not appear to have any effects. I suspect this is due to how blocks are rendered from Gutenberg where data is associated with each block instead of each document.
