### ISSUE TITLE
ACF Block titles overflow issue

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/wd_s#508]
**Background**
I'm currently using the feature/npm-wd_s branch

**Scenario**
When I'm on the edit screen for a page and I've added one of the WDS Blocks, the ACF left nav tabs overflow into the content/edit area.

**Steps to reproduce**
- Add a page
- Add any of the WDS ACF blocks ( WDS Accordion, for example) to the page
- While on the edit screen, select the block to view the Block settings down the right side of the screen.

Screenshot: https://vegasgeek.net/2020/cEEStN7hIN4T3vMQQjfq.png

**Comment by gregrickaby** [comment]
Thanks @vegasgeek I'm going to close this though, since it's actually part of #507 

I'll play around with it and see what we can do. Thanks for testing!
