### ISSUE TITLE
ACF Blocks breaking outside of Gutenberg columns

### ISSUE THREAD

**Issue by superfein** [WebDevStudios/wd_s#509]
The ACF Blocks do not appear to be designed to be used inside a standard Gutenberg column block.

Screenshot attached.
![gutenberg-acf-blocks-content-too-wide](https://user-images.githubusercontent.com/10688655/75060867-769b3e80-5494-11ea-84ab-a7258498a38e.png)

Is this purposeful? Are the ACF Blocks that come baked into wd_s only designed to be single column wide blocks?

**Comment by coreymcollins** [comment]
Closed via #512
