### ISSUE TITLE
SVG problems (on working branch)

### ISSUE THREAD

**Issue by martinDolan** [WebDevStudios/wd_s#514]
On `https://github.com/WebDevStudios/wd_s/tree/feature/npm-wd_s-wdscs`

There are a few issues with SVGs:

- They're not resizeable
- Color fill not working

**Not resizeable**
Changing the width and height of the `svg` in other verisons of `wd_s` will scale the `svg` up or down . Currently, changing the size of the svg has no effect on the scale itself, instead only adjusting the boundaries of the container itself.

**Color Fill not working**
Adding a color fill (as in the example below has no impact on SVG output).

Steps to recreate this issue:

Add SVG using the `display_svg` function, for example:

```
_s_display_svg(
  array(
    'icon'   => 'pause',
    'fill'   => '#f87039',
    'width'  => '20',
    'height' => '24',
  )
);
```

**Comment by coreymcollins** [comment]
Comparing the master branch to the npm branch, the issues look to be:
- `viewbox` is being stripped from the `<symbol>` markup in the SVG sprite
- `fill` is not being stripped from the `<svg>` markup in the SVG sprite

If these two changes are made manually, the SVG is able to be resized again. Next step is to look into why this is happening and make the necessary adjustments.

**Comment by martinDolan** [comment]
Thanks @coreymcollins - I plan to look into this in the coming week. I should have time on 5FTF next week at the latest.

**Comment by coreymcollins** [comment]
This should be all fixed with this commit: https://github.com/WebDevStudios/wd_s/pull/507/commits/06d12bfd584dc920b8d8998fb2adb8228b326878

Going to close this one out. Thanks for bringing this up!
