### ISSUE TITLE
Copy frontend dependencies out of node_modules

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/wd_s#519]
Now that everything is installed into `/node_modules/`, we need to figure out a solid way of moving/copying frontend dependencies (for lack of a better term) out of `/node_modules/` so that they are available in the theme.

The main problem:
- We don't commit `/node_modules/`
- So, when we add something like Slick Carousel via `npm`, it gets installed in `/node_modules/` but will never be committed
- Thanks to @gregrickaby we have a bit of a solution in our `package.json` file:
  ```"copy:slick": "cp -R ./node_modules/slick-carousel/ assets/slick-carousel || true",```

This works, _sort of_. @bezierer  has run into an issue where a package he needed was being copied into a folder of itself. Instead of being copied into `/assets/package-name/` it was being copied into `/assets/package-name/package-name/`.

Currently, the `copy:slick` script runs on `npm run build`. A workaround here is to remove it from `npm run build` and let whoever is adding the package copy it once and then commit it. Then, it's there any time anyone else pulls down the repo.

The bummer part of this is:
- It's a workaround
- It involves extra steps
- It's clunky
- It's a little finicky and doesn't give us an easy way to copy an updated version to overwrite the existing version

I found a package called **frontend-dependencies** here: https://www.npmjs.com/package/frontend-dependencies

On the surface, it sounds great and exactly like what we need. I tried messing around with it a bit yesterday, though, and couldn't get it to do what I needed it to do. Might've just been the end of a long day and my brain was fried.

Would love some extra 👀 and :brain: on this to come up with a better solve for this issue!

**Comment by gregrickaby** [comment]
@coreymcollins 👏 👏 👏  [Frontend Dependencies](https://www.npmjs.com/package/frontend-dependencies) looks awesome, and I love that you can specify the files that you want to copy over. Reminds me of Bower.

Short term this could work......long term, we need to be bundling our assets with Webpack.

Webpack reaches into `node_modules`, grabs our dependencies, and smashes them together into `wd_s/dist/bundle.js`. No copying and 🤞
