### ISSUE TITLE
Delete old branches

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/wd_s#533]
We have a bunch of branches here that I think can go by the wayside, but I wanted to check in with the team first before doing so.

Everything highlighted in this screenshot looks like something that can be deleted. There are 6 that are flagged to keep, though the two carousel ones can probably go as well since they're super old using the previous Gulp & Bower setup working with Slick Carousel.

![screenshot of branches to delete](https://d.pr/i/CFWHZS+)

**Comment by gregrickaby** [comment]
I’m good with deleting them 👍🏻

**Comment by coreymcollins** [comment]
Done!
