### ISSUE TITLE
Importing JS from Node Modules? 

### ISSUE THREAD

**Issue by jasondandy** [WebDevStudios/wd_s#534]
It was my understanding that with this theme, if one were to download an NPM package (for example Plyr - https://www.npmjs.com/package/plyr), we could simply import packages, resulting in only a single minified js file? 

When I tried adding `import Plyr from 'plyr';` to one of the files inside the `concat` directory, I get the following error inside my console: `Uncaught SyntaxError: Cannot use import statement outside a module`. 

Can anyone point me in the right direction here please?

**Comment by coreymcollins** [comment]
Hey Jason – I don't believe the packages are intended to work that way. We're using npm to help manager frontend dependencies (i.e., Slick Carousel), so when we install that package as a frontend dependency we then enqueue the scripts/styles the standard WordPress way in our `scripts.php` file. 

Using the Slick example, we're enqueueing the Slick JS & CSS from our `/dist/` directory, then initializing a carousel in our `/src/concat/carousel.js` file: https://github.com/WebDevStudios/wd_s/blob/master/src/js/concat/carousel.js
