### ISSUE TITLE
Need a way to easily allow pagination on Custom Queries

### ISSUE THREAD

**Issue by oliverharrison** [WebDevStudios/wd_s#535]
The current pagination works great for the main loop. But for custom WP_Query(s), it needs to be modified. I propose that we modify the pagination to handle both!

This can be handled by:
* passing the query to the pagination function with a fallback to handle the main query
* checking the total pages in the function so that the pagination knows how many pages the custom query has

**Comment by coreymcollins** [comment]
Closed via #536
