### ISSUE TITLE
Optimized SVGs with fill/stroke in tact

### ISSUE THREAD

**Issue by Cheffheid** [WebDevStudios/wd_s#537]
As it is now, SVGs are optimized and the stroke/fill are removed.

However, sometimes it's easier/better/only possible to do something by setting an SVG as the background instead of using it inline. In this case, you cannot change the colour that it displays as and you would need the stroke or fill attributes to remain present.

In order to solve this, there are probably two options:
- Let svgstore handle the fill/stroke removal for the sprite and only use svgo to optimize everything else it does now. That way, the separate SVG files that are currently dropped in the dist folder for the sprite can also be used as background images. The downside is that it will make the SVG sprite heavier with SVGs that aren't being used as inline icons.
- Set up a script that will "restore" the old way of having a separate SVG image folder that gets copied to dist (with or without minimizing/optimizing, as long as it leaves the fill/stroke in tact it should be fine). The main benefit here is that it'll be easier to see what images are being used for backgrounds, and that it won't blow up the sprite with SVGs that are only for backgrounds. The main downside here is that svgo will break when the folder it's trying to process is empty, so we will need to have at least one SVG present (the play icon comes to mind here as a reasonable option).

My vote will probably be for the second option, which is how I ended up solving it for another project, but whatever works for me. :)

**Comment by coreymcollins** [comment]
I think we're kind of doing your second option at the moment. Right now, we're minimizing and optimizing what's in `/src/images/icons` which is where the basic icons tend to go (play buttons, arrows, carets, social icons, etc.). This uses the SVGO config file which removes the stroke and fill attributes so we can override them with our SVG display template tag.

For other icons which are either more dynamic with a lot of colors that I don't want stripped out or SVGs that I don't need to use inline, I'll create a subdirectory like `src/images/icons/background-icons` and add something to the `package.json` file to handle it, like:
```"background-icons": "svgo -f src/images/icons/background-icons -o dist/images/icons/background-icons",```

It's a bit of a manual process based on the project, but it tends to work. Depending on how we're using icons throughout the site, I might have a need to create multiple subdirectories - for instance, if I need to filter an ACF select field to display icons then I'll need to create a directory for those icons so I can add my filter to display only the icons from that directory.

Does that sound like what you're looking for with your second option, or does it not quite meet your goals completely?
