### ISSUE TITLE
Add support for TailwindCSS

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#547]
Internally, we have agreed upon using [TailwindCSS](https://tailwindcss.com/) as our base. TailwindCSS is a popular utility-based CSS package that can be configured and customized using a `tailwind.config.js`. This will allow engineers to work quickly, and not have to manage homegrown utilities like grids, breakpoints, etc...

- [x] Remove all existing Sass and Sass files
- [x] Hook up @wordpress/scripts (See #546)
- [x] Import TailwindCSS package from NPM
- [x] Create `tailwind.config.js`
- [x] Configure `tailwind.config.js` with base styles
- [x] Follow the [requests outlined by the team](https://webdevstudios.atlassian.net/wiki/spaces/WDS/pages/882311193/Open+Discussion+wd+s)

**Comment by coreymcollins** [comment]
This has been added in the Tailwind branch/PR #551.

We'll be updating the theme to match the team's ongoing requests, so I'll leave this out not-R4R'd for now.

**Comment by ingageco** [comment]
@gregrickaby i was wondering if SASS was still a part of this package - doesn't look like it. You might want to update the readme to remove Sass from the features: 

_I feature some of the web's most proven technologies like: Tailwind, npm, webpack, Sass, and PostCSS._
