### ISSUE TITLE
Build command breaks on Buddy

### ISSUE THREAD

**Issue by Cheffheid** [WebDevStudios/wd_s#566]
Better late than never :).

I don't know for sure what the best approach would be to fix this, but the setup in package.json is breaking our Buddy deploys. And so this is definitely an internal WDS issue, but anyone that uses Buddy (or a deploy tool that works similarly, with a separation between Node and PHP environments) will run into this.

## The problem ##
Right now, to build everything you can simply run `npm run build`. This will build all of the CSS, JavaScript, images, and translation files, but as a result it will also make the assumption that you have PHP and WP CLI installed on your build environment.

This will work perfectly when you do it on a local environment, but on Buddy the environment your action runs on is either Node or PHP enabled and so it _cannot_ do both of those things in the same action unless you _also_ manually install Node or PHP on that action's environment. This is super clunky and difficult to maintain.

## Possible solutions ##
So, the way I see it there are two ways to fix this. 

The first one is what I ended up doing on the project I ran into these issues with and it's to take `theme:pot` out of the general `theme` Node command and added a separate step in Buddy's deploy pipeline to build the POT file before deploying by running the same WP CLI command that `theme:pot` runs (since this environment doesn't have node, running commands from package.json is essentially out of the question).

What this does do, however, is break the "one command to build _all the things_" philosophy. And so the alternative, which is more of a compromise for that and probably the way we should go here, is to have a second node command (`npm run build:buddy` or `npm run build:node` or whatever) that will only build all the Node-buildable assets and leave the current commands alone. Obviously, this can also be reversed where `npm run build` will be the command that builds the Node-buildable assets and we add a `npm run build:all` or something that also builds POT files. I have no strong opinion either way :).

In either scenario we'll need to update the project template in Buddy to match whichever route we end up going here, but I figure this ticket can serve as the impetus for that change :).

**Comment by jrfoell** [comment]
I want to 2nd this as I just encountered it on a new project. In buddy it will require an additional (PHP w/ WP-CLI) pipeline to build the pot files.

Since it's a public project I'd advocate for having `npm run build` do _all the things_, and then use @Cheffheid's suggestion of a `npm run build:node` option for us to use in Buddy.

**Comment by coreymcollins** [comment]
Right, we need to fix this in the theme but we also need to change our Buddy workflow which is out of my hands. If you want to schedule a time to chat tomorrow with everyone who needs to be involved (i.e., the folks who will be making any needed changes to Buddy) then we can get a plan together for this.

We don't want to push a change to the theme before we have a plan in place to also update Buddy.

**Comment by jrfoell** [comment]
I've already got the additional build steps added to Buddy, but I'm game to talk through them to see if we can simplify it further. I'll set up a meeting.
