### ISSUE TITLE
Development URL replacement

### ISSUE THREAD

**Issue by tiborp** [WebDevStudios/wd_s#567]
Hi,

Great to see wd_s is using Tailwind now! I cloned the theme to my local environment, but a search for _s.test only finds it in the readme file. So now I am wondering where to set the development URL.

Hope someone can point me in the right direction.

Thanks!

**Comment by coreymcollins** [comment]
We don't specify or set the development URL in any of our scripts at this point, but I do see that it's still referenced in the README file. I'll go ahead and remove that to clear up the confusion there. You should be able to use the theme with whatever local development setup (Local, MAMP, etc.) you're running without having to specify any development URL in the theme.

Thanks for bringing this to our attention, and thanks for using the theme!

**Comment by tiborp** [comment]
Hi Corey,

Thanks! Makes sense I couldn't find it then ;-)

Next question would be what URL is being used when running `npm run start`

I am not a webpack wizzard, so maybe this is a newby-question, but I was expecting a browser window to open, with an URL like localhost:3000, where I would see changes live reloading.

Using Local (5.9.8) for local development.

**Comment by tiborp** [comment]
Solved; since it is using Live Reload, it a matter of using the browser extension for this, on the normal URL. I was just so used to using browserSync for this :-)
