### ISSUE TITLE
Some observations on the dev workflow

### ISSUE THREAD

**Issue by tiborp** [WebDevStudios/wd_s#568]
After playing around a bit with the new setup in wd_s (I have been using the older Gulp-version for quite some time), there are a few things I would like to share with you. First of all: I really like the idea using a Tailwind based theme, and I think you did a great job so far!

But...

I noticed that no live reload is triggered when making changes to template files, which I found quite surprising. Maybe I am missing something, so please correct me if I am doing it wrong :-)

Consider the following scenario: I add a Tailwind class to an element; let's say `ml-10`, to the site-description paragraph in `header.php`. What I would expect to happen, is a refresh in my browser screen that would show the result of those changes.

As far as I can see now, to see the result of my changes I have to first manually refresh my browser AND, unless I did add a class name that is already present in the compiled stylesheet, I also have to stop and then  re-run `npm run start `, so the newly added class is also present the stylesheet. That seems a bit tedious to me.

Another thing is the time it takes to run the tasks and refresh the browser: I am using the LiveReload extension in Chrome, and it takes 6-8 seconds for a small change in a .scss file to show up in my browser screen. Being used to see my changes in around 1 second, this feels like a very long time :-S

Hope I am doing it wrong :-)

Cheers, Tibor

**Comment by coreymcollins** [comment]
Thanks for the feedback! Stuff like this is always good to get from folks outside of the WDS circle so we can see where we can improve. We'll take a look at what you've mentioned and keep you posted on where we go next.

Thanks!
