### ISSUE TITLE
Body background is never set

### ISSUE THREAD

**Issue by pmgarman** [WebDevStudios/wd_s#58]
This, I can't find anywhere in the codebase. I also am not 100% sure where it would be prefered to be at. It's not really "layout" and not really a "module" ... `body` styles are pretty much in "normalize" which I don't really feel right at putting it in either.

```
body {
    background: $color-background-body;
}
```

Noticed this when using the customizer, you get a gray background from the customizer behind the iframe because no background is set within the theme itself.

**Comment by gregrickaby** [comment]
That's a great question. I used to be in _typography.scss, on line 5. 

I'm putting it in normalize because it makes the most sense (to me).

**Comment by gregrickaby** [comment]
Fixed (and I used the wrong ticket number... sigh) https://github.com/WebDevStudios/wd_s/commit/a8dce059abc80753e219bccfbe273e6ba3cd7472
