### ISSUE TITLE
sprite.svg not generated during npm run start

### ISSUE THREAD

**Issue by coreymcollins** [WebDevStudios/wd_s#583]
When you first run `npm i`, the `sprite.svg` file will get created which is important for using the `display_svg` functions.

When you run `npm run start`, the `sprite.svg` file is cleared out and does not get recreated at any point. If you add or modify an SVG in the `src/images/icons` directory, that file will be added to/updated in the `build` directory, but the `sprite.svg` file is not generated.

We need to make sure the `sprite.svg` file is generated during `npm run start` so while actively developing so the sprite file is generated without having to stop the process and run `npm run build`.

**Comment by aubreypwd** [comment]
I'll try and look at this tomorrow :D

**Comment by aubreypwd** [comment]
I have a PR for a fix for this ⏫

**Comment by coreymcollins** [comment]
Closed by #587
