### ISSUE TITLE
Document npm & composer scripts

### ISSUE THREAD

**Issue by bradp** [WebDevStudios/wd_s#602]
The number of npm and composer scripts has grown quite a bit, but the README still only references `build` & `run`.

It would be super helpful to have all these documented, either in a table at the end of README, similar to https://github.com/bradp/pears#%EF%B8%8F-usage or potentially a second markdown file with the commands. 

I'd suggest against using the GH wiki for it, as someone using this might want to customize the scripts, and if we have them documented in a file being tracked, they can edit that.

**Comment by bradp** [comment]
I'm happy to write these up, just a matter of where we want this to live. I think in the README is the best place, because it also shows at a glance all the benefits of these scripts are.

@coreymcollins Thoughts?

**Comment by coreymcollins** [comment]
Yeah, I have no problem having those written up in more detail. We have them in both the README and Wiki, so I'm fine with you updating the README if you'd like and then we can just copy & paste to the Wiki to keep that aligned.

Thanks!
