### ISSUE TITLE
Idea: Simplification & organization of the SCSS

### ISSUE THREAD

**Issue by oliverharrison** [WebDevStudios/wd_s#616]
The SCSS should be organized so that it is easier to understand what each partial is styling. Additionally, it should be scoped better to not have global styles override block styling.

**Comment by gregrickaby** [comment]
Something Lisa and I are talking about is a shift to the [Atomic Design](https://bradfrost.com/blog/post/atomic-web-design/) methodology. This would apply to not only our designs, but file organization/structure and building blocks/themes.

Here's how the file organization could look in wd_s:

```bash
sass/
├─ atoms/
│  ├─ _buttons.scss
│  ├─ _images.scss
│  ├─ _headings.scss
│  ├─ index.scss
├─ molecules/
│  ├─ _card.scss
│  ├─ _comments.scss
│  ├─ _forms.scss
│  ├─ index.scss
├─ organisms/
│  ├─ _block-two-column.scss
│  ├─ _footer.scss
│  ├─ _header.scss
│  ├─ index.scss
├─ templates/
│  ├─ _contact.scss
│  ├─ _homepage.scss
│  ├─ index.scss

```

Thoughts?

**Comment by coreymcollins** [comment]
I think Oliver & Amor had started work on this last 5FTF, and looking at Oliver's branch it looks like some of this might be underway. Might be good to chat through this either on FEE Scrum or a call with Oliver & Amor to see where things stand currently and where we can delegate some tasks here.

Oliver's branch currently contains some other template changes outside of Sass and JS, so it might be best to break those out into their own branches so we can focus our branches on specific feature sets.

I'm always up for a change if it's going to make for a better process and experience for y'all!
