### ISSUE TITLE
Idea: `/components` folder should be renamed to `/js`

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#621]
We have a folder named `/scss` but our JavaScript is named `/components` and it's confusing.

I'd like to propose the following:

```bash

js/
├─ components/
│  ├─ accordion.js
│  ├─ mobile-menu.js
│  ├─ modal.js
│  ├─ navigation-primary.js
│  ├─ etc...
├─ utility/
│  ├─ js-enabled.js
│  ├─ skip-link-focus.js
│  ├─ window-ready.js
│  ├─ etc...
```

Thoughts?

**Comment by coreymcollins** [comment]
Same comments as on #616 – it looks like Oliver started some of this work in his branch already, so some of this work may already be underway. We may just want to break it out into its own JS-focused branch unless it makes sense to do all of the Sass and JS structure together?
