### ISSUE TITLE
How to split styles and scripts of a project into multiple files?

### ISSUE THREAD

**Issue by nicktoot** [WebDevStudios/wd_s#626]
Hello everyone 👋

I really like the wd_s theme, it's an awesome contribution for the WordPress community.

But I cannot make it so that in the output to create several CSS and JS files, instead of one index.css and one index.js.
For example, to create separate style files for gutenberg blocks or to style something in the admin area.
I understand that the wd_s uses the default webpack config from the WordPress folder in the node_modules (@wordpress/scripts/config/webpack.config), so I cannot change the settings of the input and output files.

Can you please tell me if there is a possibility of splitting files in wd_s?

How can I do this in order to continue using all the features of the theme?

Many thanks in advance to everyone for their help and participation! 🙏

**Comment by belovdigital** [comment]
Hi guys. The same question here. We just need to find a simple way to have something like this (example):
- global.scss
- blocks.scss
- ...

and in built get 
- global.css
- blocks.css (that we can add conditionally to specific pages or blocks)
- ...

**Comment by coreymcollins** [comment]
Hey y'all!

wd_s uses wp-scripts, so anything you can do in wp-scripts can be done in wd_s.

For instance, if you wanted to specify multiple input points for your `build` and `start` scripts, you can do so as detailed here:
- [Custom Build Script](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#build)
- [Custom Start Script](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#start)

Out of the box, our theme utilizes a single entry point but you're free to customize and extend the theme and package file to your needs and your project.
