### ISSUE TITLE
npm run build and npm run start error: the system cannot find the path specified

### ISSUE THREAD

**Issue by ivansidorov35** [WebDevStudios/wd_s#627]
Hello, i have an issue, when i try to build my project on Windows 10. In the end i see an error: the system cannot find the path specified. There's complete log file when i enter "npm install".
![Screenshot_6](https://user-images.githubusercontent.com/81721245/114016369-6cdcc200-9873-11eb-8b27-8e6d21b86d53.png)
[2021-04-08T10_53_27_746Z-debug.log](https://github.com/WebDevStudios/wd_s/files/6278114/2021-04-08T10_53_27_746Z-debug.log)

But when I change in package.json in scripts - "build": "**wds-build** && npm run theme" to "build": "**wp-scripts build** && npm run theme" everything goes ok.

**Comment by coreymcollins** [comment]
Hey @ivansidorov35 – we just pushed some updates to wd_s that change our workflow quite a bit, including relying more on `wp-scripts` out of the box rather than our own solution. Could you give the updated `main` branch a test and see if you're still running into this issue?

Thanks!
