### ISSUE TITLE
WP CLI is an undocumented dependency

### ISSUE THREAD

**Issue by salcode** [WebDevStudios/wd_s#629]
When I ran `npm i`, the install failed because I don't have WP CLI installed.

![image](https://user-images.githubusercontent.com/5194588/114765489-36032200-9d33-11eb-9d9b-4a1282c51397.png)

Perhaps we could list a `Prerequisites` section and document WP CLI is required.

**Comment by gregrickaby** [comment]
@salcode Thank you. I added it to the list in https://github.com/WebDevStudios/wd_s/commit/d609e552b38b73982fff7a3de6b3818f985b8f89. Hopefully, we'll #618 merged in early next week. 👍🏻
