### ISSUE TITLE
Search button

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#63]
It's terrible out of the box because it's 300x300 or something.

**Comment by gregrickaby** [comment]
How does everyone feel about just dropping the default form styles? I did this today for my WDSCamp presentation, and the WP-API search form was basically naked - and looked fantastic.

**Comment by coreymcollins** [comment]
Updated in this pull request encompassing basic form elements: https://github.com/WebDevStudios/wd_s/pull/78

Should be good to close this out, unless there's anything specific to the search button we want to adjust here.

**Comment by gregrickaby** [comment]
:+1:
