### ISSUE TITLE
wdunderscores.com issues

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#643]
The generator is not finding/replacing all the things. See https://github.com/WebDevStudios/wd_s-generator

**Comment by coreymcollins** [comment]
Should this be an issue here or in the generator repo?

**Comment by gregrickaby** [comment]
I added it here for visibility, but yes, it should be in the generator repo. See https://github.com/WebDevStudios/wd_s-generator/issues/12

**Comment by gregrickaby** [comment]
Mico is jumping on this. Closing here!
