### ISSUE TITLE
Theme zip generated with your wd_s generator gives a warning

### ISSUE THREAD

**Issue by Manu-W** [WebDevStudios/wd_s#663]
I have an issue with your theme and I'm sorry if this is not the right place to ask for help, but I don't know where else to post this:

I used your wd_s Theme Generator to create a zip for me. When I activate that theme in my local wordpress installation I get the following warning (file paths shortened):

**Warning: include(............\inc/../build/index.asset.php): failed to open stream: No such file or directory in ...........\inc\scripts.php on line 34
Warning: include(): Failed opening '........\inc/../build/index.asset.php' for inclusion (include_path='......\Xampp\php\PEAR') in .......\inc\scripts.php on line 34**

This "'/../build/index.asset.php'" does not exist in my zip file.
How can i fix this?

**Comment by donmhico** [comment]
Hello @Manu-W,

It seems like you haven't perform the build process for the theme. Have you tried performing the [Installation steps](https://github.com/WebDevStudios/wd_s#installation)?

After your install the theme dependencies, run the build command
```
npm run build
```

**Comment by Manu-W** [comment]
Thank you. I got it running now.

But may I suggest to rewrite this:
If you want to keep it simple, head over to https://wdunderscores.com and generate your wd_s based theme from there. You just input the name of the theme you want to create, **click the "Generate" button, and you get your ready-to-awesomize starter theme**.

I thought I would not need to do all the other things  O.o

**Comment by coreymcollins** [comment]
The theme generator and installation/setup are two different steps (https://github.com/WebDevStudios/wd_s#getting-started and https://github.com/WebDevStudios/wd_s#installation), so you still need to run `build` whether you're manually replacing all of the `_s` strings or using the generator.
