### ISSUE TITLE
ERROR in Cannot read property 'sync' of undefined Occurred while linting index.js:4

### ISSUE THREAD

**Issue by belovdigital** [WebDevStudios/wd_s#724]
Hi! We use your framework intensively, thank you.
But after the latest update npm run build gives the following error:

ERROR in Cannot read property 'sync' of undefined
Occurred while lifting /home/xxxxx/xxxxx..dev/public/wp-content/themes/xxxxxx/src/index.js:4

details - https://belovdigital.d.pr/KxH210

We used npm i --legacy-peer-deps to install npm, of course. 
NPM 7+ version
Node 14+

**Comment by coreymcollins** [comment]
Hey @belovdigital – I'm unable to replicate this myself, but I'll run it past the team to see if anyone else can replicate or has run into it in the past.

For reference, I'm running npm 7.10.0 and Node 14.16.1.

**Comment by belovdigital** [comment]
Thanks. 
What does this part mean in index.js (eslint commented part)?

/* eslint eslint-comments/disable-enable-pair: error */
/* eslint-disable no-undef, no-unused-vars */

import './scss/tailwind.scss';
import './scss/index.scss';
import './js/index';

/* eslint-enable no-undef, no-unused-vars */

**Comment by coreymcollins** [comment]
Those comments were to get around some previous ESLint warnings being thrown, but it looks like those don't get thrown anymore so we may actually be able to remove those. They shouldn't have an affect on any build scripts or anything, though.

**Comment by belovdigital** [comment]
Alright, some progress here. I was able to install some missing dependencies manually based on WARN messages during the npm install.
Now the next problem is a lot of ERRORS from styles - https://belovdigital.d.pr/8nD213
How to disable that?

**Comment by belovdigital** [comment]
Fixed with the following:

npm run lint:css -- --fix
npm run lint:js -- --fix
npm run build

What a crazy day though

**Comment by rossberenson** [comment]
I ran into this issue as well. To solve it, I installed prettier separately.
