### ISSUE TITLE
Scaffolding Template fix

### ISSUE THREAD

**Issue by khleomix** [WebDevStudios/wd_s#747]
The scaffolding template is currently not working the way it's supposed to work.

Things to do:
- Update accordion markup.
- Add tailwind classes to work with the scaffolding template.

![Scaffolding-–-Site-Title](https://user-images.githubusercontent.com/1948204/134683901-4c9dcdbe-5b6c-4360-8514-de28d0a2ea6e.jpg)

**Comment by coreymcollins** [comment]
@khleomix – I know you started work on this on a branch a while back. Is that work still in progress or is it ready for a PR?

**Comment by khleomix** [comment]
@coreymcollins not yet, will need to update this with latest `main`. Will check on this soon. Thanks!

**Comment by khleomix** [comment]
@coreymcollins All done and ready for you to review.
