### ISSUE TITLE
Reorganize the inc/ directory

### ISSUE THREAD

**Issue by batesweb** [WebDevStudios/wd_s#764]
I would like to suggest a more organized file structure for the `inc/` directory. The current file structure is not intuitive and can lead to very disorganized code by the end of a large project (e.g. declaring functions in `template-tags.php` which are not really template tags). 

I would propose switching to a more fool-proof layout which I have seen used in various applications and have been using for years in my own starter theme. It is also more consistent with how we are organizing our JS/SCSS files.

Primarily, this would involve breaking out each function into its own file (named identically to the function name) and grouping them in directories by their functionality/purpose. While this would result in more files being created, it would make locating a function much simpler and also mitigate merge conflicts in files that would otherwise be updated constantly (e.g. 5 people working on functions in `template-tags.php` simultaneously).

For example, instead of having a single `template-tags.php` file (have I mentioned this file before?) with 30 function declarations, you would have an `inc/template-tags/` directory with 30 individual files, each housing a single function.

I would propose the following structure for the `inc/` directory:

```text
inc/
└─── customizer/    (functions relating to the theme customizer)
          └─── demo-function.php
          └─── another-demo-function.php
          └─── yet-another-demo-function.php
└─── functions/     (general functions that don't fit into any other directory)
└─── hooks/         (theme hooks)
└─── post-types/    (theme post type registrations & functions)
└─── scaffolding/   (theme scaffolding functions)
└─── setup/         (functions relating to the theme setup)
└─── shortcodes/    (shortcode registrations)
└─── template-tags/ (functions that render markup for use in theme templates)
└─── README.md
```

I would also propose an update to `functions.php` to make including all of these files hands-off (almost). Instead of explicitly including each individual file, we could utilize the `glob()` function to loop through each directory and automatically include all `.php` files in the directory.

The updated `functions.php` would look something like this:

```
function _s_get_theme_include_files() {
	return [
		'inc/customizer/', // Customizer additions.
		'inc/functions/', // Custom functions that act independently of the theme templates.
		'inc/hooks/', // Load custom filters and hooks.
		'inc/post-types/', // Load custom post types.
		'inc/scaffolding/', // Scaffolding.
		'inc/setup/', // Theme setup.
		'inc/shortcodes/', // Load shortcodes.
		'inc/template-tags/', // Custom template tags for this theme.
	];
}

foreach ( _s_get_theme_include_files() as $include ) {
	$include = trailingslashit( get_template_directory() ) . $include;

	// Allows inclusion of individual files or all .php files in a directory.
	if ( is_dir( $include ) ) {
		foreach ( glob( $include . '*.php' ) as $file ) {
			require $file;
		}
	} else {
		require $include;
	}
}
```

**Comment by oliverharrison** [comment]
Closed by #769
