### ISSUE TITLE
Disable the default 'full screen' view on pages and posts using the Gutenberg editor

### ISSUE THREAD

**Issue by oliverharrison** [WebDevStudios/wd_s#766]
As per the title; by default since WordPress 5.4, the admin editor will open into a 'full screen' view when editing posts or pages with the Gutenberg editor. 

Most developers do not use this view and it can be annoying and distracting to have to close it every time a session is restarted in the browser.

**Comment by batesweb** [comment]
We decided to set this up as a plugin instead of integrating it into the theme. See plugin repo below:

https://github.com/WebDevStudios/wds-disable-annoyances
