### ISSUE TITLE
Problem while loading Google Fonts

### ISSUE THREAD

**Issue by sdelon** [WebDevStudios/wd_s#784]
Hi all,

I have an issue with Google Fonts. When the site loads, at the very first seconds, it displays the right fonts, but as soon as it is fully loaded, the fallback fonts (system-ui) display in place. 

I have added this enqueue style line in the `inc/scripts` file :

`
function add_google_fonts() {
    wp_enqueue_style( 'fonts_lora_poppins', 'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,500;1,500&family=Poppins:ital,wght@0,200;0,400;0,700;0,900;1,200;1,400;1,700;1,900&display=swap', false );
}

add_action( 'wp_enqueue_scripts', 'add_google_fonts' );
`
and in my tailwind config file in the extend theme part :

`
fontFamily: {
 sans: ["'Poppins'", ...defaultTheme.fontFamily.sans],
 serif: ["'Lora'", ...defaultTheme.fontFamily.serif]
}
`

Do I need to add something more or do something different for the fonts to correctly load ? 
Thanks for your help,
Stephanie

**Comment by coreymcollins** [comment]
Can you provide your full Tailwind config file? You're using `...defaultTheme.` here which we aren't using in our config, and I'm curious about the differences between our two configs and where the issue may be coming up.

Thanks!

**Comment by sdelon** [comment]
Hi Corey, thanks for getting back to me. As for the defaultTheme, it is usually how i set up fonts when working with Tailwind in JS frameworks as it is recommended in this tailwind Labs video : https://www.youtube.com/watch?v=sOnBG2wUm1s&t=388s (at 6'16). It might be different in this specific WP configuration. Here is the full Tailwind config file :

`const defaultTheme = require('tailwindcss/defaultTheme')
const plugin = require( 'tailwindcss/plugin' );

module.exports = {
  mode: 'jit',
  purge: {
    content: [ './**/*.php', './src/js/**/*.js' ],
		layers: [ 'utilities' ],
		mode: 'layers',
  },
  darkMode: false,
  theme: {
    container: {
      padding: {
          DEFAULT: '1rem',
          sm: '1rem',
          lg: '1rem'
      }
    },
    extend: {
        colors: {
          "dark-gray" : "#303436",
          "mid-gray" : "#6B6C6A",
          "light-gray" : "#FAF7FB",
          "lavender" : "#78686F",
          "light-blue" :"#9CC4B2",
          "pink" : "#D5BBB1",
          "rainbow-green" : "#2CC094",
          "rainbow-blue" : "#6D89A6",
          "rainbow-yellow" : "#ECC369",
          "rainbow-orange" : "#E5764A",
          "rainbow-red" : "#EC5261",
        },
        fontFamily: {
          sans: ["'Poppins'", ...defaultTheme.fontFamily.sans],
          serif: ["'Lora'", ...defaultTheme.fontFamily.serif]
        }
    },
  },
  variants: {
    entend: {}
  },
  plugins: [
    plugin( function ( { addComponents, config } ) {
			const screenReaderText = {
				'.screen-reader-text': {
					clip: 'rect(1px, 1px, 1px, 1px)',
					height: '1px',
					overflow: 'hidden',
					position: 'absolute',
					whiteSpace: 'nowrap',
					width: '1px',
					'&:hover,&:active,&:focus': {
						backgroundColor: config( 'theme.colors.black' ),
						clip: 'auto',
						color: config( 'theme.colors.white' ),
						display: 'block',
						fontSize: config( 'theme.fontSize.base' ),
						fontWeight: config( 'theme.fontWeight.medium' ),
						height: 'auto',
						left: '5px',
						lineHeight: 'normal',
						padding: config( 'theme.spacing.8' ),
						textDecoration: 'none',
						top: '5px',
						width: 'auto',
						zIndex: '100000',
					},
				},
			}
      addComponents( screenReaderText, {
				variants: [ 'hover', 'active', 'focus' ],
			});
    })
  ],
}
`

Thanks a lot !

**Comment by coreymcollins** [comment]
I did a quick test this morning with our theme's Tailwind config file and things seem to be working. When I add your fonts to the config + enqueue, I do see the new fonts in place:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/954724/141134886-66156182-5c69-4957-bd49-56ed4ab9ec17.png">

I went the route of adding to our config file to test instead of replacing it completely since our theme relies on a lot of classes and styles set in our config, and completely replacing it would throw a handful of errors.

This is the updated version of the config that I used:

```
const defaultTheme = require( 'tailwindcss/defaultTheme' );
const plugin = require( 'tailwindcss/plugin' );

module.exports = {
	purge: {
		content: [ './**/*.php', './src/js/**/*.js' ],
		layers: [ 'utilities' ],
		mode: 'layers',
	},
	theme: {
		fontSize: {
			'root-em': '16px',
			xs: '0.75rem',
			sm: '0.875rem',
			base: '1rem',
			lg: '1.125rem',
			xl: '1.25rem',
			'2xl': '1.375rem',
			'3xl': '1.5rem',
			'4xl': '1.625rem',
			'5xl': '1.75rem',
			'6xl': '1.875rem',
			'heading-xs': '2rem',
			'heading-sm': '2.125rem',
			'heading-md': '2.375rem',
			'heading-lg': '2.625rem',
			'heading-xl': '2.875rem',
		},
		spacing: {
			px: '1px',
			0: '0',
			1: '0.0625rem',
			2: '0.125rem',
			3: '0.1875rem',
			4: '0.25rem',
			5: '0.3125rem',
			6: '0.375rem',
			8: '0.5rem',
			10: '0.625rem',
			12: '0.75rem',
			16: '1rem',
			20: '1.25rem',
			24: '1.5rem',
			32: '2rem',
			40: '2.5rem',
			48: '3rem',
			56: '3.5rem',
			64: '4rem',
			68: '4.25rem',
			72: '4.5rem',
			76: '4.75rem',
			80: '5rem',
			192: '12rem',
		},
		boxShadow: {
			xs: '0 0 0 0.0625rem rgba(0, 0, 0, 0.05)',
			sm: '0 0.0625rem 0.125rem 0 rgba(0, 0, 0, 0.05)',
			default:
				'0 0.0625rem 0.1875rem 0 rgba(0, 0, 0, 0.1), 0 0.0625rem 0.125rem 0 rgba(0, 0, 0, 0.06)',
			md:
				'0 0.25rem 0.375rem -0.0625rem rgba(0, 0, 0, 0.1), 0 0.125rem 0.25rem -0.0625rem rgba(0, 0, 0, 0.06)',
			lg:
				'0 0.625rem 0.9375 -0.1875rem rgba(0, 0, 0, 0.1), 0 0.25rem 0.375rem -0.125rem rgba(0, 0, 0, 0.05)',
			xl:
				'0 1.25rem 1.5625rem -0.3125rem rgba(0, 0, 0, 0.1), 0 0.625rem 0.625rem -0.3125rem rgba(0, 0, 0, 0.04)',
			'2xl': '0 1.5625rem 3.125rem -10.125rem rgba(0, 0, 0, 0.25)',
			'3xl': '0 2.1875rem 3.75rem -0.9375rem rgba(0, 0, 0, 0.3)',
			inner: 'inset 0 0.125rem 0.25rem 0 rgba(0, 0, 0, 0.06)',
			outline: '0 0 0 0.1875rem rgba(66, 153, 225, 0.5)',
			focus: '0 0 0 0.1875rem rgba(66, 153, 225, 0.5)',
			none: 'none',
		},
		screens: {
			phone: '300px',
			'tablet-portrait': '600px',
			'wp-admin-bar': '783px',
			'tablet-landscape': '900px',
			'desktop-min': { min: '1200px' },
			desktop: '1200px',
			'desktop-large': '1600px',
		},
		container: ( theme ) => ( {
			center: true,
			screens: {
				phone: '100%',
				desktop: '1200px',
			},
			padding: {
				DEFAULT: theme( 'spacing.16' ),
				'desktop-large': '0',
			},
		} ),
		extend: {
			backgroundOpacity: {
				10: '0.1',
			},
			fontFamily: {
				sans: [ "'Poppins'", ...defaultTheme.fontFamily.sans ],
				serif: [ "'Lora'", ...defaultTheme.fontFamily.serif ],
			},
		},
	},
	variants: {},
	plugins: [
		plugin( function ( { addBase, config } ) {
			addBase( {
				html: {
					fontSize: '100%',
				},
				'h1,.h1': {
					fontSize: config( 'theme.fontSize.heading-xl' ),
				},
				'h2,.h2': {
					fontSize: config( 'theme.fontSize.heading-lg' ),
				},
				'h3,.h3': {
					fontSize: config( 'theme.fontSize.heading-md' ),
				},
				'h4,.h4': {
					fontSize: config( 'theme.fontSize.heading-sm' ),
				},
				'h5,.h5': {
					fontSize: config( 'theme.fontSize.heading-xs' ),
				},
				'h6,.h6': {
					fontSize: config( 'theme.fontSize.heading-xs' ),
				},
				'h1,h2,h3,h4,h5,h6,.h1,.h2,.h3,.h4,.h5,.h6': {
					marginBottom: config( 'theme.spacing.16' ),
				},
				a: {
					textDecoration: 'underline',
				},
				p: {
					marginBottom: config( 'theme.spacing.16' ),
					'&:last-child': {
						marginBottom: '0',
					},
				},
				'.button': {
					padding: config( 'theme.spacing.16' ),
				},
				'table,dl,ol,ul,address,pre,blockquote,iframe': {
					marginBottom: config( 'theme.spacing.16' ),
				},
				pre: {
					overflow: 'auto',
				},
			} );
		} ),
		plugin( function ( { addComponents, config } ) {
			const screenReaderText = {
				'.screen-reader-text': {
					clip: 'rect(1px, 1px, 1px, 1px)',
					height: '1px',
					overflow: 'hidden',
					position: 'absolute',
					whiteSpace: 'nowrap',
					width: '1px',
					'&:hover,&:active,&:focus': {
						backgroundColor: config( 'theme.colors.black' ),
						clip: 'auto',
						color: config( 'theme.colors.white' ),
						display: 'block',
						fontSize: config( 'theme.fontSize.base' ),
						fontWeight: config( 'theme.fontWeight.medium' ),
						height: 'auto',
						left: '5px',
						lineHeight: 'normal',
						padding: config( 'theme.spacing.8' ),
						textDecoration: 'none',
						top: '5px',
						width: 'auto',
						zIndex: '100000',
					},
				},
			};

			addComponents( screenReaderText, {
				variants: [ 'hover', 'active', 'focus' ],
			} );
		} ),
	],
};
```

I did notice, however, that if I view source and view the URL being enqueued, it's only including Poppins and not Lora:
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/954724/141136629-16608b76-5026-489d-86f7-0c8b04430eb1.png">

I'm wondering if there may be a syntax error in your enqueue?

**Comment by coreymcollins** [comment]
As a quick reference note – we used to include multiple Google fonts like this:

```
function _s_font_url() {

	$fonts_url = '';

	/*
	* Translators: If there are characters in your language that are not
	* supported by the following, translate this to 'off'. Do not translate
	* into your own language.
	*/
	$roboto = _x( 'on', 'Roboto font: on or off', '_s' );
	$open_sans = _x( 'on', 'Open Sans font: on or off', '_s' );

	if ( 'off' !== $roboto || 'off' !== $open_sans ) {
		$font_families = array();

		if ( 'off' !== $roboto ) {
			$font_families[] = 'Roboto:400,700';
		}

		if ( 'off' !== $open_sans ) {
			$font_families[] = 'Open Sans:400,300,700';
		}

		$query_args = array(
			'family' => urlencode( implode( '|', $font_families ) ),
		);

		$fonts_url = add_query_arg( $query_args, '//fonts.googleapis.com/css' );
	}

	return $fonts_url;
}
```

And then enqueue with:
```
wp_enqueue_style( '_s-google-font', _s_font_url(), array(), null );
```

If I try that setup with your fonts, I do in fact get the expected outcome when viewing source in the browser:
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/954724/141142644-06b8deef-8019-4bbd-af45-4e6467d92dc8.png">

**Comment by sdelon** [comment]
Thanks Corey, Indeed with your function to include fonts, both fonts are now loaded as you can see below, but still fonts load only a fraction seconds and then back to the fallback fonts as you can see here : https://watch.screencastify.com/v/FeEQYlV2egLAGjL0HtVi
![Capture d’écran 2021-11-11 071525](https://user-images.githubusercontent.com/53929569/141247586-373392af-49a2-4a8e-90c1-5e9e75717d50.jpg)

**Comment by coreymcollins** [comment]
Thanks for sharing that video – I'll dig into this a bit more this morning and see if I can replicate.

Is there any other markup either in your theme files or partials that would be relevant to know about? Is your theme in a public repo that I could check out, or would you be able to share it so we're both working from and troubleshooting the same codebase?

I'll try and replicate in a fresh wd_s install either way, but the closer we can get to the same code and variables would be great.

Thanks!

**Comment by sdelon** [comment]
Thanks a lot Corey, I have just sent you an invite as it is a private repo.

**Comment by coreymcollins** [comment]
Thanks for the access!

When I checked out your theme, I didn't find any reference to enqueuing the Google fonts.

I added this:
```
function wds_acme_font_url() {

	$fonts_url = '';

	/*
	* Translators: If there are characters in your language that are not
	* supported by the following, translate this to 'off'. Do not translate
	* into your own language.
	*/
	$lora    = _x( 'on', 'Lora font: on or off', '_s' );
	$poppins = _x( 'on', 'Poppins font: on or off', '_s' );

	if ( 'off' !== $lora || 'off' !== $poppins ) {
		$font_families = array();

		if ( 'off' !== $lora ) {
			$font_families[] = 'Lora:ital,wght@0,500;1,500';
		}

		if ( 'off' !== $poppins ) {
			$font_families[] = 'Poppins:ital,wght@0,200;0,400;0,700;0,900;1,200;1,400;1,700;1,900';
		}

		$query_args = array(
			'family' => urlencode( implode( '|', $font_families ) ),
		);

		$fonts_url = add_query_arg( $query_args, '//fonts.googleapis.com/css' );
	}

	return $fonts_url;
}
```

to `/inc/scripts.php`

And then added this to the `wds_acme_scripts` function:
```
wp_enqueue_style( '_s-google-font', wds_acme_font_url(), array( 'wd_s' ), $asset_file['version'] );
```

Then, when I build and refresh the homepage I'm getting the fonts as expected and they don't disappear.

For example, here's a section on the homepage displaying a post. I've enlarged the font size so it's easier to see in the screenshot:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/954724/141493541-2016cc68-7cf5-410a-acce-f3b5916c2d69.png">

Compared to the same string in Google fonts to compare font shapes:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/954724/141493641-6d7ef047-6bc9-4591-86e9-e53776d4080e.png">
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/954724/141493674-ff0015ed-297c-41a5-9853-654921eeca13.png">

I'm not sure if your local is out of sync with what is in your repo, but could you double check that the fonts are being enqueued as noted above?

If they are and you're still seeing the issue, can you let me know how to setup a page like the one in your screencast so I can try to replicate that exact scenario?

Thanks!

**Comment by sdelon** [comment]
Corey, my mistake, I didn't push the latest code version before adding you as a collab on the rep since it wasn't working as expected. But I have just pushed the latest version for you to see which contains the reference to enqueuing the Google fonts and it is the one that doesn't work. But I am sorry, I don't really understand what you mean by "setup a page like the one in the screencast". I have a database containing all posts and so, so I don't really know how I can setup the page. 
Thanks a lot for your help !

**Comment by coreymcollins** [comment]
Thanks! I just wasn't sure if there was anything special I needed to do to setup a section on the homepage to look like that section in your screencast. Without any extra setup other than enabling the theme, my homepage looks like this:
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/954724/141499516-5851951f-366c-4344-be76-9755857d4cca.png">

Is there a spot to set a featured post that can display like the one in your screencast seen here?
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/954724/141499602-e9217f63-de44-4aa0-a4e5-77f7585a9774.png">

**Comment by sdelon** [comment]
Hi Corey, this is getting even stranger since it loads perfectly on certain pages... But since it has nothing to do with wd_s, I won't be taking more of your time on that issue, I'll keep investigating :-) Again thanks a lot for your time and help on that issue !

**Comment by coreymcollins** [comment]
Happy to help, good luck tracking down the issue!
