### ISSUE TITLE
Webpack Asset Modules - SCSS compile error

### ISSUE THREAD

**Issue by rossberenson** [WebDevStudios/wd_s#785]
Sorry to reopen a bug but it is a bug similar to #725 . 

Since the above bug, webpack.config.js has been updated to utilize the latest webpack asset modules. I'm running into an error while trying to use `background-image: url(/images/placeholder.png);` in a scss partial. The same error occurs when trying to use @font-face. I've spent a while debugging and sadly didn't come across a solution. webpack.config.js looks correct based on webpack documentation. Was researching @wordpress-scripts and didn't see an obvious conflict there. 

Basically, in the error below, replace '/images/placeholder.png' with '/fonts/font.woff' or '/images/icons/icon.svg'... you get the idea. Seems like any asset being imported via css causes this issue.

To replicate and to make sure it wasn't me. It very well still could be. I did a clean install of wordpress and a clean wd_s. 

I then went to the global/global.scss and added `.site-main {
	background-image: url(/images/placeholder.png);
}
`.

I made sure this partial was being imported in `index.scss`. 

The error I get is this:
```
cached modules 16 KiB (javascript) 5.25 MiB (css/mini-extract) 997 bytes (runtime) [cached] 21 modules
./src/scss/index.scss 39 bytes [built] [1 error]

ERROR in ./src/scss/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve '/images/placeholder.png' in '/Users/username/Sites/test.local/wp-content/themes/test/src/scss'
    at /Users/username/Sites/test.local/wp-content/themes/test/node_modules/webpack/lib/Compilation.js:1773:28
    at /Users/username/Sites/test.local/wp-content/themes/test/node_modules/webpack/lib/NormalModuleFactory.js:811:13
    at eval (eval at create (/Users/username/Sites/test.local/wp-content/themes/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/username/Sites/test.local/wp-content/themes/test/node_modules/webpack/lib/NormalModuleFactory.js:286:22
    at eval (eval at create (/Users/username/Sites/test.local/wp-content/themes/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/username/Sites/test.local/wp-content/themes/test/node_modules/webpack/lib/NormalModuleFactory.js:442:22
    at /Users/username/Sites/test.local/wp-content/themes/test/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/username/Sites/test.local/wp-content/themes/test/node_modules/webpack/lib/NormalModuleFactory.js:673:25
    at /Users/username/Sites/test.local/wp-content/themes/test/node_modules/webpack/lib/NormalModuleFactory.js:882:8
    at /Users/username/Sites/test.local/wp-content/themes/test/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
 @ ./src/index.js 5:0-27

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.51.1 compiled with 2 errors in 304 ms
[Browsersync] Reloading Browsers...
```

Any help would be appreciated.

**Comment by coreymcollins** [comment]
I think the problem in this case may be your syntax.

You're doing this in the partial:

```background-image: url( /images/placeholder.png );```

And that _does_ give me the same error.

However, it's because it's looking for the image in the wrong directory. What you need is:

```background-image: url( ../images/placeholder.png );```

Which will look up one directory into `src`, then find the `images` folder.

This did highlight that some of the partials aren't being imported, though, so I'm going to throw a fix in for that real quick.

Let me know if this resolves your issue when you get a chance – thanks!

**Comment by rossberenson** [comment]
Hi @coreymcollins,

Thanks for taking a look. Sometimes you miss the obvious staring at code for a while. I did add the `../` and sadly that did not solve the issue for me. I'm still encountering an error. Although, a different error. 

```ERROR in ./src/scss/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Users/rossberenson/Sites/cs-uc.local/wp-content/themes/wd_s-main/node_modules/webpack/lib/NormalModule.js:469:19)
    at /Users/rossberenson/Sites/cs-uc.local/wp-content/themes/wd_s-main/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/rossberenson/Sites/cs-uc.local/wp-content/themes/wd_s-main/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/rossberenson/Sites/cs-uc.local/wp-content/themes/wd_s-main/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/rossberenson/Sites/cs-uc.local/wp-content/themes/wd_s-main/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /Users/rossberenson/Sites/cs-uc.local/wp-content/themes/wd_s-main/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /Users/rossberenson/Sites/cs-uc.local/wp-content/themes/wd_s-main/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
 @ ./src/index.js 5:0-27
```
There are no hidden characters that I can find. Removing the `background-image: url(../images/placeholder.png);` solves the _this_ issue but is not an overall solution. haha. 

I tried a few different versions of node as well. Results do not differ.

**Comment by coreymcollins** [comment]
Interesting. You mentioned you tried different versions of node – are you running & testing with the minimum versions of node and npm noted in the readme?

Did you copy and paste the background image string from Github here? It's probably a long-shot since it doesn't _look_ like it's telling you the error initiates there, but I'm curious if maybe some sort of copy/paste weirdness could be to blame.

If that doesn't work, could you try deleting `node_modules` and running a fresh `npm install`?

**Comment by rossberenson** [comment]
So, I actually did do a clean install of the theme and npm modules. I am running node 14.18.1, npm 8.1.3.

I did not copy and paste. I typed it out, myself.

**Comment by coreymcollins** [comment]
Thanks for the info – I can't replicate this myself, but I'll run it by our team to see if anyone else can. Hopefully we can nail down what's causing this issue for you!

**Comment by rossberenson** [comment]
Thanks! I'll keep debugging on my end too. It's really strange.

**Comment by coreymcollins** [comment]
Have you modified any of the rest of the theme code? If so, would you be able to share your theme code? I'm still unable to replicate this on my own with a clean install of wd_s, and I'm wondering if there may be something else we may be missing by not troubleshooting with the same exact code.

Are you getting the error whenever you use any of our various build scripts? `build`, `start`, and `watch`? 

For me, I'm able to set a background images as either the `placeholder.png` file from `/src/images` as well as any SVG from `/src/images/icons` without an error.

**Comment by rossberenson** [comment]
I just did a clean install of WordPress and the wd_s theme. Using an image or svg as a background does not break the build.

Comparing the package.json, I noticed `@wordpress/scripts` has been updated. I wonder if that was the issue?  

Regarding `@font-face`, seems like when the site is built, there is a hash appended to the font file name. I did not notice this the first time around. Editing `webpack.config.js` to remove the hash, since I don't have the hash specified in the css that imports the fonts via `@font-face`. It's now `fonts/[name][ext]`. Thought this would solve that issue but alas it does not. Keep getting an error saying `Module not found: Error: Can't resolve '../fonts/fontname.woff2' in '/Users/username/Sites/wds-test.local/wp-content/themes/wds-test/src/scss/index'`.

I added a `_fonts.scss` in the global directory. That's where I was testing `@font-face`. The font directory does exist the fonts.

I tried using a .css instead of .scss for all the `@font-face`, and that does work. The relative urls specified match up. This leads me to believe there is some sort of compiling error somewhere. Still hunting.

**Comment by rossberenson** [comment]
Heh, I just got it working by doing this: 
```
@font-face {
	font-family: 'HCo Gotham Narrow SSm';
	src:url(../../build/fonts/GothamNarrSSm-XLightItalic_Web.woff2) format('woff2'),
		url(../../build/fonts/GothamNarrSSm-XLightItalic_Web.woff) format('woff');
	font-weight: 200;
	font-style: italic;
}
```

Not the prettiest but it compiles and the compiled css shows:
```
@font-face{
    font-family: HCo Gotham Narrow SSm;
    font-style:normal;
    font-weight:200;
    src:url(fonts/GothamNarrSSm-XLight_Web.woff2) format("woff2"),
    url(fonts/GothamNarrSSm-XLight_Web.woff) format("woff")
 }
```

**Comment by coreymcollins** [comment]
Could you do me a favor and add this to `CopyPlugin` in `webpack.config.js`?
```
{
    from: '**/*.{woff,woff2,eot,ttf,otf}',
    to: 'fonts/[path][name].[ext]',
    context: path.resolve( process.cwd(), 'src/fonts' ),
},
```

And then in your `@font-face` declaration, use this instead:
```
src:url(../fonts/GothamNarrSSm-XLightItalic_Web.woff2) format('woff2'),
url(../fonts/GothamNarrSSm-XLightItalic_Web.woff) format('woff');
```

In testing the fonts here, I was noticing that the fonts weren't being copied to `build`, which they previously were. In looking at a recent project, I'm seeing the above `CopyPlugin` pattern in place but it's not in the current version of wd_s. It may have been removed in error and be part of what's causing the problem here.

**Comment by rossberenson** [comment]
I noticed the fonts didn't copy over, so I manually did for testing purposes. My other project, was copying the fonts. (Has an older wd_s setup)

Anywho, copying does work but updating `@font-face` does not.

`ModuleNotFoundError: Module not found: Error: Can't resolve '../fonts/GothamNarrSSm-XLight_Web.woff2' in '/Users/username/Sites/wds-test.local/wp-content/themes/wds-test/src/scss'`

`../../build/fonts/GothamNarrSSm-XLight_Web.woff2` does still work though.

**Comment by coreymcollins** [comment]
Can you maybe share your directory setup? Is your `fonts` folder directly inside `scss`?

I'm curious, because your error says it can't find the font in `src/scss` but I would imagine the fonts would be in `src/fonts`?

**Comment by rossberenson** [comment]
btw, I think for the CopyPlugin, the to should be `to: 'fonts/[path][name][ext]',`. 

My `fonts` folder is directly inside `src`. When the site is built, it's directly under `build`.

<img width="235" alt="Screen Shot 2021-11-12 at 2 23 03 PM" src="https://user-images.githubusercontent.com/2307364/141523307-610e3489-3f08-4d45-8bf7-8c18728caa47.png">

**Comment by rossberenson** [comment]
Closing VSCode and reopening and restarting seemed to solve this issue. I can now use:
```
@font-face {
	font-family: 'HCo Gotham Narrow SSm';
	src:url(../fonts/GothamNarrSSm-XLight_Web.woff2) format('woff2'),
		url(../fonts/GothamNarrSSm-XLight_Web.woff) format('woff');
	font-weight: 200;
	font-style: normal;
}
```

Without issue. This wasn't the first time I tried the ol' unplug and replug method but for some reason, this time it took.

**Comment by coreymcollins** [comment]
A good call on the path - I think the older version of webpack I grabbed that snippet from required the `.` before `[ext]` but we no longer need that.

Oh, weird about VSCode! I'm glad you were able to resolve that, at least, and that we didn't just spend the next 8 years trying to troubleshoot this thing 😅

I'm going to throw together a PR to get that CopyPlugin pattern back in place, but otherwise let me know if there's anything else to try and nail down here. If not, we should be able to close out the issue.

Appreciate you taking the time to work with me to try and squash this stuff!

**Comment by rossberenson** [comment]
It takes a team! Thanks for your help!
