### ISSUE TITLE
@apply errors while using npm run watch after clean install

### ISSUE THREAD

**Issue by JaketheYeti** [WebDevStudios/wd_s#788]
Hi all,
For some reason some tailwind classes don't seem to be able to be applied with @apply. 
I had them working in a Roots/Sage instance using Tailwind, but doesn't seem to work in this wd_s.

Other classes seem to work, but two specific ones I've encountered so far:

@apply shadow;
@apply max-w-screen-lg;

I've downloaded a version from the wd_s generator website, as well as cloned the repo to a local development.
In the /src/scss/templates/_header.scss I add 'shadow' to the site-header @apply rule

Error:
The `shadow` class does not exist. If you're sure that `shadow` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

I have not changed any other file.

**Comment by coreymcollins** [comment]
We're defining our own values for shadow, so you'd need to use one of these options:
```
boxShadow: {
    xs: '0 0 0 0.0625rem rgba(0, 0, 0, 0.05)',
    sm: '0 0.0625rem 0.125rem 0 rgba(0, 0, 0, 0.05)',
    default:
        '0 0.0625rem 0.1875rem 0 rgba(0, 0, 0, 0.1), 0 0.0625rem 0.125rem 0 rgba(0, 0, 0, 0.06)',
    md:
        '0 0.25rem 0.375rem -0.0625rem rgba(0, 0, 0, 0.1), 0 0.125rem 0.25rem -0.0625rem rgba(0, 0, 0, 0.06)',
    lg:
        '0 0.625rem 0.9375 -0.1875rem rgba(0, 0, 0, 0.1), 0 0.25rem 0.375rem -0.125rem rgba(0, 0, 0, 0.05)',
    xl:
        '0 1.25rem 1.5625rem -0.3125rem rgba(0, 0, 0, 0.1), 0 0.625rem 0.625rem -0.3125rem rgba(0, 0, 0, 0.04)',
    '2xl': '0 1.5625rem 3.125rem -10.125rem rgba(0, 0, 0, 0.25)',
    '3xl': '0 2.1875rem 3.75rem -0.9375rem rgba(0, 0, 0, 0.3)',
    inner: 'inset 0 0.125rem 0.25rem 0 rgba(0, 0, 0, 0.06)',
    outline: '0 0 0 0.1875rem rgba(66, 153, 225, 0.5)',
    focus: '0 0 0 0.1875rem rgba(66, 153, 225, 0.5)',
    none: 'none',
},
```

For instance, `shadow-default` or `shadow-md`.

Similarly with the max width, we don't have a `lg` breakpoint as we're setting custom breakpoints so you'd need to use one of these:
```
screens: {
    phone: '300px',
    'tablet-portrait': '600px',
    'wp-admin-bar': '783px',
    'tablet-landscape': '900px',
    'desktop-min': { min: '1200px' },
    desktop: '1200px',
    'desktop-large': '1600px',
},
```

For instance `max-w-screen-phone`.

**Comment by JaketheYeti** [comment]
Thank you coreymcollins! So simple. Is this all what's defined in the tailwind.config.js?

**Comment by coreymcollins** [comment]
Yup! You're free, of course, to modify that as needed for your own purposes but we found overriding some default Tailwind bits and pieces worked best for our workflow.
