### ISSUE TITLE
Source maps disappearing

### ISSUE THREAD

**Issue by efuller** [WebDevStudios/wd_s#79]
Line numbers are also incorrect

**Comment by efuller** [comment]
Quick update on findings. After testing, it appears that grunt-css min might be the source of the issue. I'll need to dig into the docs and test - https://github.com/gruntjs/grunt-contrib-cssmin/issues

**Comment by efuller** [comment]
After more testing, it appears that the initial cause stated above is not the culprit that is breaking source maps. 

They are breaking when the 'cmq' Grunt task is being run. This is the task that combines media queries and adds them to the end of style.css

At the moment, I think our only option is to decide whether or not we want to continue combining media queries.

**Comment by gregrickaby** [comment]
I have a fix for this. It involves switching to [PostCSS](https://github.com/postcss/postcss). 

I've been testing today and it seems to be working. Plus, we can talk about moving to PostCSS for our post-compilation.

```
postcss: {
            options: {
                map: true,
                processors: [
                    require('autoprefixer')({ browsers: ['last 2 versions'] }),
                    require('css-mqpacker')
            ]},
            dist: {
                src: 'style.css'
            }
        },
```

**Comment by gregrickaby** [comment]
This was fixed when we merged in PostCSS.

https://github.com/WebDevStudios/wd_s/issues/99
