### ISSUE TITLE
Fix i18n variable usage

### ISSUE THREAD

**Issue by JayWood** [WebDevStudios/wd_s#89]
Looking at this https://github.com/WebDevStudios/wd_s/blob/master/functions.php#L137

Should be this

``` php
//...
'description'   => sprintf ( __( 'Widget area for %s', '_s' ), $sidebar_name ),
//...
```

A small bug I know but it doesn't follow WordPress documentation outlined here: https://codex.wordpress.org/I18n_for_WordPress_Developers#Placeholders

I seen it and figured I'd open a ticket.  At this time I'm unaware of any other instances of this occurring but if I see them I'll let you guys know.

**Comment by gregrickaby** [comment]
@JayWood Thank you!
