### ISSUE TITLE
Adding theme.json

### ISSUE THREAD

**Issue by elpuas** [WebDevStudios/wd_s#896]
Theme.json works with both classic PHP-based themes as well as block themes. we can discuss the value of using this feature on wd_s.

https://developer.wordpress.org/themes/advanced-topics/theme-json/#a-theme-json-can-be-added-to-any-theme

**Comment by coreymcollins** [comment]
It'd be cool to find a way to be able to set some of this stuff (like colors) in one place and have it pass through `theme.json` and `tailwind.config.js`. I think it's a great idea to implement `theme.json`, it would just mean remembering to add colors, font sizes, and other styles in potentially multiple places if we also want to set those colors, fonts, and other styles as globals/variables in the Tailwind config.

**Comment by coreymcollins** [comment]
Just saw this – haven't dug into its details or tested it, but maybe some ideas here to start from: https://gist.github.com/alexstandiford/c4fbd990676a7511418f2e669c5be592

**Comment by coreymcollins** [comment]
I spent a little bit of time playing with that Gist above and have some notes below.

Basically, it works! I can adjust the top of our `tailwind.config.js` file to look like this:
```javascript
const fs = require( 'fs' );
const plugin = require( 'tailwindcss/plugin' );
const glob = require( 'glob' );

// Get arrays of all of the files.
const topLevelPhpFiles = glob.sync( './*.php' ),
	directoryFiles = [
		'./inc/*.php',
		'./template-parts/*.php',
		'./src/js/**/*.js',
	];

// Read our theme.json file.
const themeJson = fs.readFileSync( './theme.json' ),
	theme = JSON.parse( themeJson );

// Get colors from theme.json.
const themeColors = theme.settings.color.palette.reduce( ( acc, item ) => {
	const [ color, number ] = item.slug.split( '-' );

	// If there is a number identifier, make it an object.
	if ( undefined !== number ) {
		if ( ! acc[ color ] ) {
			acc[ color ] = {};
		}
		acc[ color ][ number ] = item.color;
	} else {
		acc[ color ] = item.color;
	}

	return acc;
}, {} );
```

Then, where we extend our colors:
```javascript
extend: {
	backgroundOpacity: {
		10: '0.1',
	},
	colors: themeColors,
},
```

In my `theme.json` file, I have some basic colors setup:
```json
{
{
	"version": 2,
	"settings": {
		"color": {
			"defaultPalette": false,
			"palette": [
				{
					"slug": "strong-magenta",
					"color": "#a156b4",
					"name": "Strong magenta"
				},
				{
					"slug": "very-dark-grey",
					"color": "rgb(131, 12, 8)",
					"name": "Very dark grey"
				},
				{
					"slug": "alfredo-yellow",
					"color": "#bada55",
					"name": "Alfredo Yellow"
				}
			]
		},
```

So with this all in place, I can then use `bg-alfredo-yellow` as a color in a stylesheet without having to declare that color in both the `theme.json` file and the `tailwind.config.js` file. Neat!

**Comment by coreymcollins** [comment]
In Slack, Alfredo pointed out that this kind of does double duty in that this creates `--wp-preset-color-alfredo-yellow` and Tailwind’s `bg-alfredo-yellow`.

So you could basically write your styles like:
```css
.site-header {
    background: var(--wp-preset-color-alfredo-yellow);
}
```
or
```css
.site-header {
    @apply bg-alfredo-yellow;
}
```

With the only real advantage being that (if you're using the Tailwind CSS IntelliSense extension) you get a suggestion for Tailwind colors but not the `theme.json` colors:
<img width="600" alt="screenshot of Tailwind CSS IntelliSense suggesting variables based on a string" src="https://user-images.githubusercontent.com/954724/175372563-1f77dfde-1d5b-454a-bf3e-5b85e13ccc2e.png">

So, there may be more digging here if we ended up wanting to do something like this just to kind from repeating compiled styles – especially if we were able to beef this up and pull in paddings, font sizes, etc.

Or maybe this is all just an argument for moving away from Tailwind all together, but I'll let y'all fight that one out 😅

**Comment by khleomix** [comment]
Closing, this has been resolved with the latest release: https://github.com/WebDevStudios/wd_s/releases/tag/v3.5
