### ISSUE TITLE
JS compilation error

### ISSUE THREAD

**Issue by razvanFrandes** [WebDevStudios/wd_s#903]
Hello,

I'm trying to create react blocks, but I get this error in terminal

_You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file_

Any ideas to solve it ?

Thank you.

**Comment by jrfoell** [comment]
Hey @razvanFrandes - we just released a new version of `wd_s` can you update and see if you're still getting the same issue? If you can provide a detailed build log, that would be helpful too. Make sure you're on the right build tool versions per the .nvmrc: Node 14 & NPM 7

**Comment by razvanFrandes** [comment]
Hey @jrfoell,

I have Node:16.14.2 and NPM: 8.6.0. I downloaded the new repo, still same issue when trying to create a simple hello world react component.

Btw, I'm using Windows, maybe there is a problem?

Module parse failed: Unexpected token (6:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```
 function App() {
     return (
       <h1> Hello World! </h1>
     );
 }
```

**Comment by rossberenson** [comment]
I'm also running into this issue. Repo was cloned about two weeks ago. Node and NPM versions confirmed.
