### ISSUE TITLE
Replace lame color variable names with spiffy names

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#92]
Need to swap out these boring names like "lighter-gray" with something a bit more fun.

Copy/Paste the hex codes in `_colors.scss` into http://chir.ag/projects/name-that-color/ and replace!

**Comment by colorful-tones** [comment]
I'm currently working on something that is a bit more robust regarding the color variables and skins. Hoping to have an official PR soon and demo during Designer meeting. For now, here is my branch: https://github.com/colorful-tones/wd_s/tree/color-variables-theme/sass/utilities/colors

**Comment by gregrickaby** [comment]
Fixed in #118
