### ISSUE TITLE
Discussion: Should we move things into an /assets folder?

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#93]
The [plugin generator](https://github.com/WebDevStudios/generator-plugin-wp) places assets into a directory. This allows for a "cleaner" root. Maybe we can follow along?

Move `images`, `js`, and `sass` into `/assets`

Thoughts?

**Comment by bezierer** [comment]
I'm always down for keeping root clean. I was happy about creating the template-parts directory a while back. +1 from me!

**Comment by efuller** [comment]
+1 for me on this.

**Comment by colorful-tones** [comment]
+1

**Comment by coreymcollins** [comment]
I'm not against the idea or anything, but is there a specific reason to do it?  Does having the images, js, and sass directories in the root really make things that much more cumbersome or un-clean?  Or is it combining those things in one place just for the sake of combining things?

I'm fine either way, but just curious if it's really that huge of a deal to begin with or if there are reasons behind it other than "visually" in the folder structure.

**Comment by gregrickaby** [comment]
It's a combination of a few of those reasons.

1) Plugins which are created using the plugin generator (which we're in charge of styling) use the `/assets` folder. It just makes sense to keep things consistent across the project landscape at WDS. This fits perfectly with the saying, "Think of the next developer". We should make things as consistent and easy for "the next person" to work our code.

2) Yes, it cleans up root. Most projects also need a `/fonts` directory and `/bower_components` too.

**Comment by aubreypwd** [comment]
+1

**Comment by gregrickaby** [comment]
All set here...and before the new year! (and new crop of projects for 2016!) :santa:

:https://github.com/WebDevStudios/wd_s/commit/0fe4d34947ca892c866cef44345405c7705642e2
