### ISSUE TITLE
Discussion: Add header/logo support to the customizer?

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#94]
I've seen us starting to use the customizer a bit more. Maybe add this in along with the existing `custom-background` support?

http://codex.wordpress.org/Function_Reference/add_theme_support#Custom_Header

**Comment by colorful-tones** [comment]
I've been using Customizer more, but have yet to come across a usage for Custom Header on our client projects. Do you imagine a particular scenario? Or do you want code included, but commented out?

~~I could see add_section, add_setting, and add_control for logos as being a common functionality that might be good to include?~~ Just re-read title of Issue... +1 for logo support. :)

**Comment by coreymcollins** [comment]
I'm starting to hate the customizer less and less.  I think we should add it.  Every client has a logo and it should be easy for them to replace it if they ever need to update it.

I would say, though, that we should drop some other customizer options like custom-background.  I've opened a new discussion about that, though: https://github.com/WebDevStudios/wd_s/issues/100

**Comment by gregrickaby** [comment]
Custom header support is already in _s, we just removed it way back when. I'd like to put it back in.

**Comment by efuller** [comment]
+1 for adding this back in.
