### ISSUE TITLE
File directory path broken for assets file in scripts.php

### ISSUE THREAD

**Issue by KelseyMcAuley** [WebDevStudios/wd_s#958]
Hi! 

I noticed today that the path to the index.asset.php was broken in scripts.php. I changed it to: 
	$asset_file_path = get_template_directory() . '/build/index.asset.php';
and now it works!

**Comment by kingthrillgore** [comment]
We haven't seen this issue with any recent incidence but the change appears to be harmless enough to mainline. Thanks for your report!
