### ISSUE TITLE
Undefined variable $random_identifier in searchform.php

### ISSUE THREAD

**Issue by gratrockstar** [WebDevStudios/wd_s#987]
In searchform.php, the variable set a the top is named $wd_s_random_identifier, but when it is used later on it is used as just $random_identifier.  This is throwing constant warnings in PHP and should be updated to use the same variable name.

**Comment by khleomix** [comment]
Closing, this has been resolved with the latest release: https://github.com/WebDevStudios/wd_s/releases/tag/v3.5
