### ISSUE TITLE
Discussion: Use PostCSS

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wd_s#99]
I've been doing some testing and would like to drop our Grunt dependencies: "Autoprefixer, Combine Media Queries, CSSComb, CleanCSS, and CSSmin" in favor of [PostCSS](https://github.com/postcss/postcss) plugins. PostCSS plugins would replicate the optimization tasks we currently have in place. The difference is, it does it faster and with less dependencies. 

The first win is, it fixes https://github.com/WebDevStudios/wd_s/issues/79#issuecomment-152767541. 

The second win? This wouldn't require any changes to our workflow (hooray!). We'd still be using `grunt watch` like normal.

Finally, I love that http://codepen.io has added PostCSS to it's arsanal of inline proessors. PostCSS development has a tremendous amount of momentum right now and the list of available plugins is impressive!

This is part of my testing `Gruntfile.js`:

```
// Process Sass with LibSass (like normal)
sass: {
    options: {
        sourceMap: true,
        outputStyle: 'expanded',
        lineNumbers: true,
        includePaths: [
            'bower_components/bourbon/app/assets/stylesheets',
            'bower_components/neat/app/assets/stylesheets'
        ]
    },
    dist: {
        files: {
            'style.css': 'sass/style.scss'
        }
    }
},

// Afterwards, process the compiled style.css using PostCSS plugins
// "AutoPrefixer" and "Media Query Packer".
postcss: {
    options: {
        map: true,
        processors: [
            require('autoprefixer')({ browsers: ['last 2 versions'] }),
            require('css-mqpacker')
    ]},
    dist: {
        src: 'style.css'
    }
},

// Finally, run it through the PostCSS plugin "CSSNano" which runs a
// ton of optimizations and then minifies.
cssnano: {
    options: {
        sourcemap: true
    },
    dist: {
        files: {
            'style.min.css': 'style.css'
        }
    }
},
```

I've been putting this through it's paces today, and so far so good. Thoughts?

Here is a great read on PostCSS: http://webdesign.tutsplus.com/series/postcss-deep-dive--cms-889

**Comment by bradp** [comment]
+1 to PostCSS :+1:

**Comment by colorful-tones** [comment]
Would webpack be a good option to put on the table? http://webpack.github.io/

**Comment by efuller** [comment]
The way I understand how webpack works, it is more of a JS module bundler. It allows you to 'require' things such as CSS / images per module. Not sure that it would fit well into our workflow.

I came across this package for creating a style guide using CSS comments and PostCSS - https://github.com/jonathantneal/mdcss

**Comment by gregrickaby** [comment]
Webpack CAN compile Sass (via node sass). I've been playing with it for a few hours this morning, but I haven't quite figured it all out yet. It's a lot like Browserify. @efuller is right, we'd have to re-structure how we write our Sass and change our workflow as it would also eliminate the need for Grunt.

This is a good read: https://medium.com/@housecor/browserify-vs-webpack-b3d7ca08a0a9#.m74y635wn

**Comment by colorful-tones** [comment]
I'm all for PostCSS +💯and keep our eyes on Webpack.

**Comment by coreymcollins** [comment]
This seems like a pretty boss solution.  I, too, have inconsistencies with source maps from time to time and if we can find a solution that not only fixes that but spruces everything else up a bit at the same time then that's a pretty good bonus.

**Comment by briannaorg** [comment]
+1 for PostCSS and +1 for keeping an eye on Webpack.

**Comment by gregrickaby** [comment]
I think, for now, we switch to PostCSS. We'll retain the same workflow (Grunt), and definitely look at Webpack down the road.

I do think we should stop using /concat and start using [Browserify](http://browserify.org/). But that's another discussion...

**Comment by gregrickaby** [comment]
PostCSS support added in this commit: https://github.com/WebDevStudios/wd_s/commit/a2357e1297e6f7d99c26e68b0a41f88315effbd5
