### ISSUE TITLE
Add tailwind support for patterns

### ISSUE THREAD

**Issue by schlotterer** [WebDevStudios/wd_s#991]
In order to use tailwind classes in block pattern construction can we include the patterns folder in the tailwind.config.js directoryFiles array starting on line 6

`directoryFiles = [
		'./inc/*.php',
		'./template-parts/*.php',
		'./src/js/**/*.js',
		**'./patterns/*.php',**
	];`

**Comment by kingthrillgore** [comment]
I've updated the directoryFiles as follows:

```javascript
	directoryFiles = [
		'./inc/*.php',
		'./template-parts/*.php',
		'./src/js/**/*.js',
		'**./patterns/*.php',
	];
```
